### ISSUE TITLE
Translation for Street Level Quality Layers is not working

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1002]
Somehow the translation for all the Street Level Quality Layers is not working, neither in German nor in English. @majkshkurti maybe you can find the issue?

**Comment by majkshkurti** [comment]
@UJehle I checked this. The issue is that the name in translation key isn't the same with the name of the layer in app-conf.json. 
ex. (wheelchairUsability should be ways_wheelchair in app-conf.json)

**Comment by UJehle** [comment]
Aah thanks @majkshkurti ! I thought it's connected via the style names. I will fix it.
