### ISSUE TITLE
WALKIE: improve Green Index

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1015]
We should improve the Green Index as part of the Walkability Index. We could therefore try to combine different data:
- OSM polygons (landuse=park, etc. ; nature) -> AOIS
- OSM lines (tree rows, etc.)
- OSM points (trees)
- Mapillary image segmentation (Share of Green) 

Score:
Park = 100 Points
Tree Row = ...
Tree = ...
River = ...
Water Stream = ...

**Comment by EPajares** [comment]
NDVI is used to determine green spaces. Final testing still needed.
