### ISSUE TITLE
Improve mapping challenge "width" and "surface"

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1018]
Idea from Rainer:
bei den Radwegen wertet ihr für die Breite und Oberfläche nur die Schlüssel width und surface aus, nehme ich an. Die kombinierten Rad-/Fußwege, die separat neben der Straße als Weg eingezeichnet sind, haben dann cycleway:width, cycleway:surface und footway:width, footway:surface. Beispiel: https://www.openstreetmap.org/way/302423216

**Comment by EPajares** [comment]
We discontinued the development of the mapping mode as we believe it would be more fruitful to continue with mapping activities outside of the GOAT application. Therefore this will be closed.
