### ISSUE TITLE
Documentation feature heatmap

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#103]
We have to document how the accessibility index and accordingly the heat-map is calculated. 
It would be perfect to show the distance-decay function for several parameters. Once we have the heat-map feature improved we can work on this.

**Comment by EPajares** [comment]
@EmnaBH we need to show with an example how the heatmap is calculated. We will document this on the website.

**Comment by EPajares** [comment]
Table for index calculation:
https://github.com/EPajares/goat/blob/development/app/database_functions/heatmap/test_new_impedance_function.ods

**Comment by EmnaBH** [comment]
Can we close this issue?
