### ISSUE TITLE
Show analysis for a coordinate point via API request (e.g. an open-source Walk Score) 

### ISSUE THREAD

**Issue by sbutler-gh** [goat-community/goat#1039]
I would love to be able to load a GOAT analysis for a given location via API.

For example, a user clicks a point on a webmap — webmap sends the coordinate point to the Goat API — and the Goat API responds with a high-level analysis for the accessibility around that coordinate point.

Sort of like an open-source Walk Score!

**Comment by EPajares** [comment]
Hi sounds like an interesting idea! Thanks for rising it here. 
Currently, we only have live GOAT versions in a few municipalities worldwide. As we have to collect local data to produce proper analyses. This also somehow limits us in providing services like a API as users usually expect it to work across the globe. But we have plans to extend the covered area and then this could get more feasible in the future.
