### ISSUE TITLE
Background map "public transport" is not working

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1076]
![grafik](https://user-images.githubusercontent.com/49870195/116369044-3b6b6c80-a809-11eb-9c8a-49e20e9db509.png)

**Comment by majkshkurti** [comment]
@UJehle I checked this service and it looks like http://memomaps.de/ has added a CORS restriction to limit service on other domains.

**Comment by UJehle** [comment]
Too bad. Then we remove this map? Maybe we find a similar one that we can show instad.

**Comment by majkshkurti** [comment]
We decided to use thunderforest
