### ISSUE TITLE
Check imported custom data

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1121]
Currently the imported data is not checked concerning aspects such as:

SRID
Table name
Table schema attributes

Some progress is done here to improve the setup procedure. The idea is to refactor the setup step by step using python classes.

Some WIP can be found here: https://github.com/goat-community/goat/tree/feature/population_disaggregation/app/database/scripts

**Comment by EPajares** [comment]
We would need some sort of configuration were we can define which tables are required and which schema should be met. I will start with defining the most important tables at the moment:

CREATE TABLE public.census (
    id text, (required)
    demography text, (optional)
    geom public.geometry, (required)
    pop integer (required)
);

CREATE TABLE public.landuse (
    landuse text, (required)
    geom geometry, (required)
);

CREATE TABLE public.landuse_additional (
    landuse text, (required)
    geom geometry, (required)
);

CREATE TABLE public.study_area (
    name text, (required)
    sum_pop integer, (required)
    geom geometry (required)
);

**Comment by vcruvinelr** [comment]
> We would need some sort of configuration were we can define which tables are required and which schema should be met. I will start with defining the most important tables at the moment:
> 
> CREATE TABLE census (
> id text, (required)
> demography text, (optional)
> geom public.geometry, (required)
> pop integer (required)
> );
> 
> CREATE TABLE landuse (
> landuse text, (required)
> geom geometry, (required)
> );
> 
> CREATE TABLE landuse_additional (
> landuse text, (required)
> geom geometry, (required)
> );
> 
> CREATE TABLE study_area (
> name text, (required)
> sum_pop integer, (required)
> geom geometry (required)
> );
> 
> CREATE TABLE buildings_custom (
> geom geometry, (required)
> building TEXT,(optional)
> amenity TEXT,(optional)
> residential_status TEXT,(optional)
> housenumber TEXT,(optional)
> street TEXT,(optional)
> building_levels SMALLINT,(optional)
> roof_Levels SMALLINT,(optional)
> height float(optional)
> );

All of this tables are mandatory for the first load or only "study_area.shp"?

**Comment by EPajares** [comment]
Sorry for not answering here. In theory only study_area.shp is needed. But for a proper deployment also the other data tables are suggested.
