### ISSUE TITLE
Scenarios are only working when refreshing the page (F5)

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1159]
There is an issue with the scenarios.. often they are only working when first reloading the page with F5. 
Not sure if there is a way to fix this?

**Comment by EPajares** [comment]
This is a general issue. Basically the client code is loading from the cache of your browser. It is not specific to the scenario but could also affect other features. @majkshkurti maybe you could research on some options to force the browser to load fresh client code

**Comment by EPajares** [comment]
Some strategies are summarized here: https://code-boxx.com/force-browsers-reload-javascript-css/

**Comment by majkshkurti** [comment]
We can try to autoincrement the version number in package.json when pushing the last commit. 
Running `npm version patch` for small updates or maybe a `pre-release` git hook script should fix this issue.

**Comment by EPajares** [comment]
I did so today for the new Freiburg release. I think it worked. 
We might need a more automated way though. I will leave the issue open put remove the label as bug.
