### ISSUE TITLE
Legend Landschaftsplan

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1185]
There seems to be an issue with some WMS legends.
![grafik](https://user-images.githubusercontent.com/49870195/126129068-39f29188-51e3-4628-a049-90a9e9ec5ef6.png)
![grafik](https://user-images.githubusercontent.com/49870195/126129807-2e369deb-bb93-44a2-b070-97965304a41f.png)

**Comment by majkshkurti** [comment]
@UJehle I just checked this and the reason why it doesn't work is related to CORS policy. Apparently http://risby.bayern.de/ doesn't allow usage out of their domain. The layer doesn't work either.

**Comment by EPajares** [comment]
This is a particular data problem. I will close this issue.
