### ISSUE TITLE
Cannot edit style point layer

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1212]
![image](https://user-images.githubusercontent.com/42171996/129043179-0bc4dc06-4306-4d16-b90c-5dc5a01224bf.png)

**Comment by Ebubeker** [comment]
I managed to fix this issue too. The main problem was that the changes were not added to the styles. So every time a new change happens the style is overwritten

**Comment by EPajares** [comment]
Thanks! For the points, we would also need to change the color of the marker. Changing the color for the icon might not be possible but for the normal marker it should be. You can check the component of the other layers. Like this one:
![image](https://user-images.githubusercontent.com/42171996/183747177-28ab95b4-166e-4f2b-b0a3-ab478b6e93ab.png)

**Comment by Ebubeker** [comment]
Ok I understand, I will make sure to add that functionality too.
