### ISSUE TITLE
"Show Street network" is missing

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1221]
![grafik](https://user-images.githubusercontent.com/49870195/134166446-6b0d2497-de8a-441f-bad7-ef3f4ac8b7f3.png)

**Comment by UJehle** [comment]
(this bug is found in Freiburg and Munich version)

**Comment by EPajares** [comment]
For the 15-Minute isochrone the bug is not there. Anyway we will tackle within the next weeks.
