### ISSUE TITLE
POIs are not updating

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1229]
POI selection is not updating. First, I have chosen Tram + ubahn stops. Then I disabled both and chose "bar" but the map is not updating. At this point in time, the menu on the left was hidden. The POI selection only updated when I opened the menu on the left. I guess there is some kind of logic issue here.
![grafik](https://user-images.githubusercontent.com/49870195/143719719-75cbf32a-685d-4c9f-b9a5-2ef6237962c8.png)

**Comment by EPajares** [comment]
Will close this as we currently rewritten the whole POIs interaction.
