### ISSUE TITLE
Isochrones are displayed below AOIs

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1231]
The isochrones are shown below the AOIs. I think it would look nicer & make more sense to put the isochrones on top or at least give the option to adjust the layer order in the layer menu (isochrones are currently not listed in there). 
![grafik](https://user-images.githubusercontent.com/49870195/143720386-19c86be3-a986-416c-a3d7-ef8c3e6e67ed.png)

**Comment by UJehle** [comment]
This somehow only happens when going into the "layer" menu. As long as I am in the "isochrone" menu, the isochrone ist on top.

**Comment by EPajares** [comment]
This is fixed in the new release
