### ISSUE TITLE
Improve map print for isochrones

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1232]
It would be nice to have a legend for the isochrones. I know we once discussed this and that it's quite tricky. but would something like this be possible (I have now done this in PowerPoint :D)? 
![grafik](https://user-images.githubusercontent.com/49870195/143720612-8ac2237f-28c7-4009-a527-3e1c10dc3af5.png)
To directly show the minutes of the isochrones on the map? Plus, we should somewhere state if this isochrone is for walking, cycling, etc. and which speed is used.

**Comment by EPajares** [comment]
This is fixed.
