### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1234]
![grafik](https://user-images.githubusercontent.com/49870195/143939335-e7707095-0f6c-453a-ab44-207ea5985cb0.png)

**Comment by vagvaf** [comment]
I checked this a bit this morning because it seemed easy to fix, but it seems that it is resolved. Can someone confirm? And if yes, should this be closed?

**Comment by EPajares** [comment]
Yes this is fixed. We changed the way the layer will be translated in the new version. So I will close it. Thanks
