### ISSUE TITLE
Rename "Isochrones (2)"

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1235]
We got the feedback today, that the number of isochrone slider is not self explaining. 
It would help to rename it --> "Number of Isochrones" (German: "Anzahl der Isochronen"). In addition, the icon is not that fitting. Can we maybe replace this with an icon that shows an isochrone? 
![grafik](https://user-images.githubusercontent.com/49870195/145852012-72d380e5-a94b-491e-b3fc-1a91237bfd84.png)

**Comment by EPajares** [comment]
This is fixed
