### ISSUE TITLE
Bug in Multi-isochrone calculation 

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1237]
Here, the calculation of multi-isochrones is not working although only 66/150 amenities are chosen. Not sure what is the issue. 
![grafik](https://user-images.githubusercontent.com/49870195/149085918-0f9a6ae1-639e-4656-b667-7473ed92d795.png)

**Comment by EPajares** [comment]
Actually, there is a timeout after I believe 60s. So, in case the isochrone is not finished until then it will stop. This is mostly a resource issue now in the database. Should be fixed in the new release. Therefore, I will close this issue now.
