### ISSUE TITLE
Frontend e2e testing workflows

### ISSUE THREAD

**Issue by majkshkurti** [goat-community/goat#1278]

**Comment by UJehle** [comment]
Hi @majkshkurti ! I have just seen that I am assigned to this issue. But I have no clue what it is about :D 
Do you remember what the task here is?

**Comment by majkshkurti** [comment]
@UJehle Yes, the idea is to have some common workflows that users in order to write testing for the UI (e2e)

**Comment by majkshkurti** [comment]
@UJehle Yes, the idea is to have some common workflows that users in order to write testing for the UI (e2e).

_For example:

- Calculate Single Isochrone.
Steps:
1) Click calculate button
2) Click on the map
Output:
- Expect isochrone shape
- Results section length should increase by one._

**Comment by UJehle** [comment]
Aah I see. Thanks for the explanation! I think we could pretty much take the steps from the [Tutorials](https://plan4better.de/en/tutorials/isochrone/). Shall I copy them from there into a word-dok, or in which format would you ideally need it?
