### ISSUE TITLE
Can we make the search function smarter?

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1307]
Is there an option to make the search function smarter? Basically only showing results within the study area?
![grafik](https://user-images.githubusercontent.com/49870195/166295622-3d53ac1f-43e9-40a6-99d4-c8ed0fea34fd.png)

**Comment by EPajares** [comment]
I believe the API receives a bounding box and not the exact borders of the study area. So it could be that the coordinates are outside of the study area.

**Comment by EPajares** [comment]
As discussed, we have to change the API we use for this. So first we need to find a suitable service.

**Comment by UJehle** [comment]
Okay I see. If this is complicated, then never mind. It was just an idea. Probably it's not super important to have this.
