### ISSUE TITLE
Language issue

### ISSUE THREAD

**Issue by majkshkurti** [goat-community/goat#1324]
The issue occurs when the browser language is different from English or German. The payload send to the server should fall back to English in unsupported languages.

![Screenshot 2022-05-23 141322 5399](https://user-images.githubusercontent.com/32641116/169844176-65d10006-1668-44b8-a062-d2901b157bb0.jpg)

**Comment by EPajares** [comment]
@Ebubeker You can do a feature branch from Master and we will merge it then as hotfix.
