### ISSUE TITLE
Explore way of documentation using Redoc

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1337]
Currently, documentation using REDOC is automatically generated in FastAPI. This is created as it provides an easy way to get started with the documentation. Though this automatic documentation could be extended with additional description. For instance a small developer guideline for the API. Or a checklist that should be followed when creating an endpoint as described here #1334.

So it would be great to explore how this information could be added there and do some first tests in extending the automated documentation. In a second iteration, we would have to see what content we should add next.

**Comment by metemaddar** [comment]
To create the **general description** using markdown doc-strings and meta data we have the following instructions: [docs](https://fastapi.tiangolo.com/tutorial/metadata/)

Also we can **add description to endpoint** in markdown doc-string as specified here: [docs](https://fastapi.tiangolo.com/advanced/path-operation-advanced-configuration/?h=description#advanced-description-from-docstring) 

We can also add **summary and description for every field** of the endpoint: [docs](https://fastapi.tiangolo.com/tutorial/path-operation-configuration/#summary-and-description)
