### ISSUE TITLE
Improve Multi Isochrone performance

### ISSUE THREAD

**Issue by majkshkurti** [goat-community/goat#1353]
Currently, the multi-isochrone calculation is calculated by the union of multiple single isochrone calculations. The large network data prevents this solution to scale in more than 100-250 points. 
To improve it we should consider having a smarter approach when looping the network. We can consider storing the travel time cost for the visited network edges and exclude it for the next points if it's smaller.

**Comment by metemaddar** [comment]
I was thinking also about extracting variable declarations out of the loops. Also made a commit for it. But while searched again, found that it has no effect. Because after compile, all [POD-type](https://stackoverflow.com/questions/146452/what-are-pod-types-in-c) declarations will go at the beginning of the function ([ref](https://stackoverflow.com/questions/982963/is-there-any-overhead-to-declaring-a-variable-within-a-loop-c)). As we use the POD types for all of our variables, and batch extracting the variables would also create some bugs. So I revert the commit.

**Comment by metemaddar** [comment]
I'm going to use the python profile library named [tracemalloc](https://docs.python.org/3/library/tracemalloc.html) to profile the memory consumption (as discussed [here](https://stackoverflow.com/a/45679009/1951027))

**Comment by metemaddar** [comment]
I think the memory allocated by VS Code debugger. Because the tracemalloc showed the biggest memory change is 4.8 KB for grid creation:
```
/app/./src/core/isochrone.py:49: size=4848 B (+4848 B), count=69 (+69), average=70 B
<__array_function__ internals>:179: size=4184 B (+4184 B), count=24 (+24), average=174 B
/usr/local/lib/python3.9/site-packages/numpy/lib/function_base.py:1423: size=3616 B (+3616 B), count=3 (+3), average=1205 B
<__array_function__ internals>:180: size=3416 B (+3416 B), count=18 (+18), average=190 B
/usr/local/lib/python3.9/site-packages/scipy/sparse/_compressed.py:1041: size=3064 B (+3064 B), count=39 (+39), average=79 B
/usr/local/lib/python3.9/site-packages/scipy/sparse/_coo.py:402: size=1120 B (+1120 B), count=6 (+6), average=187 B
/usr/local/lib/python3.9/site-packages/scipy/sparse/_base.py:299: size=1088 B (+1088 B), count=6 (+6), average=181 B
/usr/local/lib/python3.9/site-packages/numpy/core/getlimits.py:654: size=1008 B (+1008 B), count=18 (+18), average=56 B
/app/./src/core/isochrone.py:50: size=904 B (+904 B), count=9 (+9), average=100 B
```

It was created with the following code:
```
snapshot1 = tracemalloc.take_snapshot()
GRID = isochrone_single_depth_grid(network, starting_ids, [25])
snapshot2 = tracemalloc.take_snapshot()
top_stats = snapshot2.compare_to(snapshot1, "lineno")
print("[ Top 10 differences ]")
for stat in top_stats[:10]:
    print(stat)
```

**Comment by metemaddar** [comment]
@majkshkurti, I could find the memory usage as you find out. I did the profiling in a wrong way. As doc said, we should run the start method of tracemalloc as soon as possible. I tried again with running from the isochrone.py itself and it could detect 16GB of memory usage for the sparse matrix.

I think I can write it again with a small footprint.

The results:

```
/usr/local/lib/python3.9/site-packages/scipy/sparse/_coo.py:400: size=16.0 GiB (+16.0 GiB), count=3 (+3), average=5461 MiB
<frozen importlib._bootstrap_external>:647: size=61.6 MiB (+2696 KiB), count=562502 (+28268), average=115 B
/usr/local/lib/python3.9/abc.py:106: size=4426 KiB (+1723 KiB), count=18153 (+6553), average=250 B
/app/src/core/dijkstra.py:17: size=666 KiB (+666 KiB), count=6560 (+6560), average=104 B
/usr/local/lib/python3.9/abc.py:123: size=1279 KiB (+423 KiB), count=12869 (+4489), average=102 B
/usr/local/lib/python3.9/abc.py:107: size=973 KiB (+351 KiB), count=5924 (+2289), average=168 B
/app/src/core/dijkstra.py:68: size=288 KiB (+288 KiB), count=1 (+1), average=288 KiB
/app/src/core/dijkstra.py:67: size=288 KiB (+288 KiB), count=1 (+1), average=288 KiB
/app/src/core/isochrone.py:56: size=284 KiB (+284 KiB), count=17 (+17), average=16.7 KiB
<__array_function__ internals>:180: size=304 KiB (+256 KiB), count=435 (+18), average=715 B
```
