### ISSUE TITLE
Add external layers from (WMS, WMTS). 

### ISSUE THREAD

**Issue by majkshkurti** [goat-community/goat#1357]
This feature enables users to add layers from external geoportal endpoints. For this, we will need a simple UI that allows previews of the layers with a button to add them to the layer tree. 
In the layer tree, the external layers are grouped under a new group "External Layers" with all the options as other layers. 

A similar implementation is done in geomapfish. 
[https://geomapfish-demo-2-7.camptocamp.com/?lang=en](https://geomapfish-demo-2-7.camptocamp.com/?lang=en)

**Comment by EPajares** [comment]
I am closing this now as I just merged the code in dev. I will open some new issue that are related to this feature. As I am experienced some smaller things that need to be improved. @Ebubeker Thanks a lot for working on this.
