### ISSUE TITLE
Add endpoint for CRUD operations to add vector layer to schema extra

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1358]
In the schema extra, we are storing our static layers. These layers have no interactive logic but are used for visualization purposes only. For example, we show the number of accidents. We need an endpoint that allows us to upload this data via the dashboard.

**Create:**
1. The supported file formats should be **Shapefile (zipped), GeoJSON and Geopackage.** As Geopackage is a database it can contain several layers. In such a scenario all layers should be added. 
2. The files can come with different projections. They can be usually handled by Geopandas unless no projection is set. We should always change the projections to EPSG 4326 as this is our default one in the DB.
3. Each file or each table in the case of Geopackage should be created as a new database table in the schema extra. 

**Read:**

1. Read the name of the table + evtl. the 100 first rows. 

**Update:**

1. Overwrite an existing table with new data. I would just delete the old table and then add the new table as the schemas could be different.

**Delete:**

1. Delete the table with the specified name. 

**Very important, we should make sure that no other schema is touched as there we have the system tables.**

We are already using Geopandas to upload the Custom POIs from the user. This is another use case but could be a source of inspiration: https://github.com/goat-community/goat/blob/main/app/api/src/crud/crud_upload.py

**Comment by metemaddar** [comment]
So we would need such a model to save uploaded meta data:

```
Table: static_layers
id: int
user_id: int
table_name: string, unique, random_string()
type?: choice(string)
deleted?: bool
.
.
.
```

**random_string()**: Can be a character or string plus UUID (as UUID can start with a number)
**example**: `static-layer-123e4567-e89b-12d3-a456-426655440000`

- UUID is 32 character length (Hexadecimal numbers) ([ref](https://www.uuidtools.com/what-is-uuid))
- postgresql table name can be up to 63 characters starting with a letter or an underscore ([ref](https://www.informit.com/articles/article.aspx?p=409471)).

**Comment by EPajares** [comment]
Thanks @metemaddar for the very good though! We were not thinling about it as we kind of had a narrow view on it as we considered that only the superuser can add data. But maybe this would limit us to much. Because it could be interesting for the other user to also add layers in the future.

**Comment by EPajares** [comment]
Thanks @metemaddar for the very good though! We were not thinling about it as we kind of had a narrow view on it as we considered that only the superuser can add data. But maybe this would limit us to much. Because it could be interesting for the other user to also add layers in the future.

**Comment by EPajares** [comment]
Maybe we could create such a model. But I think maybe we would only need the columns:

- id
- table_name (using uuid)
- user_id

Or you wanted to add type for some more logic?

**Comment by metemaddar** [comment]
Great. Depending on the usage, we can add some other meta data. And also it can have a name for the administration dashboard to get access from client. I think that's fine for the moment. Some meta data can be calculated by database like some sizes and layers (As we can see in the data frame columns) if it's needed.
