### ISSUE TITLE
Style scenario network features to show if they are usable by foot and bicycle 

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1359]
Sometimes it happens, that the bridge scenario is not working properly and the "scenario" isochrone basically looks like the "standard" one. I think I now understood why: the network that the circle tool shows seems to be not in line with the routing network. At Wittelsbacherstraße for example.
![Bild1](https://user-images.githubusercontent.com/49870195/176266412-45a87cbe-d8c6-43d1-abd8-cc58783206f1.png)

**Comment by EPajares** [comment]
Many things are coming two things together here. 

1. First, the network on OSM is, from my point of view, wrongly classified. The paths are labeled as "use_sidepath", but no separate sidepaths are drawn. This is causing connectivity problems.

2. We were fetching the whole network, including the parts that are labeled e.g. foot=use_sidepath or bicycle=use_sidepath.
Though we are excluding these classes for the routing. 

I am now filtering by the foot categories to exclude. Though this is not the perfect solution as we are not handling the ones excluded for bikes. The best would be styling the features to show whether they are usable by foot and bike. And show features that are not suitable for one or the other. Though this would require some more changes. So I have patched this temporary fix.
