### ISSUE TITLE
Admin Dashboard (Stack research)

### ISSUE THREAD

**Issue by majkshkurti** [goat-community/goat#1365]
# Goal of this issue
Consider using React framework for the dashboard with Typescript support. We have to decide which library can help us for accelerating the development. 

# Resources
The following library is worth investigating into :

- React Admin

# Deliverables
At the moment for the dashboard, we will create a new repository and merge it at a later stage on GOAT main repo. 
The current repo is here: https://github.com/goat-community/dashboard

Though we can start the project from scratch.

**Comment by EPajares** [comment]
The current repo is this one: https://github.com/goat-community/dashboard
But we can start it from scratch.

**Comment by cinaaaa** [comment]
I think that it's really Ok to move forward with this library for now!
