### ISSUE TITLE
White Box in left menu appears in printing menu

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1372]
![grafik](https://user-images.githubusercontent.com/49870195/177868187-7cf3f7c4-e2a6-4295-bb5a-af54a4f2879c.png)

In the printing menu, a white box appears in the left menu (see screenshot). I guess that it's not meant to be like that.

**Comment by EPajares** [comment]
I somehow cannot reprodoce this. Could you provide more context? Ideally considering the information of the issue template.

**Comment by EPajares** [comment]
This issue is also duplicated here #1319

**Comment by UJehle** [comment]
Oh true, I already reported it :D 
Hmm, maybe it's a browser issue (I am using Firefox). It happens when I am in the "other layers" menu.
![Bild1](https://user-images.githubusercontent.com/49870195/178102431-420bf63c-1e26-46f0-a23c-023daba7c78d.png)
