### ISSUE TITLE
Allow for round scales for printing

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1373]
![grafik](https://user-images.githubusercontent.com/49870195/177869261-1bdb8686-7201-48b9-aa36-0c2d9986425c.png)

**Problem:**
When printing a map, the scale is always odd.

**Solution I'd like:**
Is it somehow possible to have an option to set the scale to round numbers (e.g. 1 : 45.000)? Maybe by a dropdown, slider, or something similar in the menu on the right side? That would be cool and look a bit better on the print.

**Comment by majkshkurti** [comment]
This can't be achieved in the client printing. Maybe we can remove the scale number.

**Comment by UJehle** [comment]
Ya that would be an easy fix. Thanks!

**Comment by Ebubeker** [comment]
I managed to remove the text above the scale line.
