### ISSUE TITLE
Improve German translation of Printing Form

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1374]
# Goal of this issue
Improve the German translation of the Printing Form.
Concrete: Replace "Legend" by "Legende".

![grafik](https://user-images.githubusercontent.com/49870195/178102506-1a4a3998-b27e-4a0c-b39c-41042de2c3f4.png)

# Resources
NA

# Deliverables
Fixed translation

**Comment by Ebubeker** [comment]
This issue has been fixed and now it refers directly to the language files and it shows correctly "LEGENDE"
