### ISSUE TITLE
Multi isochrone population count

### ISSUE THREAD

**Issue by majkshkurti** [goat-community/goat#1376]
# Goal of this issue
Currently, the multi-isochrone population count is aggregated on a study area level. We should find a way of adding the population in the new "grid" approach. 

# Resources

# Deliverables

**Comment by metemaddar** [comment]
Would you check the zoom level for multi-isochrone? I think it's zoom level maybe is different than the other parts.
For example for transportation we have zoom level of 9 but for multi-isochrone it's 10 (hard coded). Maybe it effects the calculation.
