### ISSUE TITLE
Admin Dashboard - CRUD Style

### ISSUE THREAD

**Issue by majkshkurti** [goat-community/goat#1378]
# Goal of this issue
Create user interface to create styles for layers.

# Resources

# Deliverables

**Comment by EPajares** [comment]
@cinaaaa There is a small bug with the JSON editor on chrome I believe. It does not allow me to go very right in the editor. So I cannot change the last 5 or so characters of one line.

**Comment by cinaaaa** [comment]
@EPajares Thanks Elias for reporting, I'll check this
