### ISSUE TITLE
Admin Dashboard - CRUD Users

### ISSUE THREAD

**Issue by majkshkurti** [goat-community/goat#1379]
# Goal of this issue
Ability to see users list and apply CRUD on them in the dashboard users tab.

# Resources

# Deliverables

**Comment by metemaddar** [comment]
@cinaaaa 
From witch branch are you getting the API?

**Comment by cinaaaa** [comment]
@metemaddar I'm using https://goat-dev.plan4better.de/api/v1/

**Comment by majkshkurti** [comment]
@cinaaaa The skip and limit parameters are already there but the sort and filter we haven't implemented yet. 
Maybe, for now, you can try to do it on the client as we don't have a lot of users anyways. The user list response will be rather small.

**Comment by cinaaaa** [comment]
@majkshkurti  To handle pagination I need to have a total users count, besides the filters.
`{data: [...], count: all of the users' count in our database}`

**Comment by cinaaaa** [comment]
The search and paginations handled in the client side
