### ISSUE TITLE
Users PUT error

### ISSUE THREAD

**Issue by cinaaaa** [goat-community/goat#1381]
### Summary 📃

When I wanna send a partial update for a user, I get a 500 internal server error response.

### Expected Behaviour ✔

Expected to have the updated user object.

### Current Behaviour 🔦

500 internal server error

### Steps to reproduce 👣

Send PUT request to `/api/v/users/{user_id}` for update a current user

**Comment by metemaddar** [comment]
The following error has occurred while attempting to update and `study_area` wasn't in the payload:

```
INFO:     127.0.0.1:41608 - "PUT /api/v1/users/119 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
.
.
.
  File "/app/./src/crud/crud_user.py", line 47, in update
    if update_data.get("study_areas") or len(update_data["study_areas"]) == 0:
KeyError: 'study_areas'
```
I'll PR a patch for it.

**Comment by cinaaaa** [comment]
Now it's working
