### ISSUE TITLE
Add CRUD for Geostores

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1391]
# Goal of this issue
We are having a table listing all geostores. A geostore is a platform where geospatial data can be retrieved from. Usually these are maintained by public authorities. The table with the Geostores needs to be maintained.

Further it should be possible to assign a Geostore to each study area.

# Resources

The models where created and the database tables are in the dev deployment. They are called customer.geostore and customer.study_area_geostore.

# Deliverables
CRUD endpoints for the Geostore tables. For the Geostore endpoints I would create a API section called **Geostore**

# Branch to derive
Dev

**Comment by metemaddar** [comment]
Endpoints to add:

- CRUD for customer.geostores
- Add/Remove for customer.study_area_geostore (M2M)

**Comment by EPajares** [comment]
We can only do some minimal validation for customer.geostores.

- Check if URLs return data
- Check if configuration is makes use of the right keys. The keys we are specifying are from this object
`{
"url": "mapURL",
"name": "Name",
"description": "LayerDescription",
"type": "LayerType",
"legend": "legendUrl",
"attribution": "attribution",
"getcapabilities": "GetCapabilities"
}`
