### ISSUE TITLE
Try to add categories for external layers

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1395]
# Goal of this issue
The first version for exporting external layers works. Though in the case of large geoportals listing all layers means a challenge for the user to find the layers he is interested in. So we could explore using the layer groups most geoportals provide. 

![image](https://user-images.githubusercontent.com/42171996/181259514-0f1b6dde-1f6f-4827-8b97-3debb44750ac.png)

# Resources
Check some of the following geoportals:
https://geoportal.bayern.de/
https://monitor.ioer.de

# Deliverables
There could be categories added here to filter the layers.
![image](https://user-images.githubusercontent.com/42171996/181260079-5bed3b2b-4f38-4223-874f-1daf6769f0a6.png)

# Branch to derive
dev

**Comment by Ebubeker** [comment]
I will try to find something about categories. There has to be something since the Bayern geoportal access the layers from the same source. So I will try something.

**Comment by Ebubeker** [comment]
![keywords](https://user-images.githubusercontent.com/60944813/182584921-67be5f6c-2c7e-4c8d-8dee-aa11cc631d6e.png)

## Another Solution
I have found another way where we can categorize the layers. It is through keywords, basically every layer has some keywords, it is more like the blog websites where each post has keywords, so u can categorize them or even use them as search properties.

**Comment by EPajares** [comment]
Thanks for this! Interesting idea. This is better than nothing. I assume not all geoportals have it though right?

**Comment by Ebubeker** [comment]
Mostly all the getCapabilities urls have at least one or two keywords. But anyways I can give it a try since I don't have a task at the moment

**Comment by EPajares** [comment]
Yes please give it a try. Thank you very much.

**Comment by Ebubeker** [comment]
I sadly couldn't do anything about it, it is not possible to do anything. All the geoportals have it but in order to get it we have to fetch them, and fetching 900+ geoportals at a time will slow down the website

**Comment by EPajares** [comment]
This was not implemented as it would mean a significant loss of performance.
