### ISSUE TITLE
Create Readme for Dashboard Repo

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1403]
# Goal of this issue
Create a readme with basic information for the dashboard repo.

# Resources

# Deliverables
Readme

# Branch to derive
Main

**Comment by cinaaaa** [comment]
@EPajares  You mean a Technical or "How To" document on it?

**Comment by EPajares** [comment]
I believe the content should be the following:

- Purpose of the repo and a link to the GOAT main repo
- How to

**Comment by cinaaaa** [comment]
@EPajares  I just did it, it's a simple and minimal document file to have a quick overview from the dashboard
https://github.com/goat-community/dashboard/blob/main/README.md
