### ISSUE TITLE
Add return arrow to get back to previous step

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1408]
# Goal of this issue
Actually it would be great to have a "Get back arrow" so we can return to the overview of all categories.

![image](https://user-images.githubusercontent.com/42171996/182927730-ad1c87a7-80ae-41ff-a8cd-da8412dfc129.png)

# Resources

# Deliverables
Add return button to get to the previous layer overview.

# Branch to derive
Dev

**Comment by Ebubeker** [comment]
Task has been finished, I also fixed some small mistakes along the way and I think that most of the things for now are alright.

**Comment by EPajares** [comment]
Great! Could you do a PR against the dev branch. I will review it then.
