### ISSUE TITLE
Add documentation for new indicators

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1412]
# Goal of this issue
We are adding new indicators like: 

- (Cumulative Opportunities heatmap for public transport)
- Station count

For these indicators we need a documentation.

# Resources

# Deliverables
New documentation on the website.

# Branch to derive

**Comment by UJehle** [comment]
@dilaann could you check which documentation parts are still missing and open individual issues for them, if necessary coordinate with @majkshkurti

**Comment by EPajares** [comment]
Only add station count

**Comment by UJehle** [comment]
@dilaann will check if we can use the content of Majk's Thesis

**Comment by UJehle** [comment]
Thanks @dilaann for the draft! 
I just adjusted it a bit and translated it into German.
@EPajares if you like you could have final look, then I can bring it online.

**Comment by EPajares** [comment]
![image](https://github.com/goat-community/goat/assets/42171996/f0250c8f-bfd8-416f-a40e-0c1e9bd73b05)

I would say "Bedienungshäufigkeit"

Maybe this sense needs to be checked. "Varieren zu" seems bit wrong to me.
Wie variiert das ÖPNV-Angebot zu Wochentagen oder Tageszeiten?

Maybe we can mention that this indicator is often part of "Schwachstellenanalyse" in "Nahverkehrsplänen". Eventually we also find some more reference to the some guideline. There should be a guideline for the state of bavaria on Nahverkehrspläne.
