### ISSUE TITLE
Avoid empty key value pairs for geostore config in Dashboard

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1430]
Avoid sending empty key-value pairs when sending configuration via the dashboard. 

![image](https://user-images.githubusercontent.com/42171996/184138981-cee473ff-78fe-4449-871c-0faa471c3265.png)

## Expected Behavior

If the value is empty for one of the keys the key-value pair should not be sent to the endpoint. 
## Current Behavior

It produces empty key-value pairs
## Possible Solution

Don't add the key-value pairs to the payload.

**Comment by cinaaaa** [comment]
@EPajares  If all the key values (even the empty ones) are not presented on the object we will get into 
```json
{"msg":"configuration keys should be exactly as of \"URL, name, description, type, legend, attribution, getcapabilities\"}
```

**Comment by EPajares** [comment]
Thanks for reporting the issue. I know the problem in the API, but I would have to discuss with @metemaddar what would be most consistent way in fixing this. Let's discuss this tomorrow.

**Comment by EPajares** [comment]
@metemaddar, I was checking this there seems to be a problem. When one key has an empty value inside the database, the complete JSON is overwritten and replaced by the word "Null".

**Comment by metemaddar** [comment]
@EPajares, Which data for example. For me, the geostore with id=3, has an empty configuration, but it returns as empty string. But for id=44, it was created without configuration and it returns json `null` value. How did you test?

**Comment by EPajares** [comment]
Sorry, I was testing this again, and it works.
