### ISSUE TITLE
Delete many rows at the same time for dashboard tables

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1435]
# Goal of this issue
New feature to delete many rows simultaneously by checking a checkbox in the table.
 
![image](https://user-images.githubusercontent.com/42171996/184497973-b6b513d8-fefe-4f21-84a1-fc97236bd4bf.png)

# Resources

# Deliverables
New feature for each table that allows deleting several rows simultaneously by clicking on a checkbox per row. 

# Branch to derive
Main

**Comment by cinaaaa** [comment]
This is done but need API deployment before my side deploy
