### ISSUE TITLE
Bring two text boxes in line

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1436]
# Goal of this issue
A very small thing to improve. The two textboxes are not perfect in line. There is a small distance between both, as seen in the screenshot
![image](https://user-images.githubusercontent.com/42171996/184498278-a04aee87-3f07-4ebc-850b-018ceea7acce.png)

# Resources

# Deliverables
Bring text boxes in line.

# Branch to derive
Dev

**Comment by Ebubeker** [comment]
It is done
