### ISSUE TITLE
Update endpoints to allow for delete-many

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1438]
# Goal of this issue
Allow deleting many features at the same time using our existing endpoints. A list of ids should be passed and accordingly the features be deleted. Most of the delete endpoints would be affected. Though there are some exceptions. Delete many should be implemented for the following endpoints:

![image](https://user-images.githubusercontent.com/42171996/184607031-627f2bc6-db2a-4dd8-bc13-e793af515377.png)
![image](https://user-images.githubusercontent.com/42171996/184607132-a781f89c-2a36-4339-8e79-a9d8e4cf7105.png)
![image](https://user-images.githubusercontent.com/42171996/184607179-21412f62-f8e6-4986-aa3d-e6c855eaee14.png)
![image](https://user-images.githubusercontent.com/42171996/184607237-6ab32f79-6b4d-4d5d-9b2a-c9bb649d39b7.png)
![image](https://user-images.githubusercontent.com/42171996/184607274-561eb855-e5e7-441a-b6ba-0204e484a7a8.png)
![image](https://user-images.githubusercontent.com/42171996/184607305-eff7e96d-40da-4561-99ce-f33ec529638c.png)

# Resources
Existing code from the mentioned endpoints.

# Deliverables
Delete many functionalities for the mentioned endpoints. Adjust tests.

# Branch to derive
Dev

**Comment by metemaddar** [comment]
I think it would be good to add this functionality to CRUD_BASE.delete() so that it can take also list as input id.
Also we would change the input type to Union(LIST[INT],INT).

**Comment by EPajares** [comment]
I guess this should not break anything, right?

**Comment by metemaddar** [comment]
Yes, I think it won't break anything. Because we can check the input type at Base.delete() before perform delete. I should check more at endpoint procedure.
A question is what should we do if there is some already deleted id in input list. As we raise 404 when the input id is not present at the table.
Maybe we shouldn't raise 404. Because when the object is not present, it means maybe it is deleted before. There is a discussion at [StackOverFlow that suggest not to raise 404 (at comments)](https://stackoverflow.com/a/6440374/1951027).


![Image](https://user-images.githubusercontent.com/3726265/184849868-ba1d09ba-60a7-402f-9884-01965c067de0.png)

**Comment by metemaddar** [comment]
The RFC also suggests says we should raise 204 (No content) when the object is not present at table ([ref](https://www.rfc-editor.org/rfc/rfc7231#section-4.3.5)):

> If a DELETE method is successfully applied, the origin server SHOULD
>    send a 202 (Accepted) status code if the action will likely succeed
>    but has not yet been enacted, a 204 (No Content) status code if the
>    action has been enacted and no further information is to be supplied,
>    or a 200 (OK) status code if the action has been enacted and the
>    response message includes a representation describing the status.

Of course it doesn't say about deleting multiple objects, if some of them are not present.
If some of them are present, the request should be accepted (202) and if some of them not present (204?)
However it says the response can be 200 + a message that describes the status.

**Comment by metemaddar** [comment]
I suggest at the moment to

- response 200 for multiple objects (Any time)
- response 200 if there is only one object to delete and it was deleted (Presents at the moment)
- response 204 instead of 404 when the object is not present at table.

**Comment by metemaddar** [comment]
The endpoint: `scenarios/{scenario_id}` is used for Goat Client. Should be refactor it as well? @EPajares
