### ISSUE TITLE
Roll back data after test

### ISSUE THREAD

**Issue by metemaddar** [goat-community/goat#1441]
**Main problem**
Database gets populated by dummy data after testing. Sometimes we have around 10 records for complex endpoint testing. Mostly these data have random and meaningless values.
Removing test data can help us have more clear and reliable data at database while developing client or database itself.

**Solution**
We can have rollback functionality at testing, so that the SqlAlchemy would rollback the data for us. There is an example for java [here](https://jenkov.com/tutorials/java-unit-testing/database-testing-rolling-back-transactions.html).

**Additional context**
We also have rollback functionality in SqlAlchemy ([docs](https://docs.sqlalchemy.org/en/14/orm/session_basics.html#session-rollback)).

**Comment by EPajares** [comment]
This one is quite important as we are polluting quite a lot the DB. I am not so sure if the rollback will work in our case as the data is already committed to the DB, I think when creating it using the functions from CRUDBase. 

But maybe this needs to be tested. I think in worst case we might have to record the IDs of inserted features and delete them after the test is finished but this might be a bit hard to manage in some cases.
