### ISSUE TITLE
Long loading time

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1472]
When opening GOAT in the browser, it usually takes quite long to load. 

## Expected Behavior
GOAT is ready to use when opening it. (Before the release 1.1 it was loading immediately)

## Current Behavior
This is how it looks like for the first ca. 20 seconds.
![grafik](https://user-images.githubusercontent.com/49870195/186504771-5cf488c2-e399-4fe3-8424-965cf79d38e4.png)

## Possible Solution
Don't know.

## Steps to Reproduce
1. Open link: https://goat.plan4better.de/ in Firefox.
2. No further steps.

**Comment by EPajares** [comment]
We have not changed the codebase yet. The service that does not load is the base map I assume from the pic. For me it loads fine but it can happen that the Mapbox services might be slow. I had something like this once.
