### ISSUE TITLE
Prepare environment for React

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1474]
# Goal of this issue
One moment in time we should migrate from Vue 2. So, we need material for making an informed decision on choosing either React.js or Vue.js

# Resources
Check existing codebase, read on the internet and talk to other projects.

# Deliverables
Report 2-3 pages that summarize pros and cons. You can also use Miro for this.

# Branch to derive

**Comment by cinaaaa** [comment]
@EPajares I think this is clear for us and can be in the done section.

**Comment by EPajares** [comment]
Yes we can close it thx
