### ISSUE TITLE
Icon & Colour change is not working in Deerfild Beach

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1478]
### Summary 📃

Some some reason, the changes on icon and icon colour are not saving.

### Expected Behaviour ✔

I am changing colour & icon. Thus, I am expecting that this also reflects in the map and the Thematic Data Filter.
![grafik](https://user-images.githubusercontent.com/49870195/186894546-21a6db3d-783c-446d-b5ea-c0517ea2609e.png)

### Current Behaviour 🔦

I click on "safe" but it is still showing the old icon & color.
![grafik](https://user-images.githubusercontent.com/49870195/186894678-3f12432c-f3a3-4d54-a574-0b04a36e28dc.png)

### Steps to reproduce 👣

1. Visit GOAT dearfield
2. Try to change icon & color

**Comment by EPajares** [comment]
Ok, I could reproduce this. The problem is at the moment only with custom categories. I need to check the API.
