### ISSUE TITLE
Improve icon categories

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1480]
### Summary 📃

The icon categories in the dropdown menu look a bit unstructured. Probably it's just because some are written in capital and some in lower case. 
What could probably also help is to move the icons from "custom(p4b)" in the according categories (e.g. the transport symbols into "Transportation"). In addition, the order could maybe be improved? For example, I would expect that "others" comes in the very and not between the letters E and F. 
![grafik](https://user-images.githubusercontent.com/49870195/186995533-22b4139e-4c4b-45e4-972e-e0e03bb4082a.png)

### Steps to reproduce 👣

1.
2.
3.
4.

**Comment by EPajares** [comment]
The main problem here is the missing translation. We can add it. 
We could put the icons from Plan4Better to transport, the problem is that we have to assign the category each time we define a new custom icon. As not all of them might belong to transport in the future. So we would lose flexibility.

**Comment by EPajares** [comment]
The translation was fixed we could consider adding the "others" category to the end.
