### ISSUE TITLE
Connectivity heatmap is not working for Deerfield Beach

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1482]
### Summary 📃

Connectivity heatmap is not working for Deerfield Beach. Not sure, if this is only an issue on my end. The other heatmaps are loading fine. 
![grafik](https://user-images.githubusercontent.com/49870195/187408942-395e1e7e-b5a2-40d3-a063-eb18d9bd2ed6.png)

### Expected Behaviour ✔

Connectivity heatmap shows up

### Current Behaviour 🔦

Connectivity heatmap doesn't show up

### Steps to reproduce 👣

1. Go to GOAT Deerfield Beach
2. Activate Connectivity Heatmap

**Comment by EPajares** [comment]
This was a data seeding mistake. I fixed it
