### ISSUE TITLE
Minute count not working? 

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1511]
### Summary 📃

I am just testing the new features and am not sure what the "0" is standing for. May it be that the minute count is not working correctly here? 
![grafik](https://user-images.githubusercontent.com/49870195/189761985-9a37d618-7ff3-42f7-a326-82c96d6dceb5.png)

### Expected Behaviour ✔

Actually, I am not sure what to expect. But the 0 looks wrong.

### Current Behaviour 🔦

0

### Possible Solution 💡

showing the minutes count for the isochrone

### Steps to reproduce 👣

1. GOAT Munich
2. Calculate a bus isochrone
3. Voilá

**Comment by EPajares** [comment]
This is duplicated #1493

**Comment by UJehle** [comment]
Okay, then you can close it
