### ISSUE TITLE
Add legend to Public Transport Frequency Layer

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1515]
**Is your feature request related to a problem? Please describe.**
This new layer is cool! I just have one issue.. I don't understand how to read it. 
![grafik](https://user-images.githubusercontent.com/49870195/189765414-8c512db9-b320-4f52-8f05-386f893b8f25.png)

**Describe the solution you'd like**
Maybe a legend with the different point sizes would be nice. 

**Describe alternatives you've considered**
And/Or using different colors for different point sizes to make them a bit better distinguishable?

**Comment by majkshkurti** [comment]
The legend can't render automatically in this case as the style is custom. A possible solution is to use a plugin from ol-ext which can render graphics from ol styles or to hardcode an image 
https://viglino.github.io/ol-ext/examples/legend/map.control.legend.html
