### ISSUE TITLE
"No title fetched"?

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1516]
### Summary 📃

Whenever I click somewhere on the map with the ÖV-Güteklassen open, it shows "No title fetched". I am not sure what this is supposed to show? 
![grafik](https://user-images.githubusercontent.com/49870195/189765889-853ce878-6645-4ace-81e1-a0ffc80320ff.png)

### Expected Behaviour ✔

Not showing this message.

### Current Behaviour 🔦

Showing the message.

### Possible Solution 💡

Remove it? 

### Steps to reproduce 👣

1. GOAT München
2. Activate ÖV-Güteklassen Layer
3. Click on the Map

**Comment by EPajares** [comment]
Duplicated #1503
I will remove the other one as this has more description
