### ISSUE TITLE
ÖV-Güteklassen: Why are the black areas not red? 

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1517]
### Summary 📃

This new indicator is pretty cool and gives a great overview! One thing that I don't understand: Why are the areas that seem to be outside of the coverage not having the red color? 
![grafik](https://user-images.githubusercontent.com/49870195/189766428-e6edae69-f420-4632-91b2-e763738e554b.png)

### Expected Behaviour ✔

The whole map is covered with some colour.

### Current Behaviour 🔦

Some wholes in it.

### Steps to reproduce 👣

1. GOAT München
2. ÖV-Güteklassen Layer
3.
4.

**Comment by EPajares** [comment]
This is not a bug but basically, the definition of the indicator:
![image](https://user-images.githubusercontent.com/42171996/190842421-7e20abfb-ec7e-4373-8b63-c66a4feab436.png)

Areas that are not covered have no ÖV Güteklasse. so basically, it is worse than the lowest class.
