### ISSUE TITLE
Station count and ÖV Güteklasse do not always reflect time picker

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1519]
# Goal of this issue
When testing the time picker I realized that sometimes it does not work.

# Resources

# Deliverables

# Branch to derive

**Comment by Ebubeker** [comment]
The station count seems to work fine for me and the results seem to be convincing. I mean sometimes choosing a time which has 45 minutes or 15 minutes causes a server error. I am failing to understand the bug here.
