### ISSUE TITLE
Add user_id and study_id area in user_study_area table on register

### ISSUE THREAD

**Issue by majkshkurti** [goat-community/goat#1543]
The user registration endpoint just adds the user only in the user table and doesn't populate the user_study_area table. This prevents the user from having more than one study area.

**Comment by EPajares** [comment]
At also does not population the table user_role

**Comment by metemaddar** [comment]
When we try to create user by /user/create, It adds the user to user_study_area. But the /user/demo doesn't do this.
It's so strange :thinking:

**Comment by metemaddar** [comment]
But both work with user_role table well.
