### ISSUE TITLE
Missing translation: Transport Modes

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1554]
### Summary 📃

![grafik](https://user-images.githubusercontent.com/49870195/191110374-d7c32b96-4f60-4e85-b53d-6015dc3fd49f.png)
This should be: 
ÖPNV
Auto

### Steps to reproduce 👣

1.
2.
3.
4.

**Comment by EPajares** [comment]
I fixed this already. Maybe the prod was not yet updated with this change.
