### ISSUE TITLE
Building entrances in the middle of the building - on purpose? 

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1563]
### Summary 📃

it is on purpose that the building entrances can be placed in the middle of the buildings? 
![grafik](https://user-images.githubusercontent.com/49870195/191518268-ace3936b-c01e-413f-9df4-c59f0a20afdb.png)

### Expected Behaviour ✔

Entrances can only be placed on the walls / building boudaries.

### Current Behaviour 🔦

Then can be places anywhere in the building.

### Steps to reproduce 👣

1. Scenario > building
2. Draw building
3. Place an entrance
4.

**Comment by EPajares** [comment]
I would label this as enhancement. It is not a bug.
