### ISSUE TITLE
Add docs for data upload file 

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1565]
# Goal of this issue
I believe we would have to update the data upload tutorial: https://plan4better.de/en/tutorials/data_upload/
Currently, we are showing how the file is created, but it would be good if we showed how to create such a file in QGIS and then, in the second step, how to upload it via GOAT.

So basically, we could create a sample file with some custom POI manually drawn using QGIS. Maybe we can create around 25 POIs somewhere in Munich. Ideally, a bit distributed. We could call the file _my-custom-pois_
The attributes we could just populated with some dummy values. 

I have a sample file for Deerfield
[grocers_sample.zip](https://github.com/goat-community/goat/files/9644311/grocers_sample.zip)

# Resources

# Deliverables
Add additional content for the tutorial on data upload.

# Branch to derive

**Comment by UJehle** [comment]
Let me add some sub-tasks here: 

- [ ] create draft (Dilan)
- [ ] feedback (Ulrike)
- [ ] revise & upload to Github / Forestry (Dilan)
- [ ] translation to German (Ulrike/Sophie)
- [ ] final check & release (Ulrike)
