### ISSUE TITLE
Improve printing

### ISSUE THREAD

**Issue by majkshkurti** [goat-community/goat#157]
The isochrone color should be visible in legend. We can add a static gradient color image from 1-20 minutes for now. 
The basemaps not shown at configuration scales. 
We can use mapproxy to cascade the basemaps images.
@majkshkurti

**Comment by EPajares** [comment]
We have to elaborate further on ways to improve performance. Mapproxy simply takes a lot of time. Also the imagery produced with Mapproxy is not that good. Probably we should test if we can restict printing to the resolutions Mapbox and Bing provide. We then don't have all zoom levels but printing should be much better.

**Comment by EPajares** [comment]
In fact Mapbox has many zoom levels: https://docs.mapbox.com/help/glossary/zoom-level/

**Comment by UJehle** [comment]
+ add isochrones to the print legend

**Comment by UJehle** [comment]
+ improve the print template

**Comment by EPajares** [comment]
I think this is mostly finished and a very generic issue. We probably should open new ones for specific improvements?
