### ISSUE TITLE
Make ÖV-Güteklassen und Station count more flexible

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1572]
# Goal of this issue
Currently, the user can only compute these indicators for one study area.

1. Allow superuser to compute ÖV Güteklassen and station count for more than one study area. If possible we make also this optional. I believe currently we are just using the active study area and the client does not pass anything. 
2. For ÖV Güteklasse add option to pass the hardcoded **station_config** dynamically. However, to avoid breaking changes, this should only be optional. The user should still be able to pass no configuration.

# Resources
### count_pt_service_stations()
https://github.com/goat-community/goat/blob/1fc0bdd8ce4c34412305ab8b0de94a770312f150/app/api/src/crud/crud_indicator.py#L629-L652

### compute_oev_gueteklassen()
https://github.com/goat-community/goat/blob/1fc0bdd8ce4c34412305ab8b0de94a770312f150/app/api/src/crud/crud_indicator.py#L654-L778

# Deliverables
Add options to endpoints.

# Branch to derive
Dev

Branch to push feature/oev-guetklasse-flexible

**Comment by metemaddar** [comment]
This should affect the following endpoints:

https://github.com/goat-community/goat/blob/1fc0bdd8ce4c34412305ab8b0de94a770312f150/app/api/src/endpoints/v1/indicators.py#L184-L240


https://github.com/goat-community/goat/blob/1fc0bdd8ce4c34412305ab8b0de94a770312f150/app/api/src/endpoints/v1/indicators.py#L241-L299



And for the first one, if I get it well, we need to get study_area_id as a list, so, if we get study_area_id as a list, then it should be return calculation as a list as well.
Of course I think it would be good to always return as a single type (list) and not to sometimes send as an object and sometimes send as a list. @majkshkurti, Which one is better? is it okay to always pass the result as a list?

**Comment by metemaddar** [comment]
@majkshkurti
for refactoring `calculate_oev_gueteklassen` we need to pass a json to the endpoint. Is it better to also refactor it as post or otherwise we may need to encode station_config to base64.

**Comment by majkshkurti** [comment]
@metemaddar That will break the client implementation as we use a get request for all indicators. 
However, I think we can change it, so no problem. I will not suggest using base64. It will make this API practically unusable outside GOAT.
