### ISSUE TITLE
[BUG]  Lack of change of Transparency of Pedestrians and Cyclists

### ISSUE THREAD

**Issue by iremkapucuoglu** [goat-community/goat#1573]
There is an option to change transparency for pedestrians and cyclists data in the Additional data section, but there is no change in the map when you change the transparency.

When the transparency is high
![transparanlık ful](https://user-images.githubusercontent.com/73173737/191757784-a04d9d60-a90c-4a31-b227-189db38a2796.png)

When the transparency is low
![transparanlık en az](https://user-images.githubusercontent.com/73173737/191757852-eb4661d5-6212-4d8b-b8b8-5b6b1c33ccaa.png)

**Comment by Ebubeker** [comment]
I investigated this error a bit further, I think there is no solution about it. The only one might be changing the type of the layer.
Here is what chatgpt said:

By default, the VectorTileLayer in OpenLayers does not support changing its opacity. This is not an error, but rather a design decision made by the OpenLayers development team.
However, it is possible to change the opacity of a VectorTileLayer by applying a CSS rule to the layer's DOM element. For example, you could use the following CSS rule to set the opacity of a VectorTileLayer to 50%:

`.ol-layer .ol-layer-vector {
  opacity: 0.5;
}
`
You can add this CSS rule to your application's stylesheet or add it dynamically using JavaScript.

Note that changing the opacity of a VectorTileLayer using CSS may have performance implications, particularly if the layer contains a large number of features. It is recommended to test the performance impact of any CSS changes before deploying them to a production environment.
