### ISSUE TITLE
Add one distinct color per isochrone?

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1575]
# Goal of this issue
We discussed in the last dev meeting that it could get confusing that the isochrones are changing their colors when we flip through them. I believe it could be worth investigating if we could simply define a new color per isochrone. So we would have to pre-select, let's say, 20 colors. These will then be used, and e.g., the Isochrone 1, Isochrone 2, Isochrone 3.... will always keep their colors.

What do you think? @UJehle @majkshkurti @Ebubeker @iremkapucuoglu @Philipp-Otter 

# Resources

# Deliverables

# Branch to derive

**Comment by UJehle** [comment]
I think it would be nice to have the option to choose the isochrone colour, as this was also one feature that many users liked when we implemented it the first time. It also helps to style the maps nicely as, depending on the background map and the activated layers, the black/grey isochrones are sometimes hard to see.

**Comment by Philipp-Otter** [comment]
@UJehle I think, they are already working on it #1576.

**Comment by iremkapucuoglu** [comment]
I think it would be nice to have different colors for each isochrone to improve the understadability and visuality of the analysis. Also, if we will be able to enable more than 2 isochrones at the same time, color option would also improve the quality.
