### ISSUE TITLE
New tutorial video for public transport analyses

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1578]
# Goal of this issue
As briefly discussed, it would be great to have a video on public transport analyses. This might not be easy to do as we don't have an existing video yet. The video should contain the following information:

- Public transport station count
- ÖV Güteklassen
- Public transport isochrone

@iremkapucuoglu, we can coordinate what will be the exact content of the video. 

# Resources

# Deliverables

# Branch to derive

**Comment by UJehle** [comment]
Hi @iremkapucuoglu! 
I am not sure if you already started with this issue, but I would suggest roughly the following script. Maybe this helps you.
1. open GOAT Munich
2. switch on Public transport background map
3. Activate "ÖV Güteklassen" and look at it for different days (e.g. Tuesday vs. Saturday) and different times of the day (e.g. morning vs. afternoon)
4. Switch on the average count of departures and click on some of the pie charts to get the details. (I think the best would be to pick one point with very high and one with very low count and then use the same two points for the next step >> isochrones)
5. Calculate public transport isochrones for the 2 points you show before and highlight the differences in accessibility

**Comment by UJehle** [comment]
In addition, let me add some subtasks:

**Create Video (EN)**
- [ ] create video - Irem
- [ ] create subtitles - Irem
- [ ] check - Ulrike
- [ ] upload to vimeo - Irem
- [ ] bring to website - Ulrike

**Create Video (DE)**
- [ ] create video (DE) - Irem
- [ ] create subtitles (DE) - Sophie 
- [ ] check - Ulrike
- [ ] upload to vimeo - Sophie
- [ ] add to website - Ulrike
