### ISSUE TITLE
Add planning question on public transport to the "isochrone" tutorials

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1580]
# Goal of this issue
In the tutorials, currently, a section on the new public transport analysis is missing. 
https://plan4better.de/tutorials/isochrone/

Add a step-by-step description + screenshots on the planning question "How many people can access a specific location within 20min by rail-based public transport (tram, underground, train)?"

The result would roughly look like this: 
![grafik](https://user-images.githubusercontent.com/49870195/192230926-ce2b33a0-1c98-447c-9611-3c53160300d2.png)
 
Subtasks:
- [x] create English draft (Dilan)
- [x] feedback (Ulrike)
- [x] final English (Dilan)
- [x] translation to German (Ulrike)
- [ ] inserting German screenshots (Dilan)
- [ ] final check & release (Ulrike)

**Comment by UJehle** [comment]
Hi @dilaann, thanks for the PR with the edits! I accepted it and made the German translation for the new planning question.

**Comment by dilaann** [comment]
Hey, all. When I check the website, the images and text are ready in English and German. So I'm closing this issue.
