### ISSUE TITLE
Update tile images for video page on plan4better website

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1582]
# Goal of this issue
On the video section of our Plan4better website, a kind of "preview" picture is shown for each video. 
![grafik](https://user-images.githubusercontent.com/49870195/192639392-361e6015-8542-487d-b709-6c854b40950c.png)
These pictures are not fetched automatically from Vimeo but need to be uploaded separately to the website. 
@iremkapucuoglu could you assist me here and create a representative screenshot for all 9 videos? Here, we don't need to differentiate between English and German, as it's too small to read anyhow.

- [x] 1. Walking isochrones 
- [x] 2. Scenario Ways
- [x] 3. Local Accessibility Heatmap
- [x] 4. Multi Isochrones 
- [x] 5. Scenario POIs 
- [x] 6. Comparison Population Density Accessibility
- [x] 7. Scenario buildings 
- [x] 8. Spatial data 
- [x] 9. Individualized maps 

You can save the created screenshots in the corresponding subfolders in the "videos" folder: https://plan4better-my.sharepoint.com/:f:/r/personal/elias_pajares_plan4better_de/Documents/Plan4Better%20-%20Server/Marketing/Website/Videos?csf=1&web=1&e=b0yBA4

Thanks!

**Comment by EPajares** [comment]
@UJehle can we close this?

**Comment by UJehle** [comment]
Some small things are still open. I will close it when they are finished.

**Comment by UJehle** [comment]
Thank you @iremkapucuoglu ! I just uploaded the last images.
