### ISSUE TITLE
Function recreating script does not drop functions from schema basic

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1589]
# Goal of this issue
Our script that we are using for managing the functions does not work properly as it does not clean the schema "basic" from all functions.

# Resources

# Deliverables

# Branch to derive

**Comment by EPajares** [comment]
I tested this once more and it does not work. Please drop all functions in the schema first and then recreate the functions

**Comment by metemaddar** [comment]
According to IsochroneMultiCountPois which is needed to check the POI count:
https://github.com/goat-community/goat/blob/fe6d6e2625f99624d6973593786df7997768f419/app/api/src/schemas/isochrone.py#L19-L28

We can extract data from IsochroneDTO and request as following:

| IsochroneMultiCountPois 	| IsochroneDTO                   	|
|------------------------:	|--------------------------------	|
|                 user_id 	| **from request**                   	|
|             scenario_id 	| `dto.scenario.id `               	|
|               amenities 	| `dto.starting_point.input`       	|
|                 minutes 	| `dto.settings.travel_time`       	|
|                   modus 	| `dto.scenario.modus`             	|
|                  region 	| `dto.starting_point.region`      	|
|             region_type 	| `dto.starting_point.region_type` 	|
|                   speed 	| `dto.settings.speed`             	|
|       active_upload_ids 	| `user.active_data_upload_ids`    	|

Is this right? And as active_udata_upload_ids can be determined by user_id, we might remove the `active_upload_ids` from the schema and fetch it from database.
@majkshkurti
