### ISSUE TITLE
Develop method to assess POI data quality

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1593]
# Goal of this issue
We need a method to assess the quality of our existing POI database and new poi data sets. Initially, this method might be a manual validation of the data, but it should follow an organized workflow. First, we should read about best practices in literature and then assess how we can apply one or a combination of methods to our use case.

# Resources
Check some literature. Ask experts from IÖR.

# Deliverables
A new section in the wiki that clearly describes the workflow and can be reproduced by different people.

# Branch to derive

**Comment by iremkapucuoglu** [comment]
I found an article which can be useful 
https://mdpi-res.com/d_attachment/ijgi/ijgi-10-00735/article_deploy/ijgi-10-00735.pdf

**Comment by dilaann** [comment]
Here is another:
[Assessing_Crowdsourced_POI_Quality_Combi.pdf](https://github.com/goat-community/goat/files/9744840/Assessing_Crowdsourced_POI_Quality_Combi.pdf)
