### ISSUE TITLE
Process LOD 2 buildings

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1598]
# Goal of this issue
Data from CityGML models is a precious resource of information. At the moment, particularly for our building data sets.
Our building data currently comes from a different source but a common challenge is to get more attributes on the buildings, such as building levels and building type. We do have building processing using data from OSM here: 
https://github.com/goat-community/data_preparation/tree/main/src/population
I will refactor this part soon. But the process could be significantly improved if include data from LOD 2 buildings.

**So the task would be to read the building that we have imported into CityDB and converting the LOD buildings into the target schema (see below). For this we could have to use a combination of SQL queries that we might execute by looping in Python.**

I would create a new class here called CityGMLBuilding: 
https://github.com/goat-community/data_preparation/tree/main/src/collection

This class can go into a new file.

# Resources

We have a couple of classes for connecting and reading data from the databases here: https://github.com/goat-community/data_preparation/tree/main/src/db

This is the model for the target building table:
```sql
CREATE TABLE basic.building (
	id serial4 NOT NULL,
	amenity text NULL,
	residential_status text NULL,
	housenumber text NULL,
	street text NULL,
	building_levels int2 NULL,
	building_levels_residential int2 NULL,
	roof_levels int2 NULL,
	height float8 NULL,
	geom public.geometry(polygon, 4326) NOT NULL,
	area int4 NULL,
	gross_floor_area_residential int4 NULL,
	osm_id int4 NULL,
	building_type text NULL,
	CONSTRAINT building_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_building_geom ON basic.building USING gist (geom);

```

# Deliverables
Process the CityGML data for Germany and save the table inside Geonode. 

# Branch to derive
Dev

**Comment by EPajares** [comment]
I added the query here: #1602

Now we have to execute the query in a loop through a spatial subdivision of the study area (e.g. the testing area Hamburg). We could use an existing function that receives an input geometry and the area size in km². This function will produce the subdivision that can be used for the looping in the next step. This function can be found here:

https://github.com/goat-community/data_preparation/blob/main/src/db/functions/create_equal_area_split_polygon.sql

**Comment by EPajares** [comment]
Importing large files (+2GM) into the database is very slow. We need another strategy.
Each zip file consists of several files, as can be seen here:

![image](https://user-images.githubusercontent.com/42171996/206676850-196be1f8-9e04-421b-938b-a1e5e037eec9.png)

So we could import the files in bulks. The functions should do the following:

1. Unzip large file
2. Receive a list files that are now processed
3. Create a new zip based on the list of files
4. Create database container
5. Import this zip into the database 

After the 5. we will run our data processing script that will perform for the buildings that were imported in this batch.

**Comment by metemaddar** [comment]
As you create the list of files inside the container and the db import process is outside of the container, we need a bridge between host and the container. So you can do the following and I‌ write a script to do import for each file_list:
Put the files to a directory named `bridge`.
![Untitled](https://user-images.githubusercontent.com/3726265/206682119-fd37e31b-e69a-41b9-a7de-3c0311ddf7bb.jpg)
