### ISSUE TITLE
Document 15 Minute Score Progress

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1610]
Research and first trials in the projects Vienna and acatech need to be documented, so a new issue for the implementation can be opened in the future. 

- [x] clean acatech code 
- [x] create section in miro board (Heatmap Ideas) and link important code snippets like the config

**Comment by Philipp-Otter** [comment]
paused till new heatmap logic is released
- [ ] research weather we should apply standardization or quantile normalization on the local accessibility indices/ the sub-scores before aggregating them

**Comment by Philipp-Otter** [comment]
Research and first trials in the projects Vienna and acatech need to be documented, so a new issue for the implementation can be opened in the future. 

- [ ] clean acatech code 
- [ ] create section in miro board (Heatmap Ideas) and link important code snippets like the config
