### ISSUE TITLE
Update "Technical Architecture"

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1613]
# Goal of this issue
https://plan4better.de/en/docs/technicalarchitecture/
I am not sure if everything is still up-to-date here. It would be good to check the content with the dev-team (I thought maybe @metemaddar could help here?). 

# Deliverables
Up-to-date "technical architecture" section on our website.

# Branch to derive
p4b-website >> development branch.

Thank you!!

**Comment by metemaddar** [comment]
My pleasure!
