### ISSUE TITLE
Tool Interface Overview

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1614]
# Goal of this issue
The goal would be to create a brief explanation of how is the user interface structured (Where to find which buttons? Etc. )
--> Have a look how other companies / softwares do this.

We could add it here: 
![grafik](https://user-images.githubusercontent.com/49870195/196014524-ae483552-7672-4e4c-b2e5-5571024a3481.png)
Though, I am not sure yet how to call this section. Maybe you have some good ideas? 

Probably you could do this together with our new team member Ana. I am sure she can be of great help for explaining the interface structure.

# Deliverables

- [x] create a draft - English (Dilan & Ana)
- [x] feedback (UJ)
- [x] final English (Dilan & Ana) 
- [x] insert German screenshots (Dilan)
- [x] translation into German (Ulrike)
- [x] release (Ulrike)

# Branch to derive
p4b-website > development branch.

**Comment by AnaSasso** [comment]
Table of clickable areas:
Icon/Button , Label , Usage
Spreadsheet: https://plan4better-my.sharepoint.com/:x:/g/personal/ana_sasso_plan4better_de/EXE-5YlanFpIoeC8tMtB8YUBmIgMvMIYyRJeTSHh_Uo6RQ?e=y533Wm

reference:
https://docs.qgis.org/3.22/en/docs/user_manual/introduction/general_tools.html#zooming-and-panning:~:text=the%20Layers%20panel.-,Icon,-Label

Interface overview:
Screenshot of the goat screen state.0 with arrows and labels 
reference:
https://docs.oracle.com/cd/E35328_01/E35332/html/vmusg-ui-overview.html

**Comment by UJehle** [comment]
Thanks @AnaSasso for starting with this! This already goes in the right direction. Let me know if you need some input from my side.

**Comment by AnaSasso** [comment]
Hi guys, so I circle back to this issue, and I know it was my own idea to use an excel spreadsheet, but it turns out it isn't the best choice. So I suggest we use Figma for all of it: https://www.figma.com/file/Sn7RXFg7L2aM71L6qzJO4v/Handoffs?node-id=58%3A198
Here I created a first draft of what would look like a table with tools explanation. 
![image](https://user-images.githubusercontent.com/116002158/201758242-a3ee6ca5-3837-4347-a3e1-c43e76353955.png)

**Comment by UJehle** [comment]
Hi @AnaSasso, I agree. A visual tool such as Figma, Miro or PowerPoint may be better suited. The draft looks cool! For the website, we would need to embed the table but it should still look good.

**Comment by dilaann** [comment]
Hi @AnaSasso , I also agree that working on Figma seems more functional. Do we also make the table with clickable buttons as well or just a label/usage table? 

About the embed the table, @UJehle  maybe we can add docs section or tutorials section. Or maybe it can be added somewhere else as a new section under GOAT as **Discover Goat > Tutorials,Docs,Videos,User Interface Overview**

![image](https://user-images.githubusercontent.com/80716601/201969470-40b32c2f-c71e-4fc5-a586-2f10d8c175c8.png)

![image](https://user-images.githubusercontent.com/80716601/201971325-f886a1c2-d4ee-4804-8d76-170716840a15.png)

**Comment by UJehle** [comment]
Hi @dilaann, I think allocating it as the fist page in the tutorial section may be the best, as it gives a great first overview.

**Comment by EPajares** [comment]
Yes we should add the overview as an image but the table as a markdown.

**Comment by UJehle** [comment]
Hi @dilaann & @AnaSasso! Thanks for the nice table! I think it looks pretty good. I only did not find it that easy to understand which of the elements are tabs, and which are menu actions, icons or toolbars. What do you think about the idea to show a screenshot above the table to name the different element groups? 
![interface_overview](https://user-images.githubusercontent.com/49870195/214102263-d6e35bf6-86a8-4e12-bf74-91442b23f6bd.png)

Not sure if it makes sense to already create this for the current GOAT version or if we wait until the new interface.

**Comment by UJehle** [comment]
@dilaann I created the German page. I still need to translate the table, but you can already insert the images.

**Comment by UJehle** [comment]
This issue is done! I will publish it with the next release. Thanks for the good teamwork <3
