### ISSUE TITLE
Landuse layers not loading for Munich

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1615]
### Summary 📃

In the GOAT Munich version, both land use layers are not loading.

### Expected Behaviour ✔

I expect the land use layers to appear. 

### Current Behaviour 🔦

They don't appear.

### Possible Solution 💡

Not sure if either the data is missing or if something else is wrong.

### Steps to reproduce 👣

1. Go to GOAT Munich
2. Switch on Land use layer

**Comment by EPajares** [comment]
This is duplicated. We have to fix this. https://github.com/goat-community/goat/issues/1383
