### ISSUE TITLE
Public transport frequencies not loading for Munich

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1616]
### Summary 📃

Sometimes, the public transport frequencies for Munich are not loading. To be honest, I don't know what the issue is because sometimes it works. But this is the error that it shows to me: 
![grafik](https://user-images.githubusercontent.com/49870195/196034240-8f90821d-c91c-42f6-b18d-4aef52f799c6.png)

### Steps to reproduce 👣

1. Open GOAT Munich
2. Activate public transport frequencies
3. Wait whats happening ...

**Comment by EPajares** [comment]
Does it work when you just try to activate the layer again? Or does it still not work? Is the time window the one shown in the image?

**Comment by UJehle** [comment]
No. Either it works when I open the application (also, when activating, deactivating and activating again) or it doesn't work at all (no matter how often I activate and deactivate it; I tested it for several time windows. None of them worked).
