### ISSUE TITLE
Allow to assign all roles to user in dashboard

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1617]
Currently, when creating a new user via the dashboard, only the user role can be assigned. 

![Image](https://user-images.githubusercontent.com/42171996/196038963-fd71f7b1-dabf-4cd3-bf09-dbcad562cfb7.png)

Though it would be good also to be able to assign all roles via the dashboard. There is an endpoint in the "Roles" that returns all roles so these values could be used to populate the dropdown menu.

**Comment by cinaaaa** [comment]
@EPajares  Please consider that we still don't have the `roles` on the response of users' GET.
So editing users is buggy!
![Screen Shot 2022-10-17 at 14 48 06](https://user-images.githubusercontent.com/42252572/196164097-80525131-47ac-4542-8688-d4d8c95ad4ca.png)
![Screen Shot 2022-10-17 at 14 49 29](https://user-images.githubusercontent.com/42252572/196164269-47608520-04eb-4673-a5e1-ddb382451a5e.png)

**Comment by cinaaaa** [comment]
Also, I'm getting 500 on sending PUT to edit a user.

```
curl 'http://localhost:3000/api/users/146' \
  -X 'PUT' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  -H 'Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjY2OTY1MTYsInN1YiI6IjE0MiIsInNjb3BlcyI6W119.KgaqySnwaMUEgMQmwajUgoVtka1IeMO3ttBtaJ4j83M' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Origin: http://localhost:3000' \
  -H 'Pragma: no-cache' \
  -H 'Referer: http://localhost:3000/users/146' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Chromium";v="106", "Google Chrome";v="106", "Not;A=Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --data-raw '{"id":146,"is_active":true,"newsletter":true,"occupation":"jkokkoko","domain":"mmkmk","creation_date":"2022-10-17T11:21:08.084997","name":"sina","surname":"farhadi","email":"sdokmsdmdslmdsl@mail.com","organization_id":4,"active_study_area_id":91620000,"active_data_upload_ids":[],"storage":512000,"limit_scenarios":50,"language_preference":"de","password":""}' \
  --compressed
```

**Comment by EPajares** [comment]
Thanks Sina for reporting this! @metemaddar could you check this one

**Comment by cinaaaa** [comment]
@EPajares  BTW, It has been done and you can check it at Staging env in minutes
