### ISSUE TITLE
Add "Study Area" selection to dasboard for user

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1618]
The endpoint for creating and updating users allows to add several study_areas and specifies the active_study_area_id.

![Image](https://user-images.githubusercontent.com/42171996/196039066-91b3f6c6-f3b9-4e59-9e52-5a489db076bd.png)

Currently, in the dashboard, we are only allowing to add the active study area id and not the study area list. So it would be good to also allow the selection of the study areas.

![Image](https://user-images.githubusercontent.com/42171996/196039230-9e1a5a6e-f016-4a51-8864-a56ac6da6752.png)

**Comment by cinaaaa** [comment]
@EPajares Does this API accepts the `study_areas` as a parameter? It's accepted, but in the response, no `study_areas` is represented in the result.

**Comment by EPajares** [comment]
Sorry just seeing this now. @metemaddar could you please check to also return the study areas?
