### ISSUE TITLE
Add tutorial on how to use the "External layers" 

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1625]
# Goal of this issue
The option of adding the external layers is great! 
The planners in Ghent liked this a lot. However, they had issues understanding how exactly it works. 
I think it would be good to have a brief [tutorial](https://plan4better.de/en/tutorials/isochrone/) on this (title "Add external layers"). 

# Resources
The primary resources here are people ;) 
@dilaann & @Ebubeker could you create such a tutorial together? With @Ebubeker providing the content and @dilaann bringing it into the right structure for our website.

# Deliverables

- [x] provide an explanation on how this feature works (Ebubeker)
- [x] create a tutorial draft - English (Dilan)
- [x] feedback (UJ)
- [x] final English (Dilan & Ebubeker) 
- [x] translation into German (Ulrike)
- [x] insert German screenshots (Dilan)
- [x] release (Ulrike)

# Branch to derive
p4b-website > development branch.

**Comment by dilaann** [comment]
The screenshots are done. I´ve added as a new section in [Graphics.pptx ](https://plan4better-my.sharepoint.com/:p:/g/personal/elias_pajares_plan4better_de/EYAO54v4r7ZBoUsBEVxbkYQB3Gh-8YKr5W10k7DNomUADw?e=qEEgHk) called External Layer(pages between 113-130 ) 

@UJehle You can check the screenshots and let me know if there are places to revise.

**Comment by UJehle** [comment]
Hi @dilaann! Thanks. I just checked the screenshots. They look good.

**Comment by UJehle** [comment]
Hi Dilan, thanks for the PR, t looks good! I merged it and made some minor adjustments. Thanks also for already uploading the German screenshots. I translated the document and linked the German screenshots. Therewith, this task is done.
