### ISSUE TITLE
Fix bug with documentation iframe

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1626]
The documentation IFRAME does not fully load the content as can be seen in the screenshot. There is a known bug discussed with @majkshkurti before.

![image](https://user-images.githubusercontent.com/42171996/196378485-b044f9aa-8374-4316-ad20-1c40382b41f3.png)

@Ebubeker maybe you could investigate it. 

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Ebubeker** [comment]
Yeah I will have a look at it.

**Comment by Ebubeker** [comment]
I am having some problems, The icon to show the documentation does not show up.

**Comment by EPajares** [comment]
fixed it for one layer of connetivity. Need to add more to the other layers.

**Comment by Ebubeker** [comment]
There is also this way to fix it, but it loads the navbar and the footer, This is the only problem.
![start](https://user-images.githubusercontent.com/60944813/196465605-562c57f8-5471-4b8a-b176-58848b9dfd4b.png)
![ende](https://user-images.githubusercontent.com/60944813/196465599-e92a505f-fe76-4a61-8b7c-b522ae920443.png)
