### ISSUE TITLE
Dynamically (de)compressing rows of DB

### ISSUE THREAD

**Issue by metemaddar** [goat-community/goat#1627]
As reported, the database rows for calculations of heat-maps get large as millions of rows. We need a tool and approach to (de)compress them and avoid taking much space.

As @EPajares followed, there are some options to compress the database rows [as documented at medium](https://medium.com/@lk.snatch/postgresql-compression-854a4647ee43).

We need to choose the right way that fits our job.

**Comment by metemaddar** [comment]
As we talked we can store the data to a binary type column. Because the data itself ins/outs in binary format. But the next step would be compressing this binary data.
It's obvious that we need a [loss-less](https://en.wikipedia.org/wiki/Data_compression#Lossless) compression method. However we can also use loosely compression. But it's not the case here.
Our binary itself uses some types of compression by using the diff method.
I assume that the diff doesn't reduce size of all data. But it produces lots of 0s. By knowing this, we would test/choose compression algorithms.

**Comment by metemaddar** [comment]
A test over sample response.bin file which is 2.9M, with some algorithms is as follows:

| Compression type | Result size | Compression | Compress time (ms) | Decompress time (ms) |
|:----------------:|:-----------:|:-----------:|:------------------:|:--------------------:|
|        tgz       |    421 KB   |     86%     |         156        |          15          |
|        zip       |    421 KB   |     86%     |         134        |          18          |
|        bz2       |    265 KB   |     91%     |         99         |          66          |
|        gz        |    421 KB   |     86%     |         126        |          13          |
|        xz        |    183 KB   |     94%     |        1106        |          18          |
|        7z        |    208 KB   |     93%     |         663        |          16          |

**Comment by EPajares** [comment]
This is an exciting result. I believe we maybe should test it inside the database now. Maybe we can just create some dummy data using python and add it inside a dummy table?

**Comment by EPajares** [comment]
We could consider creating a table with 1mio rows using this structure:

```
python
class TravelTimeMatrixBase(SQLModel):
    id: Optional[int] = Field(sa_column=Column(Integer, primary_key=True, autoincrement=True))
    grid_calculation_id: int = Field(
        sa_column=Column(
            BigInteger,
            ForeignKey("basic.grid_calculation.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        )
    )
    northwest: Optional[List(float)] = Field(sa_column=Column(Float), nullable=False)
    heigth: Optional[int] = Field(sa_column=Column(Integer), nullable=False)
    width: Optional[int] = Field(sa_column=Column(Integer), nullable=False)
    costs: Optional[List(Integer)] = Field(sa_column=Column(SmallInteger), nullable=False)

```
