### ISSUE TITLE
Cannot change the color when clicking the arrows

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1631]
Actually, when I click the arrows of the RGB color picker, the color does not change. @Ebubeker maybe you can check.

![image](https://user-images.githubusercontent.com/42171996/196811956-fdafd651-def7-4dc4-aa2f-ab1cdb21b177.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Ebubeker** [comment]
Ok because I will have a look at it. I think this might be because the values are not defined as default_values (which allows us to change them) but rather as values (if it is like this usually you cannot change it)
