### ISSUE TITLE
Fix relation for TravelTimeMatrixWalking

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1636]
# Goal of this issue
For the new table (TravelTimeMatrixWalking) I am having difficulties creating the foreign key relationship with the GridCalculation. It was created in the DB as it should be, but there were problems loading it in Python. Sp currently the relation is uncommented.

@metemaddar could you investigate this?

# Resources

# Deliverables

# Branch to derive
DEV

**Comment by metemaddar** [comment]
Things to check:

- [ ] The foreign key is at the right side
- [ ] The name has no conflicts with other data and columns
- [ ] Table name of foreign key is defined correctly
- [ ] Test with other relationship

**Comment by metemaddar** [comment]
@EPajares 
I changed the foreign key definition by using only Filed key and it works now.
But we need to update the sqlmodel to get the unique property at foreign key definition.

**Comment by metemaddar** [comment]
I think the new version of sqlmodel can fix some bugs like #1643 serializing relations. But may put some changes to alembic as well. Because it automatically detects fields that can not get null.

**Comment by EPajares** [comment]
Thanks @metemaddar I understand.
