### ISSUE TITLE
Change status of application via dashboard

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1639]
# Goal of this issue
We do have a table that manages the status of the application.

![image](https://user-images.githubusercontent.com/42171996/197388339-620477f5-621a-4a19-9c03-e4f21938bddd.png)

And we have an endpoint that checks whether the service is available:
![image](https://user-images.githubusercontent.com/42171996/197388383-d96d405e-4630-49aa-bef3-5c30a47f0caa.png)

But we don't have an endpoint that changes the status. So we would need a post request that sends/receives the following:
```
{ 
 "status": "maintenance"
}
```
or 
```
{ 
 "status": "running"
}
```

Using a Fake API we could implement this in the dashboard. Maybe we can have a checkbox for this somewhere on the left side:

![image](https://user-images.githubusercontent.com/42171996/197388592-fb87cd22-9691-4dc9-b5ab-e99b17bc8db6.png)

Ideally, when changing the checkbox, we send a message that forces the user to confirm it. Similar to what we do for the user deleting. 

# Resources
Check client implementation using a Fake-API. Later the backend implementation will follow.

# Deliverables

# Branch to derive
Dev

**Comment by cinaaaa** [comment]
![Screenshot 2022-11-01 at 11 17 28](https://user-images.githubusercontent.com/42252572/199191796-dd95fed3-5728-40bc-aafe-dc74c672f696.png)
![Screenshot 2022-11-01 at 11 19 22](https://user-images.githubusercontent.com/42252572/199191800-f3464f27-25a6-4332-ae3f-bc891a39bcc0.png)
![Screenshot 2022-11-01 at 11 28 44](https://user-images.githubusercontent.com/42252572/199191804-d2e9d62d-59e2-4332-bb21-833753794b71.png)

GET /api/status -> `"running" or "maintenance"`
PUT /api/status -> `{status: "running" or "maintenance"}`

**Comment by EPajares** [comment]
Thank you! @metemaddar could you implement the endpoints in the API? Important is that the PUT endpoint is for superusers only.
