### ISSUE TITLE
Missing Translations

### ISSUE THREAD

**Issue by iremkapucuoglu** [goat-community/goat#1669]
- In German version, the description in the pop up window is in English.

![missing_translation](https://user-images.githubusercontent.com/73173737/198959624-a12eeabc-86c5-456e-bc5a-d985560c6136.png)

- In the German version of GOAT the pop up window when deleting a scenario is only partially translated. "Alle löschen" is also not correct German -> maybe use "Szenario löschen".

![image](https://user-images.githubusercontent.com/91256148/196777888-152e3d6a-57f7-4da5-9960-35601fddf995.png)

- In English version, the school names are in German

![missing_translation_3](https://user-images.githubusercontent.com/73173737/198960211-6fefca4f-83fa-4f84-8bfd-32ca574a02e8.png)

- In English version, some of the other layers names are in German

![missing_translation_2](https://user-images.githubusercontent.com/73173737/198960339-a1814e5f-323c-4b37-b3e9-9c2adf3a0c85.png)

**Comment by EPajares** [comment]
Thank you very much for reporting! I added the translations where possible. But for the layers and POIs I have not added them. As these terms are very specific for Germany and thus hard to translate. I preferred keeping them in German as they are only relevant for German deployments.
