### ISSUE TITLE
Extend docs connectivity heatmap

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1692]
# Goal of this issue
Update description of connectivity heatmap. The description is very short. Maybe we can add some more words here.

# Resources

# Deliverables

# Branch to derive

**Comment by dilaann** [comment]
Hey, I believe this doc needs to be extended. -->  [Heatmap - Connectivity](https://plan4better.de/en/docs/heatmap-connectivity/)

So, I prepared[ this draft,](https://plan4better-my.sharepoint.com/:w:/g/personal/elias_pajares_plan4better_de/ERdApM7GU1hKs5ZmGAY-HtwBlaDWAbr8RA_EtzNOnZqxOg?e=I3vJXY) it would be nice to have an explanation part of how the calculation works. Also, I created a new folder under tutorials to organize drafts for documentation [here. ](https://plan4better-my.sharepoint.com/:f:/g/personal/elias_pajares_plan4better_de/EqHDa6Y65DVEkpMLPEpi494BbPwczTT5FVkPn_IH34IOmA?e=fxPXGc). 
You can check the draft and add some comments to update.

Thanks!
