### ISSUE TITLE
POI icons are having an offset when zooming out

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1693]
### Summary 📃

I like that the POI icons now still appear when zooming out and adjust their size! How is their position calculated? 
Currenty, the icons appear with an offset between the actual location and the marker. 
![grafik](https://user-images.githubusercontent.com/49870195/200480752-76601bd0-ae3d-4986-9aed-aa4b0f5965fd.png)

### Expected Behaviour ✔

Markers point on the exact locations

### Current Behaviour 🔦

Markers don't point on the exact locations

### Possible Solution 💡

Adjust the offset? 

### Steps to reproduce 👣

1. open GOAT
2. activate POIs
3. zoom out
4. activate background map as a reference to see the "real" locations

**Comment by Ebubeker** [comment]
I am failing to recreate the error. Maybe it is because we added the new feature of min_zoom and max_zoom to the POIs.
