### ISSUE TITLE
Add Isochrone Color Style Feature to Tutorials&Videos

### ISSUE THREAD

**Issue by dilaann** [goat-community/goat#1716]
# Goal of this issue

This isochrone color picker feature needs to be added to written tutorials and videos. 
Right now we don't see this in website tutorials. It would be nice to update when it's complete.

![image](https://user-images.githubusercontent.com/80716601/202854194-3898d6a7-f5f7-4d85-bf76-8ef954839893.png)

**Comment by iremkapucuoglu** [comment]
I created a video about styling options in GOAT. You can see from [here ](https://plan4better-my.sharepoint.com/:v:/g/personal/elias_pajares_plan4better_de/Ec4N2IDVcjBGiZpvd-Xde1EBFjEf82ZXF3HXQrMAnj74Zg?e=J7VdSv)
I will add subtitle after feedbacks for the video

**Comment by EPajares** [comment]
Still needs to be uploaded to vimeo
