### ISSUE TITLE
A brief explanation for users for Multi-Isochrone vs Single Isochrone

### ISSUE THREAD

**Issue by dilaann** [goat-community/goat#1717]
# Goal of this issue

Define the multi-isochrone and single isochrones and explain their differences in the tutorials section( why do we need them separately? what are they for? etc)

![image](https://user-images.githubusercontent.com/80716601/202854648-857b221e-e565-4118-9e74-38b735531377.png)

**Comment by UJehle** [comment]
Hi @dilaann :) that's a good point! We can maybe add a short explanation of the difference here: 
![grafik](https://user-images.githubusercontent.com/49870195/203227897-ba468091-2f7f-409b-9f4f-58fbc181e620.png)
And same in the "isochrone" tutorial.

**Comment by UJehle** [comment]
It may make sense to address this issue together with: https://github.com/goat-community/goat/issues/888.
