### ISSUE TITLE
Finish new heatmap schema

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1786]
# Goal of this issue

For each calculation types for heat-maps (#1783), we need different settings. For example for `modified_gaussian_per_grid()`, we need `sensitivity` and `cutoff`. We need to check these settings.

# Resources

Examples of configs:
**Config for gravity:** 
```json
{
   "supermarket":{
      "max_traveltime":10,
      "sensitivity":250000,
      "weight":1
   },
   "tram_stop":{
      "max_traveltime":15,
      "sensitivity":250000,
      "weight":1
   }
}
```

**Config for closest:**
```json
{
   "supermarket":{
      "max_traveltime":5,
      "weight":1
   },
   "tram_stop":{
      "max_traveltime":10,
      "weight":1
   }
}
```

# Deliverables

# Branch to derive

**Comment by metemaddar** [comment]
I think the config is better to be like:
```json
[
    {
      "category": "supermarket",
      "max_traveltime":10,
      "sensitivity":250000,
      "weight":1
   },
   {
      "category": "tram_stop",
      "max_traveltime":15,
      "sensitivity":250000,
      "weight":1
   }
]
```
Then we can use a general `Config` schema for them. And validate based on term `category`.

**Comment by metemaddar** [comment]
Of course this can have a con that the input can have multiple values for single category :thinking:

**Comment by EPajares** [comment]
Hard decision. I think your idea makes sense. But maybe we could make sure that the category is only used once. So we avoid that the user defines two configs for one category.

**Comment by metemaddar** [comment]
So we can create a Pydantic model for configs for each heat-map type (closest, gravity, etc.) and based on type, validate configurations against it's Pydantic class.

**Comment by EPajares** [comment]
Sounds great

**Comment by metemaddar** [comment]
Implemented (Initiated) for gravity and closest: 5c9e5cec01b541d384ae1188104294ed1f8f3a8e
We need to add others as well.

**Comment by metemaddar** [comment]
:warning: 

- [ ] We need to check this configurations as the configuration style changed.

https://github.com/goat-community/goat/blob/9c05fa5c6b68357ed2af591190bcc8b25c840d8c/app/api/src/crud/crud_heatmap.py#L678

**Comment by metemaddar** [comment]
I think it's also good to use some type `key` for poi/aoi/...
This approach makes code cleaner for validation.

**Comment by metemaddar** [comment]
Of course this also has cons 🤔 
As we may have different pydantic class for poi or aoi

**Comment by EPajares** [comment]
I agree. Or should we make poi/aoi as parent key like:

{
"aoi": {}
"poi": {}
}
