### ISSUE TITLE
Refactor heatmap calculations to categorize the results by opportunity

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1787]
# Goal of this issue
The calculations on heat-maps was designed to do calculations over all data. In the next step, we need to separate the data by opportunities and do calculations per opportunity.

# Resources

# Deliverables

# Branch to derive

**Comment by metemaddar** [comment]
To summarize our meeting on this:

1. Here first of all we need to separate the data (grid_ids & traveltime) and add them to their own category (For example as a dictionary). This also can decrease the sort time as we have smaller data series to sort.
2. Then we need to do calculations based on incoming calculation needs as input (#1786). These calculation names can get connected to their function (#1783) to calculate and add needed data to response.

**Comment by metemaddar** [comment]
When separated grid_ids/travel_times by categories,
The calculations got a bit faster:
Previous Results:
```
sort takes: 0.36031150817871094 s
mins takes: 0.011055469512939453 s
```

New results:
```
sort takes: 0.24292492866516113 s
mins takes: 0.003187417984008789 s
```

Change
```
Sort: -36%
Mins: -70%
```

**Comment by EPajares** [comment]
Could you run a test with all the poi categories we have? They are listed in the opportunity_config table.

**Comment by EPajares** [comment]
I think we can close this.
