### ISSUE TITLE
Implement connectivity heatmap

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1795]
# Goal of this issue
We can create the isochrone area size needed for the connectivity heatmap from the traveltime matrices. I wonder where we save it, though. I believe the best would be to save it in the grid_calculation table, as we cannot create the isochrone shapes from the matrices each time on the fly. 

# Resources

# Deliverables

# Branch to derive

**Comment by metemaddar** [comment]
The steps to get to the areas.

![Image](https://user-images.githubusercontent.com/3726265/215456372-6f9638a9-6efd-4f1b-bf5e-23f1609383a7.jpg)

**Comment by EPajares** [comment]
One thing. We might need the shapes again to intersect with the AOIs. While this will be a separate function, we could reuse the isochrone shapes. For the AOI we need one every minute isochrone so if it is 20 minutes we have 20 isochrones.

We can compute the isochrone like this and then for the connectivity heatmap, we only use the 5, 10 and 15 minute isochrone.

**Comment by metemaddar** [comment]
The files are ready now.
I'm going to config the heatmap endpoint for it.

**Comment by metemaddar** [comment]
I think we can remove the `max_traveltime` from **heatmap_config** as we have `max_traveltime` in main **heatmap_settings**.

**Comment by EPajares** [comment]
I think we should keep it in heatmap_config. As I think we should remove it from the heatmap_settings instead. As for the other heatmaps we also have it inside the heatmap_config
