### ISSUE TITLE
Study Area Names don't show for Munich

### ISSUE THREAD

**Issue by dilaann** [goat-community/goat#1815]
The multi-isochrone calculation for the Munchen area, study area names are just numbers. 
For other study areas like Freiburg or Landkreis Munchen, it seems okay.

![image](https://user-images.githubusercontent.com/80716601/210510625-214f87ce-5504-411c-9a35-eeb55a0490cf.png)

![image](https://user-images.githubusercontent.com/80716601/210510567-ed2f2994-bf42-40d3-b385-fc98ae283a5b.png)

**Comment by EPajares** [comment]
I checked this once more and I saw that we don't have the data currently. @Philipp-Otter  could you add the names into a copy of the table basic.sub_study_area so I can merge them later by ID. You can have a copy of the table inside the temporal schema. 

Somewhere in the Munich statistics portal we should have the names of the district.

**Comment by Philipp-Otter** [comment]
![image](https://user-images.githubusercontent.com/91256148/221511018-6d423a90-aaea-485c-b9b7-b1e9a96a1d51.png)

we have that issue not only in Munich. do you want me to check it for the other areas as well? Should I keep the numbers (in a new column) or overwrite them?

**Comment by Philipp-Otter** [comment]
an example for Munich: 01.1 is the Graggenauer Viertel in the district Altstadt-Lehel, so I would only replace the 01.1 in the column name by Graggenauer Viertel right?

**Comment by Philipp-Otter** [comment]
the data is ready in basic.sub_study_area_copy.

**Comment by EPajares** [comment]
Great I will merge the data and then close this issue

**Comment by Philipp-Otter** [comment]
i mentioned the wrong schema. the data is in temporal.sub_study_area_copy (geonode_p4b_data)
