### ISSUE TITLE
CRUD Heatmap: Combine hexagons, calculations and quantiles

### ISSUE THREAD

**Issue by metemaddar** [goat-community/goat#1873]
At the end we need a table like this:

| id | supermarket | supermarket_class | bus_stop | bus_stop_class | geom |
|----|-------------|-------------------|----------|----------------|------|
|    |             |                   |          |                |      |

We have hexagons saved as geojson and quantiles and calculations as dictionaries and they the quantiles/calculations have another dictionary, named uniques which contain the hexagon_ids. These can get connected together.

**Comment by EPajares** [comment]
We could also try to save the hexagon geoms directly as geodataframe instead of geojson. So we don't need to parse the geojson again using geopandas. We could save them as pickle maybe?

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_pickle.html

**Comment by metemaddar** [comment]
Yes exactly.
And we should also consider the converting calculations to dataframes, which took about **90 seconds**! :snail: :cold_face:

**Comment by metemaddar** [comment]
If I‌ get it well, the data from read_heatmap are in resolution 10. As the request resolution can be different, (For example we loaded resolution 8) then we need to convert the resolution of data from read_heatmap to their grand parent resolution of 8. And also we need to aggregate data (sum, smallest, etc... for different value kinds).
Then we have the resolution match.
At this time we should do the calculations and continue to generate the last GEOJson.
Is this true? @EPajares

**Comment by EPajares** [comment]
I would do the calculation always on 10 and then group it though by average to the target resolution e.g. 8. After it is grouped we will perform the quintile classification. After this we have both index and class on resolution 8.

**Comment by EPajares** [comment]
After this we append them as attributes to the geometries

**Comment by metemaddar** [comment]
The save method had changed to save hexagons(grids, polygons) as numpy arrays.
Now we are going to create the calculations array based on hexagon_grids.


![Image](https://user-images.githubusercontent.com/3726265/212293172-bd63e032-cf3c-4742-9171-100085b160e1.jpg)

I think we can use sparse matrix to reorder calculations_array

**Comment by metemaddar** [comment]
The data which was red from cache, includes some neighbors that are not in study area. We need to omit these calculated data while writing to the final dictionary (Because they don't match the study_area hexagons).
In this picture, the purple hexagons are covering study_area and the orange hexagons are neighbors outside of study_area.

![Image](https://user-images.githubusercontent.com/3726265/212557845-74d19bb7-e12c-415a-9e98-010653cd62de.png)

**Comment by metemaddar** [comment]
At the moment we just need to mask indexes and calculations at the same time:


![Image](https://user-images.githubusercontent.com/3726265/212559193-97cec445-6ba4-48b6-ae08-f2c5fda74dcb.jpg)
