### ISSUE TITLE
Scenario Tool

### ISSUE THREAD

**Issue by AnaSasso** [goat-community/goat#1875]
- [ ] #2143

>Epic: 2. Map Mode/Design #1834

### Scenario Tools Detailing/Design

Create scenario

1. scenario list/create scenario > add intervention 
**2. open scenario**
3. scenarios operations: duplicate, delete, open
4. batch operations: select, merge, reorder

- [ ]<strike>Intervention list</strike>
- [ ]<strike> Combine intervention into a scenario</strike>

- [x] Scenario Flow Miroboard

- [x] Flow Start
- [x] List of Saved Scenarios*
- [x] CRUD Scenarios
- [x] **Types of intervention**
-Point of interest
-Ways
-Buildings
-Public transport
-Data set?

> ***requires more detailing before turning into an issue;
> interactions: same as the current version***
> - [ ] Point of interest detailing design
> - [ ] Ways detailing design
> - [ ] Building detailing design
> - [ ] Public transport detailing design

**Comment by EPajares** [comment]
Not sure if I understand. Do you mean the scenario should be a separate epic?

**Comment by AnaSasso** [comment]
> Not sure if I understand. Do you mean the scenario should be a separate epic?
No, but like other screen settings, different from the map mode (much like the current version)
I say that because the scenarios have a lot of operations inside, especially now with the public transportation scenario.

**Comment by EPajares** [comment]
I understand. Yes, I think it should be a separate state also as we might have to disable some elements, while the users draw a scenario.

**Comment by AnaSasso** [comment]
on scenario mode user creates modifications, those get stored on the scenario environment.
User creates scenarios by combining modifications.
Scenario Layer is on map mode main screen along with other layers. User can expand scenario layer and see the list of modifications under it. To edit user is directed to scenario environment/screen.


Q: How the scenario layer can be intersected on the main screen? eg. inside a scenario might be a point, a line and a block, it it possible to calculate isochrones to it? If not, should the user be able to intersect the modifications individually?

**Comment by AnaSasso** [comment]
![Image](https://user-images.githubusercontent.com/116002158/222839172-b128a386-51f0-48d1-8312-45a715476f5d.png)
