### ISSUE TITLE
Automation Github Projects

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1883]
- [x] #1884
- [x] #1885
- [x] #1886
- [x] #1887
- [x] #1888

**Comment by cinaaaa** [comment]
@EPajares 
Hello Elias,
It's weird that we can't listen and access custom fields change on the issues, even the "Status" that is for Github!
GitHub calls the webhooks on assignees and labels change

Webhook response on the "Issue created":
https://smee.io/Pz4guqgpV7p9NJSB

---

Possible events of issues that can be triggered:
https://docs.github.com/developers/webhooks-and-events/webhooks/webhook-events-and-payloads?actionType=labeled#issues

---

Although it is so powerful and we can read the comments on the issue, maybe a pivot or change plan can help us use their features.

**Comment by EPajares** [comment]
As far as I am aware, the custom fields are not saved with the issues but one the level of projects card. There should be the option to access the cards:

https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/using-the-api-to-manage-projects
Note: We are using Github Project and not Github Project (classic). As they might have two different documentations.

**Comment by cinaaaa** [comment]
> As far as I am aware, the custom fields are not saved with the issues but one the level of projects card. There should be the option to access the cards:
> 
> 
> 
> https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/using-the-api-to-manage-projects
> 
> Note: We are using Github Project and not Github Project (classic). As they might have two different documentations.

I checked it by toggling everything on the issue and also check the triggered webhooks same time, I'll show it to you tomorrow in the daily
