### ISSUE TITLE
Explore if we use Github actions to run automation

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1884]
Github allows high automation of the projects. You can view the docs here:

https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/using-the-built-in-automations

While they allow to use of webhooks, we can also use GitHub actions to listen and execute the needed automation.

https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/automating-projects-using-actions

I think is preferable as we don't have to maintain separate infrastructure for the webhook listeners.
We are currently are already using a GitHub action to add newly opened issue to the repository, as can be seen for instance here:

https://github.com/goat-community/goat/blob/main/.github/workflows/add-issue-project.yml

So, I would propose we try GitHub actions. All the supported triggers can be found here:

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows

I think for testing we should open two testing projects and two testing repositories to cover the use cases we have in the live repos.

**Comment by EPajares** [comment]
@cinaaaa I provided some more context on this task

**Comment by cinaaaa** [comment]
![Image](https://user-images.githubusercontent.com/42252572/214281308-b26fca95-a1eb-404a-9855-8ebe9fd5cc5c.png)

Hopefully just received the hook for the project card, so I guess we can start implementing the automation app.
We should do it at the organizational level and I didn't so because of that I didn't receive any hooks : )
