### ISSUE TITLE
Group hours from mentioned issues into Epic

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1886]
The majority of our issues are part of an Epic. We currently define the Epics with the labels Epic and list related issues inside the comment. An example is here:

[#1883](https://github.com/goat-community/goat/issues/1883)

As we are defining the number of hours for each issue, we should group the sum of hours inside its Epic. So we can populate the hour's field with the sum from its issues. I think technically, we could integrate it inside this automation #1885

**Comment by cinaaaa** [comment]
This needs a refactoring the codebase to use a new library, and I belive that it's not physible for this sprint ( 8 )
