### ISSUE TITLE
Update Video on Public Transport Analysis

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1893]
# Goal of this issue
Hi @iremkapucuoglu, 
we are currently having many Presentations and Pitches, where we show the [Video on Public Transport Analysis](https://vimeo.com/766394906). People like this video, however, we realized that many cannot relate with the example from Munich. Here in Munich, public transport is very good, even at night. So we thought it would be beneficial to also show some insights into more rural areas. 

# Deliverables
Could you exchange **the part on the ÖV Güteklassen** (the rest can stay as it is) and show the county of Fürstenfeldbruck instead of Munich? I would compare Monday 7-9am with Sunday 19-21pm and use Public Transport background map.

# To Do's 

- [x] create draft English - Irem
- [x] feedback English - Ulrike 
- [x] final English - Irem 
- [x] adjust subtitles English - Irem
- [x] final check English - Ulrike 
- [x] upload to Vimeo - irem 

- [x] create German video - Irem 
- [x] feedback German - Ulrike 
- [x] final German - Irem 
- [x] adjust subtitles German - Ulrike
- [x] final check German - Ulrike 
- [x] upload to Vimeo - irem

**Comment by iremkapucuoglu** [comment]
Adding subtitles option is not working, so locked the video on vimeo. I will try later and unlock it

**Comment by iremkapucuoglu** [comment]
Uploading subtitles to vimeo still does not work for me. @UJehle can you please try? The subtitles are in [onedrive](https://plan4better-my.sharepoint.com/:u:/g/personal/elias_pajares_plan4better_de/EdRrrE9T92lEgb9oFGHynYsBLROkHQr1AzOcbfqNNbFuwQ?e=egzMTH)

**Comment by UJehle** [comment]
Hi @iremkapucuoglu , I just checked the German video and added the subtitles. It's ready to be uploaded to Vimeo. 
Thanks & have a nice weekend.
