### ISSUE TITLE
Some buttons are missing hover-over texts

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1897]
### Summary 📃

Most of the buttons ins GOAT show an explanation when hovering over them. However, for those that are marked in red, an information text is missing:
![grafik](https://user-images.githubusercontent.com/49870195/214105389-2d6f942d-f423-4963-8b99-fc1277e71baa.png)

### Expected Behaviour ✔

Show an explanation to give the user an idea what's behind

### Current Behaviour 🔦

User has no clue what's behind

### Possible Solution 💡

Add those little "hover-over" (is it called like this?) texts

### Steps to reproduce 👣

Not sure what I shall write here for this issue. 
Just open GOAT and hover over the icons to see nothing.

**Comment by EPajares** [comment]
This will be checked for the new UI

**Comment by EPajares** [comment]
We need to check which buttons need tooltip and which ones not. @AnaSasso
