### ISSUE TITLE
Add weight to heatmap classes

### ISSUE THREAD

**Issue by metemaddar** [goat-community/goat#1902]
Each opportunity, can have a weight in their config. We can add this weight to get the final heat of hexagon (?)
The formula for adding weight can be like the following:
```math
\huge
 \frac{\sum Q_i \times w_i }{\sum w_i}
```
```math
Q: quantile
```

```math
w: weight
```

**Comment by metemaddar** [comment]
An example of the result is the following:
`[3.0, 2.7, 2.0, 2.0, 3.0, 3.3, 2.7, 3.0, 1.3, 3.7, 2.7, 4.0, 3.3, 2.0, 3.3, 2.7, 2.7, 2.3]`

Here we completely lose the 0s and 5s.

**Comment by EPajares** [comment]
Yes though this depends on the data. In some case we might have only 0 and in other mostly 5. So we can reach values close to 0 or 5.
