### ISSUE TITLE
Update read_heatmap endpoint to reflect the scenario and user data

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1911]
The new implementation of the heatmap does not have scenario building implemented. Basically, we have to recompute the opportunities_matrices when the user is doing a scenario or is uploading custom data. 

Currently, this is saved in the database. In the future, this should be inside the folders. So, we could have a folder per user and its data_upload_ids and scenario_ids.

**Comment by metemaddar** [comment]
I was thinking maybe we can update the heatmaps on the fly. But as you mentioned we can not do the changes to the edges on the fly, as they take more time.

**Comment by EPajares** [comment]
We need to consider the following heatmaps:

- Population
- Comparison Population and Accessibility
- Accessibility heatmaps

**Comment by EPajares** [comment]
Fix this with v2
