### ISSUE TITLE
Redo isochrone videos

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#1921]
Concerning our isochrone videos. the UI here still had some bugs as the color flipping, and we did not have the label for the color in the result section. I was wondering if we could update these two videos, 

![Image](https://user-images.githubusercontent.com/42171996/216262511-b0df414c-a6e1-4541-b3e9-19e28ee8cdf8.png)

**Comment by EPajares** [comment]
@UJehle what do you think?

**Comment by UJehle** [comment]
Yes that would be nice, but I think issues #1893 and #1889 are more important. If we are done with them, then we can address this one here.

**Comment by UJehle** [comment]
To keep the overview of the status, I created the list of subtasks:

# Deliverables

1. English
- [ ] create draft English - Irem
- [ ] feedback - Ulrike & Elias
- [ ] finalize video English - Irem
- [ ] update subtitles English - Irem
- [ ] final check English - Ulrike
- [ ] upload to Vimeo (replace old video) English - Irem

2. German
- [ ] create video German - Irem
- [ ] feedback - Ulrike & Elias
- [ ] finalize video German - Irem
- [ ] final check German - Ulrike
- [ ] update subtitles German - Ulrike/Sophie
- [ ] upload to Vimeo (replace old video) German - Irem
