### ISSUE TITLE
Deleted POIs are still taken into accont for multi-isochrones?

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1922]
### Summary 📃

It seems like the POIs, which are deleted in the scenario, are still taken into account in the multi-isochrone calculation. It's good visible on the POIs in the left: 
![grafik](https://user-images.githubusercontent.com/49870195/216542424-f54c8847-6a0b-4d9f-a71c-7acb3959475a.png)

### Expected Behaviour ✔

If I delete a POI, I expect that it's gone. 

### Current Behaviour 🔦

The POI is still considered to be there. 

### Steps to reproduce 👣

1. open GOAT-Freising
2. Scenario Mode
3. Delete some POIs
4. Calculate Multi-isochrones in scenario mode

**Comment by EPajares** [comment]
I might know what is the reason for this bug. We might have to check one trigger in the DB that might be corrupted.
