### ISSUE TITLE
Implement the combined modified Gaussian function

### ISSUE THREAD

**Issue by Philipp-Otter** [goat-community/goat#1925]
This issue is about adding the combined modified Gaussian function as an alternative to the modified Gaussian function. The idea is based on the paper "The influence of the impedance function on gravity-based pedestrian accessibility measures: A comparative analysis (detailed information about the function are in the section "Impedance function and acceptable travel distance" starting on page 8). We might also need to add an additional parameter to our heatmap input 

Potential new heatmap input (not sure about the variable name):
"atm": {"weight": 1, "sensitivity": 250000, "max_traveltime": 5, "acceptable_travel_time": 5}

Formula of the modified Gaussian function.
![image](https://user-images.githubusercontent.com/91256148/216611568-f14ca4f3-ae0a-4ba1-bb03-b9d968dbbe3e.png)

I implemented it like this:
```
def comb_modified_gaussian_fun(x, b, a):
    """This function calculates the corresponding y values of the combined modified Gauß function for a given x value, a given beta (b) value and a given alpha (a) value. 
    Args:
        x (numpy array): x values at which the function is evaluated 
        a (integer): alpha parameter of the modified Gauß function (threshold travel time)
        b (float): beta parameter of the modified Gauß function (sensitivity parameter)       

    Returns:
        numpy array: y values of the combined modified Gauß function
    """    
    return np.piecewise(x, [x < a], [1, lambda x: np.exp(-((x-a)**2)/b)]) 
```

paper source:
https://plan4better-my.sharepoint.com/:b:/g/personal/philipp_otter_plan4better_de/EXvhq96R8ABPtQSD1rjt3OABGOWK2A26Bf-X3_O4lVeEag?e=tJeIpL

**Comment by EPajares** [comment]
I believe we can maybe adjust the schema like this:

"atm": {"weight": 1, "sensitivity": 250000, "max_traveltime": 20, "static_traveltime": 5}
