### ISSUE TITLE
Only possible to activate 2 isochrone results at the same time?

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1926]
**Is your feature request related to a problem? Please describe.**
Currently, it's only possible to activate two isochrone results at the same time. 
![grafik](https://user-images.githubusercontent.com/49870195/216641504-ff46abcd-8077-45e2-ac4e-913c25d18d8b.png)
Is there any reason for this?

**Describe the solution you'd like**
I would find if very useful to display more than 2 isochrones in the map.

**Comment by EPajares** [comment]
The problem is with the figures and table. As the would very much overflow in the information. In the new UI this might be different.

**Comment by UJehle** [comment]
Ah okay I see. Then I wait for the new UI ;)
