### ISSUE TITLE
Improve video on "Scenario buildings"

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1935]
# Goal of this issue
The building scenarios are quite interesting for some of our potential users. But the current video is not showing the full potentials. 
It would be beneficial to re-create it and show more realistic analysis: 

- draw a full area. I would recommend to use the building area "Dietenbach" in Freiburg. 
![grafik](https://user-images.githubusercontent.com/49870195/218048895-f30b1ea2-bb64-4a98-b047-218058b16f6c.png)
(https://www.freiburg.de/pb/site/Freiburg/get/params_E2083579249/1416935/Dietenbach_Fakten-und-Infografiken.pdf)
HINT: you can draw the buildings in QGIS and then import them

- also draw the paths in GOAT 
- also put new POIs (maybe focus on one category, e.g. kindergartens) >> show heatmap or multi-isochrones to analyse how well the new residents have access to this amenity

# Resources

Use the existing video as a basis. 

# Deliverables

1. English
- [x] create draft English - Irem
- [x] feedback - Ulrike & Elias
- [x] finalize video English - Irem
- [x] update subtitles English - Irem
- [x] final check English - Ulrike
- [x] upload to Vimeo (replace old video) English - Irem

2. German
- [x] create video German - Irem
- [x] feedback - Ulrike & Elias
- [x] finalize video German - Irem
- [x] final check German - Ulrike
- [x] update subtitles German - Ulrike/Sophie
- [x] upload to Vimeo (replace old video) German - Irem

**Comment by UJehle** [comment]
When creating this video, could you also create a nice banner image for the scenario buildings tutorial? (https://github.com/goat-community/goat/issues/1969)

**Comment by EPajares** [comment]
This is ready to be addressed.

**Comment by UJehle** [comment]
@iremkapucuoglu I am not sure if you have seen our comment here. This one is ready to be addressed.

**Comment by UJehle** [comment]
@iremkapucuoglu Elias just fixed the bug, now the dependency of this task should be resolved. you can try if everything works now.

**Comment by EPajares** [comment]
@UJehle is this finished?

**Comment by UJehle** [comment]
No. @iremkapucuoglu had some issues due to her laptop. 
@iremkapucuoglu could you give an update on this one when you are back from vacation and indicate which of teh subtasks above are done?
