### ISSUE TITLE
Change order of legend in pie chart (result window)

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1936]
### Summary 📃

The order of the legend does not fit the order of the categories in the pie. This always confuses me and makes it not so easy to read.
![grafik](https://user-images.githubusercontent.com/49870195/218063849-0849bee9-aa24-42bf-b906-c7747790e04a.png)

### Expected Behaviour ✔

In this example, I would expect to have "Metzger" and "Supermarket" swapped.
![grafik](https://user-images.githubusercontent.com/49870195/218064340-b86bf4b1-e7c9-4fe4-95a8-14dff5563581.png)

### Current Behaviour 🔦

The order in the legend is the exact opposite of the order in the pie chart. 

### Possible Solution 💡

Invert the legend order.

### Steps to reproduce 👣

1. Calculate an isochrone
2. Switch on some POIs
3. Open the result window
4. Get confused by the legend order ;)

**Comment by Ebubeker** [comment]
I do not think that there might be a way to fix this since we import it as a component. I tried changing the way we pass the values but still there is no change to it. I will search to see if we can edit the component. For now we can keep this open

**Comment by UJehle** [comment]
Aah I see. Thanks for investigating on this!
