### ISSUE TITLE
Update Connectivity Heatmap Documentation 

### ISSUE THREAD

**Issue by dilaann** [goat-community/goat#1947]
We need to update the documentation page for the [connectivity heatmap](https://plan4better.de/en/docs/heatmap-connectivity/) by using our new implementation.

@Philipp-Otter  and @metemaddar you can provide the content, and any sources that you use and we can together create a draft.

Thanks,
Dilan

**Comment by dilaann** [comment]
This is the[ last version of draft](https://plan4better-my.sharepoint.com/:w:/r/personal/elias_pajares_plan4better_de/_layouts/15/Doc.aspx?sourcedoc=%7BECE60C37-5A4F-4EA9-A366-FE83606E58F7%7D&file=Document_connectivity_last_version.docx&action=default&mobileredirect=true), we tried to revise the draft by the latest comments. I left a comment about the current implementation about connectivity heatmap in PT and car. It would be really good if you can check and let me know so I can publish the doc. Also, I'm a little bit confused, is this new version of connectivity heatmap released? Should I wait until we released to have this document in website? @EPajares

**Comment by dilaann** [comment]
I believe we can close this issue once we have the German translation. We already released for EN page.

**Comment by EPajares** [comment]
I updated it and now the docs will be taken forward by @UJehle to transform it for the new version
