### ISSUE TITLE
Update Local Accessibility Documentation Page

### ISSUE THREAD

**Issue by dilaann** [goat-community/goat#1948]
We need also to update this page for[ Local Accessibility.](https://plan4better.de/en/docs/heatmap/)

Thanks,
Dilan

**Comment by Philipp-Otter** [comment]
- [ ] update documentation (@EPajares, @Philipp-Otter)
- [ ] add it to Github (@dilaann)
- [ ] final check (@EPajares) 
- [ ] translation to German (@UJehle)
- [ ] release (@UJehle)
