### ISSUE TITLE
Missing translation key for "VeryHighConnectivity"?

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1949]
### Summary 📃

![grafik](https://user-images.githubusercontent.com/49870195/218750292-3853db1f-5e53-4e27-a136-521b239bea94.png)
Either the translation key or just the spaces are missing here.

### Steps to reproduce 👣

1.
2.
3.
4.

**Comment by UJehle** [comment]
@majkshkurti please feel free to reassign it.

**Comment by EPajares** [comment]
We were missing a translation in the style. I fixed it.
