### ISSUE TITLE
German text "Leichter Erreichbarkeitsüberschuss" does not fit into text box

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1953]
### Summary 📃

The text box seems too small for the long text
![grafik](https://user-images.githubusercontent.com/49870195/219309789-601072ad-acc1-44dd-b986-b3ecea609c48.png)

### Steps to reproduce 👣

1. Open GOAT
2. Activate any POI
3. Activate heatmap "comparison accessibility and population density" 
4. Switch to German

**Comment by EPajares** [comment]
This was an duplicated #2024
