### ISSUE TITLE
Add a banner image to tutorials 

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1969]
# Goal of this issue
@dilaann @iremkapucuoglu What do you think about the idea of always including a nice-looking banner image in the written tutorials? 
E.g. like this: 
![grafik](https://user-images.githubusercontent.com/49870195/221425273-9586a5c1-7f65-48fa-a4a0-fe0445a0a5b9.png)

This would be good for SEO (search engine optimization) but also for the reader as they immediately see what this section is about. 

For the sake of uniformity, it may make sense to use the same image size as for the banner images on the blogpost (900x450 pixels).

# Branch to derive
p4b-website

**Comment by dilaann** [comment]
Hi, yes it looks really nice, we should definitely add it.

**Comment by UJehle** [comment]
Thanks, @dilaann that looks good!
