### ISSUE TITLE
[BUG] Buildings disappear on building scenarios

### ISSUE THREAD

**Issue by iremkapucuoglu** [goat-community/goat#1978]
## Current Behavior

When I add a building I cannot see it properly anymore to add an entrance for example. Also, I cannot see my previous building drawings when I try to draw a new one.

## Detailed Description
I used Google Chrome as browser and here is a video about the issue

https://user-images.githubusercontent.com/73173737/222408229-c655bfbd-dd93-4d82-a906-224492370bdc.mp4

**Comment by dilaann** [comment]
Solution : Try different browsers & versions and let us know if it's still a problem. @iremkapucuoglu

**Comment by Ebubeker** [comment]
I am failing to reproduce this bug, @iremkapucuoglu can you give further detail and can you also check if you are still having this issue?

**Comment by iremkapucuoglu** [comment]
Actually, I was not having this problem while using Microsoft Edge as browser. Today I tried and it also works for Google Chrome. I think problem solved

**Comment by Ebubeker** [comment]
Closing it as it is no longer a problem
