### ISSUE TITLE
[BUG] some POI icons are not loading in map

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#1984]
### Summary 📃

![grafik](https://user-images.githubusercontent.com/49870195/222824607-9f831131-cba6-4b8f-b885-1eb72c48251b.png)
![grafik](https://user-images.githubusercontent.com/49870195/222824700-2a74e8b2-071c-41ec-9f89-0d5dad2590c5.png)
I think something is wrong with the custom icons 

### Expected Behaviour ✔

See the icon that I picked 

### Current Behaviour 🔦

See an error icon

### Steps to reproduce 👣

Browser: Firefox

**Comment by Ebubeker** [comment]
@UJehle is this still an issue? or is it fixed since I am unable to replicate it

**Comment by UJehle** [comment]
I just checked it. 
![grafik](https://user-images.githubusercontent.com/49870195/234681285-877fd4c9-af2d-4a24-8fc4-5126379eec72.png)
The error icon is not there anymore, but the "Tram" icon still looks a bit weird. Also for "bikesharing" the white lines seem not to be fully rendered. 
![grafik](https://user-images.githubusercontent.com/49870195/234681793-4828762d-0737-4e38-bed6-553f5fe98252.png)

**Comment by Ebubeker** [comment]
@UJehle I do not know why but my icons appear differently from yours. Maybe you have changed them before and they show up like this.

**Comment by Ebubeker** [comment]
Try logging in with webmaster

**Comment by UJehle** [comment]
@Ebubeker what do you mean with webmaster? 
I just tried it with another browser (Chrome), there it looks the same. 
Furthermore, I found that I can somehow not change the icon of the POI category "metro station" in the Munich version. Do you also have this issue?

**Comment by Ebubeker** [comment]
can you log in with another account. I think the issue is that you might have changed some of the poi icons before. Thats why the default Icons do not appear there. Some of my icons look different.

**Comment by UJehle** [comment]
I just logged in with webmaster and picked the same icons (the custom icons that we provide):
![grafik](https://github.com/goat-community/goat/assets/49870195/852b6bc7-b772-4937-8408-9dee1faed170)
I don't get an error anymore but the icons are not looking as nice in the map as they do in the legend, especially for "tram", "bus" and "bikesharing" it's quite hard to see the lines in the icons. So they just look like a filled block or circle.

**Comment by Ebubeker** [comment]
In that case we need to make the markers bigger since It also depends on the resolution of the users device. @EPajares what do you think about it?

**Comment by EPajares** [comment]
Yes. Even if we make it bigger it might not be enough as the icon is inside the marker. I think we would have to redesign the markers from scratch to allow such custom icons look good. Something we have to explore in v2. But it will not be simple as the markers are of different shapes and not necessarily made to be shown on a map.

**Comment by UJehle** [comment]
The initial bug just appeared again:
Tram & U-Bahn icons are not loading (some minutes ago they were showing, so I am not sure what the issue is)
![grafik](https://github.com/goat-community/goat/assets/49870195/c791f9ad-c1ae-467c-b54c-a63c437db6cb)
