### ISSUE TITLE
Heatmap Bugs: Border Hexagons

### ISSUE THREAD

**Issue by Philipp-Otter** [goat-community/goat#1992]
In the current version in the feature branch walking-matrix are a few bugs. When you run multiple study areas, the border hexagons have wrong values and are duplicated. 

![image](https://user-images.githubusercontent.com/91256148/223966820-d0f43afd-a328-457e-a5b4-ac4530ffff7a.png)

![image](https://user-images.githubusercontent.com/91256148/223967074-d82d4fd6-c0c6-4381-9794-3cd607a243a3.png)

**Comment by EPajares** [comment]
This is fixed now
