### ISSUE TITLE
Heatmap Bugs: Closest Average -> wrong quintiles and aggregation

### ISSUE THREAD

**Issue by Philipp-Otter** [goat-community/goat#1993]
In the current version in the feature branch walking-matrix are a few bugs. When you calculate the closest average, the quintiles are wrong as the best value is zero, but zero gets neglected in the quintile classification. The hexagons that do not reach an amenity in the given max travel time get the value NULL, but after the quintile classification, the value is zero as well, so the best hexagons and the worst hexagons have the same value. In general, it might make more sense to assign as many quintiles as max travel time.  

![image](https://user-images.githubusercontent.com/91256148/225622245-444dc5d4-f6a6-4681-8244-98a773dff23f.png)

![image](https://user-images.githubusercontent.com/91256148/223970282-ec3fdcc1-233e-4d04-aa98-c8efbf3f8f09.png)

**Comment by EPajares** [comment]
remove class from the closest average endpoints

**Comment by EPajares** [comment]
We keep this and avoid having another exception. I client we need to make sure to not use the classes and use the absolute values instead e.g. 5min, 10min, 15min
