### ISSUE TITLE
[BUG] POI count in result table doesn't match with POI count in pie chart

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#2062]
### Summary 📃

POI count in the result table: "48 cafes"
![grafik](https://user-images.githubusercontent.com/49870195/226964732-f54e6c44-ad7d-4c12-bff6-0d8daf19481f.png)

POI count in the pie chart: "13 cafes"
![grafik](https://user-images.githubusercontent.com/49870195/226964962-b265c73f-9dd6-4eb1-9c25-b0a252794d3c.png)

I think something is not matching here.

### Steps to reproduce 👣

1.
2.
3.
4.

**Comment by EPajares** [comment]
The problem here is that the figure does not auto-refresh. You need to go back to the figure and I think it should auto-refresh. Could you check again?

**Comment by UJehle** [comment]
I am not sure if I understand what you mean. I tried to switch to the sum curve and to the table, as well as closing and reopening the result window, but no reaction is shown in the pie chart:
https://www.awesomescreenshot.com/video/15950365?key=3e5e10187eabf952495f69de6b53f8d1

**Comment by EPajares** [comment]
Maybe @Ebubeker can you check this one. It seems to me at the moment that it only happens in Amsterdam

**Comment by EPajares** [comment]
I think it might be a general problem that the charts don't refresh
