### ISSUE TITLE
[BUG] There is one marketplace which is not shown as POI but included in the multi-isochrone results (Amsterdam)

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#2063]
### Summary 📃

There is one marketplace which is not shown as POI but included in the multi-isochrone results (Amsterdam)
![grafik](https://user-images.githubusercontent.com/49870195/226968448-02fc2878-84da-4a81-ae92-1c3966273354.png)

We just checked the database. This POI exists in the dev-db: basic.poi
![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/49870195/226968717-2d87eec1-f5a8-461c-bdb7-bfb2186a98db.png)

Not sure what went wrong here.

### Steps to reproduce 👣

1.
2.
3.
4.

**Comment by EPajares** [comment]
I think this should be fixed as I am not getting this in prod
