### ISSUE TITLE
Add further endpoints for data preparation

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2074]
-Merge heatmap preparation endpoints
- Add file migration logic to the endpoint

@majkshkurti add cleaned payload, add endpoint boiler plate

**Comment by EPajares** [comment]
Clean the payload as it has stuff we don't need

![Image](https://user-images.githubusercontent.com/42171996/228002127-e683fce3-52f5-4b86-b152-c12ce6e6c0f4.png)

**Comment by majkshkurti** [comment]
We should refactor the payload for this. 

I am proposing the following payload: 

{
  "study_area_ids": [],
  "scenario_ids": [], // Optional Default all
  "user_data_ids": [], // Optional Default all
  "exclude": [], // Optional Default empty ("analysis_unit", "opportunity", "traveltime_matrices", "connectivity_matrices", "opportunity_matrices")
  "s3_folder": "", // Optional Default empty
  "config": {
    // Overwrite default config
    "data": {
      "analysis_unit": {
        "h3_bulk_resolution": 6,
        "high_h3_resolution": 10
      },
      "opportunity": {}
    },
    "traveltime": {},
    "heatmap": {
      "connectivity": {},
      "opportunity": {}
    }
  }
}
