### ISSUE TITLE
[Gent] Indicators not working

### ISSUE THREAD

**Issue by AnaSasso** [goat-community/goat#2080]
<img src="https://user-images.githubusercontent.com/116002158/228018494-30057206-e9bb-4ecf-9cfa-f56973e4477a.png" width=50% height=50%>

<img src="https://user-images.githubusercontent.com/116002158/228028100-16d80c5a-476a-4398-afb7-f2391d5a1357.png" width=50% height=50%>

**Comment by dilaann** [comment]
I also noticed that for Ghent, I think isochrone is not computing too.

**Comment by UJehle** [comment]
Is it possible to prioritize this issue? I just got another email from the local planners.

**Comment by EPajares** [comment]
Yes as mentioned in the daily I will try fixing these data related issues for gent and deerfield today
