### ISSUE TITLE
Refactors

### ISSUE THREAD

**Issue by metemaddar** [goat-community/goat#2084]
Two main parts to refactor:
1. Core
2. API

For Core we need to break apart the code into small testable functions. Mainly in heatmap.

And for API there are some parts to refactor:
- Replace all is_superuser checks with superuser dep
- Customizations endpoint >> Replace CRUDBase with it's own CRUD
- Create a get_or_404 method to raise 404 when the object not found and replace in all endpoints that need
- data_preparation endpoint >> move display_top to utils

This list can get increased. But we also need to specify the urgent part.

Tasks:
- #2145

**Comment by EPajares** [comment]
Define concrete tasks out of this and see how it has to be integrated with running refactoring.
