### ISSUE TITLE
Harmonize Legends of Connectivity and Local Accessibility Heat Map

### ISSUE THREAD

**Issue by Philipp-Otter** [goat-community/goat#2089]
![Image](https://user-images.githubusercontent.com/91256148/228203899-3fac2901-1d8b-45a8-9429-245d6709f62d.png)

![Image](https://user-images.githubusercontent.com/91256148/228203979-867db343-3b51-4322-bff8-0966fbf99801.png)

maybe we can use the one of the connectivity for both, so very low, low, rather low, rather high, high, very high

**Comment by EPajares** [comment]
I changed this in the settings
