### ISSUE TITLE
[Amsterdam] [Bug] Scenario/Way not saving

### ISSUE THREAD

**Issue by AnaSasso** [goat-community/goat#2117]
### Summary 📃

Study area: Amsterdam
Tool: Scenario/Way

### Expected Behaviour ✔

Draw way>feature saved

### Current Behaviour 🔦

After draw complete alert message: "Can't save features"

<img src="https://user-images.githubusercontent.com/116002158/230114051-2fe6cd48-a542-417e-a21c-2c00c5c55d6b.png" width=50% height=50%>

### Steps to reproduce 👣

1. Open GOAT Amsterdam
2. Create scenario
3. Select way
4. Add way to study area

**Comment by EPajares** [comment]
Thanks for reporting! It was my fault something related to the DB. Fixed it.
