### ISSUE TITLE
Implement way scenario for heatmap

### ISSUE THREAD

**Issue by AnaSasso** [goat-community/goat#2121]
### Summary 📃

Way scenario is not interacting with connectivity 

### Expected Behaviour ✔

Connectivity heatmap update to include new scenario/way

### Current Behaviour 🔦

Connectivity heatmap does not update to include new way

<img src="https://user-images.githubusercontent.com/116002158/230210706-69cf943c-b150-4e2c-af53-cdb0a0f08cbf.png" width=80% height=80%>

### Steps to reproduce 👣

1. open amsterdam
2. create new scenario
3. add new way
4. turn on connectivity heatmap

**Comment by EPajares** [comment]
This is not implemented at the moment. But yeah, it is hard to tell which indicator reacts to scenarios. With new heatmap implementation, this gets more feasible (computationally wise) to do though.
