### ISSUE TITLE
[London] Double check the routing network

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#2126]
I think based on the German settings, "primary" roads are excluded from the walking & cycling network.
In London, it seems like this road category has a bit of a different meaning. 

For example, this is a primary road that seems to also have sidewalks: 
https://www.openstreetmap.org/way/245866919#map=18/51.49719/-0.10963
I guess this is the case for most of the primary roads in London.

**Comment by EPajares** [comment]
I had this properly configured but somehow the setting where deleted. Added it again but need to check what has caused this.
