### ISSUE TITLE
[BUG] POI icons disappear depending on browser zoom level

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#2158]
### Summary 📃

When changing the zoom-level of the browser, it might happen that the POI icons disappear:
https://www.awesomescreenshot.com/video/16738099?key=c46cbaaccbb0d1fcb248d5f1f945b496

### Expected Behaviour ✔

POI icons are always visible

### Current Behaviour 🔦

POI icons are not always visible

### Steps to reproduce 👣

1. Open GOAT
2. Activate POIs
3. Change the zoom level of the browser (CNTR + /CNTR -) 
4. See that the icons disappear

**Comment by Ebubeker** [comment]
@UJehle I can try to check this further since it shows up only on big study areas where there is a min zoom property

**Comment by majkshkurti** [comment]
For some reason, I can't reproduce this error on my machine. It might be due to the fact that I am using Linux or I have a dedicated GPU.
