### ISSUE TITLE
[BUG] Fix wording in average public transport departure pie chart

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#2160]
The word "Bushaltestelle" doesn't make sense in this context. It should be only "Bus". 
![grafik](https://user-images.githubusercontent.com/49870195/233837925-b273fbb2-ebff-499c-b1a9-26d0e4fc550f.png)
The English texts are fine. 

@Ebubeker could you fix this?

**Comment by Ebubeker** [comment]
I fixed this one too, it was a mistake in the translations, sorry. I will push the requests a bit later after I deal with the other bugs
