### ISSUE TITLE
User Onboarding

### ISSUE THREAD

**Issue by AnaSasso** [goat-community/goat#2163]
[Onboarding Flow
](https://plan4better-my.sharepoint.com/:x:/g/personal/ana_sasso_plan4better_de/EZx3n6tdXN9GlYTWieywGs8BpZ9gi5hJlHMt-hmX-HuDjg?e=o8sefk&nav=MTVfezc2MEZBQjhFLUY2NzEtNDFCNS1BNUU5LTU2N0IwRTI0QUUwOX0)

![Image](https://user-images.githubusercontent.com/116002158/234636299-2c448f3d-bd62-429f-910b-a2c34ad6455f.png)

**Comment by AnaSasso** [comment]
[Figma](https://www.figma.com/file/tu6pPILBRSUuy3Hbu8Lphk/Goat-3.0?node-id=11487%3A119349&t=SDIKOfywY2YTojOk-1)

[Ppt Presentation](https://plan4better-my.sharepoint.com/:p:/g/personal/ana_sasso_plan4better_de/EanKHIEvHwFHt7SfB8V1nmABVJoobA9TzyEvqvHgHR-AOA?e=DdvKaL&nav=eyJzSWQiOjI5NSwiY0lkIjoyODQ1ODg2ODMyfQ)

**Comment by AnaSasso** [comment]
- [ ] Design review 04/05/23

**Comment by EPajares** [comment]
Isn't this finished?
