### ISSUE TITLE
New public transport indicator: trip pairs

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#2190]
**Idea**
In the GOAT 3.0 meeting, Shravan suggested to also integrate the calculation of trip pairs ("Fahrtenpaare") between locations, as this is relevant for local transport planning. 

**Describe the solution you'd like**
The solution could look like this:
1. user defines 2 points (one start point and one end point) 
2. user picks time
3. routing algorithm calculates how many connections there are between these two points and what the average travel time is

If you like this idea, it could make sense to talk to Shravan to discuss the needs further. 

**Additional context**
Don't know yet how it will look like but from the logic roughly like this >> want to know how good accessibility and public transport supply is between these two points (here: Goetheplatz & Münchner Freiheit)
![grafik](https://user-images.githubusercontent.com/49870195/235222816-de6138bd-9f72-4001-8ea5-800532466584.png)

**Comment by EPajares** [comment]
Yes I think I discussed it twice with him before. The complexity depends a bit. when considering interchanges it gets complex as we need some sort of routing and with the routing we use can just compute isochrones. Traditionally this is only done for stations of one line but it would be more interesting having the information for several lines connecting two points. Meanwhile, we have to consider that there might be several options for the fastest route. I guess we need to do some research first while discussing with Shravan again.

**Comment by UJehle** [comment]
_Notes from call with Shravan:_ 

**Desired Input:**
- start point (transport stop, without access trip)
- end point (transport stop, without egress trip)
- day 
- time of the day
- max travel time
- max number of changes 

**Desired Output of the analysis:** 
- xxx trip options available
- list with all options (maybe also show the routes on the map, e.g. use line thickness to show how frequency of lines)
- (matching with guideline frameworks)
- (average travel time, aggregated by times of the day)
