### ISSUE TITLE
Add heatmap settings to print

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#2226]
# Goal of this issue
The user can adjust the weight & sensitivity index of the POIs, which has a direct impact on the look of the heatmap.
![grafik](https://github.com/goat-community/goat/assets/49870195/93f8b2f5-4a68-4242-9630-2ae326a1b92a)
However, when printing the results, those settings are not visible. Thus, it's hard to interpret the maps. 

I think it would be good to have a short summary of the settings in the legend (or at least the option to enable it):
![Bild1](https://github.com/goat-community/goat/assets/49870195/4d26a1e4-73e9-4564-8828-a4795820d607)

**Comment by EPajares** [comment]
Mhh I think it will not look good on the printed map. Also this is quite hard to manage at the moment to control the text on the print layout. Imagine a user select 10 POIs. The settings thing is something we should properly address in v2 by adding the metadata to the layers.
