### ISSUE TITLE
Dynamic visualization of the accessible POIs over time

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#226]
Backend:
- [x] implement opening hours function

Frontend:
- [x] add a button/checkbox to '*open*' the time based functions
--> if the button is checked, the functions "thematic_data_sum" and "thematic_data_sum_time" shall be executed
--> if the button is not checked, only the function "thematic_data_sum" shall be executed 
- [x] add a time slider/clock
- [x] add a drop-down with weekdays
- [x] visualize open (with coloured icons) and closed POIs (with grey icons)
- [x] grey out all categories in the "Thematic Data" menu that are not dependent on opening hours

**Comment by EPajares** [comment]
@majkshkurti

**Comment by EPajares** [comment]
@UJehle could you put the list of the pois that should not be greyed out here. So @majkshkurti can use it.

**Comment by UJehle** [comment]
For my study area it would be nice to grey out the following amenities if the routing_profile "walking_wheelchair" is selected:
- recycling
- atm
- charging station

and the following amenities if the "opening hours" menu is activated:
- transport (complete category)
- kindergarten
- primary school
- secondary school
