### ISSUE TITLE
[BUG] Population data is not refreshing on scenario

### ISSUE THREAD

**Issue by iremkapucuoglu** [goat-community/goat#2263]
I created building scenario and opened the comparison mode, population density is not refreshed.

## Expected Behavior
![image](https://github.com/goat-community/goat/assets/73173737/bd632323-c99b-432e-a3f7-2bb21087dfbb)

## Current Behavior
![image](https://github.com/goat-community/goat/assets/73173737/4be6904c-deca-4849-9a77-53cf0d419c47)

**Comment by EPajares** [comment]
Thanks. This issue is duplicated here.
https://github.com/orgs/goat-community/projects/1/views/27?pane=issue&itemId=24939166

**Comment by UJehle** [comment]
Did you already found the reason for this? The City of Gent also just reported this issue.
It also affects the “Accessibility and Population Density” heatmap: https://www.awesomescreenshot.com/video/18292742?key=4e1c32717cf2b83931db54e7c9daf079

**Comment by UJehle** [comment]
Thanks for fixing @EPajares , now it works.
