### ISSUE TITLE
Missing discount gym data in Freiburg

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#2302]
### Summary 📃

In the Freiburg version, we have the POI category "Discount Gym", but no data for it.
![grafik](https://github.com/goat-community/goat/assets/49870195/854ec372-5bf3-4e77-872c-c761cee84f2f)

### Expected Behaviour ✔

POIs are showing

### Current Behaviour 🔦

POIs are not showing

### Possible Solution 💡

Either adding data on discount gyms or removing this category.

### Steps to reproduce 👣

1. Open GOAT
2. Go to Freiburg version
3. Activate "Discount Gym" POIs
4. See no data

**Comment by EPajares** [comment]
I removed it from freiburg not needed as there is also lack of data
