### ISSUE TITLE
Not sure what the aoi graph in the result window is supposed to show

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#2303]
### Summary 📃

I am not sure what the aoi graph in the result window is supposed to show:
![grafik](https://github.com/goat-community/goat/assets/49870195/c47f93ca-3a7c-4e32-841e-eda13fd417ef)

### Expected Behaviour ✔

don't know

### Current Behaviour 🔦

shows a graphic that is hard to interpret

### Steps to reproduce 👣

1. Activate AOIs (parks, forest)
2. Calculate 2 isochrones
3. Open the result window and look at the graphics
4. Try to understand the figures

**Comment by EPajares** [comment]
The thing was that the units where so different from amenity count and m² of AOIs. There is a new view only for AOIs now
