### ISSUE TITLE
Add export option for all indicators in the UI

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2310]

**Comment by EPajares** [comment]
We can export all indicators now in the following formats:


class IndicatorResultsReturnType(str, Enum):
    """Combination of Heatmap and Isochrone Return Types"""

    GEOJSON = "geojson"
    CSV = "csv"
    GEOBUF = "geobuf"
    SHAPEFILE = "shapefile"
    GEOPACKAGE = "geopackage"
    KML = "kml"
    XLSX = "xlsx"

**Comment by EPajares** [comment]
This endpoint is doing the export:
![Image](https://github.com/goat-community/goat/assets/42171996/dcb17428-f566-43c8-b6bd-135fe081c490)

Before being able to do the export though we need to call the indicator endpoint to receive the task_id. For each export we need a new task id at the moment. So we need to call the indicator each time before running the return endpoint.

In the UI we can just add the same download Icon we are having for the isochrones at the moment.

![Image](https://github.com/goat-community/goat/assets/42171996/bdac752b-e7d2-47b0-8f13-11d0c0103b8e)

Note: we also need to change the endpoint for the isochrones as we can then remove the old isochrone export endpoint.

**Comment by EPajares** [comment]
@Ebubeker  If there is time you can work on it during this sprint if not the next one

**Comment by Ebubeker** [comment]
This is paused for now since the returned data in the heatmaps cannot be parsed. We checked this with Majk and the problem was not in the Client.
