### ISSUE TITLE
Heatmap disappears when adding a new POI

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#2316]
### Summary 📃

When making a scenario and adding a new POI, the heatmap disappears. I need to deactivate & activate it again in order to appear:
https://www.awesomescreenshot.com/video/18357430?key=c57255659e7c06ab6ec4f4b46b4434b6

### Steps to reproduce 👣

1.
2.
3.
4.

**Comment by EPajares** [comment]
I could not really reproduce this. For me it generally works. Do you have more context on it?

**Comment by UJehle** [comment]
Not sure which further context is helpful.
Browser: Firefox
City: Freiburg

Here is a longer screencast showing the bug:
https://www.awesomescreenshot.com/video/18387738?key=0de7642c4f5356eba60af260c037c6dc
(in this example I already had buildings there, but same bug happens if I only place a POI, without buildings)
