### ISSUE TITLE
Add meta data to the export of indicators

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2338]
# Goal of this issue

# Resources

# Deliverables

# Branch to derive

**Comment by EPajares** [comment]
It would be good to add a short text file called info.txt with meta information inside the export folder of the indicators. 


I think we should add the Coordinate reference system which is at the moment EPSG:4326. But maybe we can still dynamically read it from the file that is produced using ogr2ogr as it might vary in the future. Furthermore, we could add the date and a note that this was computed using GOAT (with link to Github) and Plan4Better (Link to website).

**Comment by metemaddar** [comment]
The conversion utility needs some more changes. Some files need to get converted to zip first. The shape file is already zip, as it contains multiple files.
Thanks for your patience.

**Comment by EPajares** [comment]
OK sure sounds reasonable. I think it is good to always return zip with the exception of geobuf and binary. As this is currently only used inside GOAT and not for export.
