### ISSUE TITLE
Redo Multi-Isochrone Video

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2358]
I think we can improve the multi-isochrone video with the following:

- Show another area then city center of Freiburg. The accessibility to the chosen amenities is very high therefore we are having very little insights. Maybe we should do the same in a county and with other POIs (Public transport stops?)
- Zoom in more in the video.
- Show the slider functionality.

**Comment by UJehle** [comment]
Hi @iremkapucuoglu, could you have a look at this one? 
I think it would especially be good to play around a bit more with the travel time slider (e.g. put it to 5min) that the catchment areas become smaller and the shares are a bit more interesting (in the current video, all of them are about 100%).
