### ISSUE TITLE
Research and Test Maplibre + (Deck.gl) + React-Map.gl

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2363]
Currently we have considered using maplibre(react map.gl) and deck.gl as the mapping library for the front end. Each library has strengths and weaknesses in different aspects. 
For GOAT we need to meet the following requirements:

- Use vector tile layer with a dynamic style configuration stored in a json format (mapbox style)

- Allow style editing in the client

- Layer editing (Geometry and Attributes)

- Complex style visualisation (e.g Charts etc). Can this work with vector tile ? How to achieve it ?

We can test this with some real data and use case scenarios.

**Comment by baghdasarovnorayr** [comment]
https://www.notion.so/Research-and-Test-Maplibre-Deck-gl-React-Map-gl-22283f8c72674b54aaf62e54cf8aa1b6?pvs=4
