### ISSUE TITLE
UI Map Base Component (only with Basemap)

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2364]
We need a simplified prototype of the **Project** to start testing the core map functionalities (style and editing).

**Comment by EPajares** [comment]
- Create the map based on the JSON from project
- Style the layers using the JSON from Geostyler/Mapbox

**Comment by EPajares** [comment]
- Add for each layer type one example in the storybook.

**Comment by baghdasarovnorayr** [comment]
https://github.com/goat-community/goat/pull/2405

**Comment by baghdasarovnorayr** [comment]
![Image](https://github.com/goat-community/goat/assets/138683176/171a6903-7060-4797-b532-ae9ccd876530)



![Image](https://github.com/goat-community/goat/assets/138683176/e540eb67-75f3-4a8e-a4ea-5237e4419de4)
