### ISSUE TITLE
[BUG] Recalculation of indicators fails for uploaded POI data set

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#2386]
### Summary 📃

I uploaded the Nahversorger POI data from Freiburg, but when I want to recalculate the indicators, I get this error message:
![grafik](https://github.com/goat-community/goat/assets/49870195/e6c3afaa-c091-4eb6-bf44-4bf2e8648cb7)

### Expected Behaviour ✔

The indicators are recomputing

### Current Behaviour 🔦

The indicators are not recomputing

### Steps to reproduce 👣

1. Open GOAT Freiburg
2. Upload the own POI data set (e.g. the one I shared in the chat this morning)
3. Try to recompute the indicators
4. See it fail

**Comment by EPajares** [comment]
This is duplicated [#1911](https://github.com/goat-community/goat/issues/1911)
