### ISSUE TITLE
Text in Infobox is not displayed correctly

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#241]
On the GOAT Website, the line breaks in the Infobox are not displayed correctly.
<img width="230" alt="Anmerkung 2019-11-20 103036" src="https://user-images.githubusercontent.com/49870195/69226736-ed1c5d80-0b80-11ea-9b0d-2fd9224033cb.png">

**Comment by EPajares** [comment]
@majkshkurti is there a way to fix that? So basically can we make sure that only full words are in a new line.

**Comment by majkshkurti** [comment]
@EPajares I didn't see this. It's a pretty straightforward fix. 
I will have a look and open a PR.

**Comment by majkshkurti** [comment]
Fixed at #285
