### ISSUE TITLE
add Snackbars and alerts when we do an action that requires them

### ISSUE THREAD

**Issue by majkshkurti** [goat-community/goat#2446]

**Comment by baghdasarovnorayr** [comment]
https://github.com/goat-community/goat/pull/2453

![Image](https://github.com/goat-community/goat/assets/138683176/f2e9e3a7-2f16-4b58-b104-207f979b889e)

**Comment by baghdasarovnorayr** [comment]
https://github.com/goat-community/goat/pull/2444
