### ISSUE TITLE
Fix errors Nextjs

### ISSUE THREAD

**Issue by majkshkurti** [goat-community/goat#2447]
There are 3-4 errors coming from the ui components. 

![image](https://github.com/goat-community/goat/assets/32641116/0a461c48-e33c-4ff2-a6c9-59d9a2a7eb1c)

**Comment by EPajares** [comment]
Check in which component this happens and see how the error can be fixed.

**Comment by baghdasarovnorayr** [comment]
As of now, there are no errors to report. It appears that the issues have been resolved, possibly during the completion of another task.
