### ISSUE TITLE
New grid bug

### ISSUE THREAD

**Issue by majkshkurti** [goat-community/goat#2457]
There is too much space between cards in the home page. 

![image](https://github.com/goat-community/goat/assets/32641116/71dc6b8d-f606-4d43-950a-df1d670ea9fb)

**Comment by Ebubeker** [comment]
maybe we can tackle this by adding more cards in bigger screens

**Comment by majkshkurti** [comment]
Yes can work, although I would say the spacing between cards might be better to remain constant

**Comment by Ebubeker** [comment]
what if we do this as a carousel, so it basically has 2 arrows to navigate, maybe we can make it as simple as possible so it doesn't make the website look messy

**Comment by Ebubeker** [comment]
or we can avoid the grid for the home page, and base it around the cards

**Comment by EPajares** [comment]
Let's do it as shown in the last screenshot

**Comment by baghdasarovnorayr** [comment]
@Ebubeker Have you opened or merged a pull request (PR) regarding this issue? Have you made any changes, or is everything currently in good shape?

**Comment by baghdasarovnorayr** [comment]
![Image](https://github.com/goat-community/goat/assets/138683176/f3ac2034-11b1-4a3c-b371-8963c9ca7731)
