### ISSUE TITLE
Insert GetFeatureInfo for ways

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#248]
Display an info box with feature information when a way is clicked (like the info box for POIs).

**Comment by EPajares** [comment]
Is this related to the new layers I assume right?

**Comment by UJehle** [comment]
Right. The idea was, that the user can see all the attribues attatched to a way and thus understand why for exmaple a path is not suitbale for wheelchairs.

**Comment by EPajares** [comment]
@majkshkurti

**Comment by majkshkurti** [comment]
@EPajares @UJehle 
We can have more layers in the future that we may need GetInfo, so it's better to do it not only for the ways, but for all layers that we have in geoserver.

**Comment by EPajares** [comment]
Sounds reasonable. The best would be that we can restrict which attributes are shown for a certain layer. As for some layers it is useless to show to many attributes. So it could be good to add an array of attributes that should be shown in the app-config.json. what do you think?

**Comment by majkshkurti** [comment]
Yeah. That's what i was thinking. For each layer we will handle the configuration to the app-conf file including attributes.

**Comment by UJehle** [comment]
I now handled the viewed attributes in the Geoserver SQL views of the layers.
