### ISSUE TITLE
Link to blog post is outdated

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#253]
As the blog was deactivated, the link down here is now outdated.
![Inkederror_LI](https://user-images.githubusercontent.com/49870195/69499480-d19fb280-0ef2-11ea-94dc-847813fa7c75.jpg)

When trying to access it, the following error occurs:
<img width="611" alt="error2" src="https://user-images.githubusercontent.com/49870195/69499426-4aead580-0ef2-11ea-9249-44a9e0f2aa09.png">

We should delete the last sentence or reactivate the blog site.

**Comment by EPajares** [comment]
Thanks for reporting! I fixed it.
