### ISSUE TITLE
Convert UI-filter in CQL-JSON

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2542]
Standard on OGC CQL2 filtering:

https://docs.ogc.org/DRAFTS/19-079r1.html#CQL2

Most important might be this chapter: 8. Requirements Class "Simple CQL"

**Comment by AnaSasso** [comment]
@Ebubeker on this state:

<img src="https://github.com/goat-community/goat/assets/116002158/32bdd93c-066d-42dd-a553-9978ecd38943)" width=30% height=30%>


there should be a option for how to match the expressions (and, or)
I added some other comments on [figma](https://www.figma.com/file/REUqupUwDCvX6q09NQL55g/Handoff_Goat-2.0?type=design&node-id=822-6472&mode=dev)
<img src="https://github.com/goat-community/goat/assets/116002158/145d9b92-1fdc-46bf-bc82-e14b7f7991d4)" width=45% height=45%>
