### ISSUE TITLE
Adjustment of the default value of the speed slider to the routing_profile

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#262]
If "elderly" or "wheelchair" is choosen as routing profile, the default value of the speed slider in the front end should adjust. 
(default speed values for elderly and wheelchair are stored in the variable_container)

**Comment by EPajares** [comment]
I added the default_routing speed to the app_config.json for each routing_profile. 
It would be great if it possible to adjust the default speed based on this value.

**Comment by majkshkurti** [comment]
@EPajares @UJehle 
I can handle this. 
Can you send me the values for every profile. I couldn't find it in app-conf.json file.

**Comment by UJehle** [comment]
Awesome! 
Standard: 5 km/h
Elderly: 3 km/h
Wheelchair: 5 km/h
Safe-night: 5 km/h
