### ISSUE TITLE
Add data collection process for network_pt

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2620]
The purpose of this process is to download OSM and GTFS data. For the OSM data it needs to be clipped using the regions.
More details are in the repo.

The aim of this here is to be able to run and the procession should be carried out: `python manage.py --actions=collection --region=eu --datasets=network_pt`

**Comment by nihar1024** [comment]
Pull request submitted for this issue: https://github.com/goat-community/data_preparation/pull/221
