### ISSUE TITLE
Add data preparation process for network_pt

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2621]
The aim here is to upload the gtfs and osm data bundle to R5. We should be able to specify an R5 instance URL in the .env file and the authentication to the R5 instance (if running in production).

This should be executed when running:
`python manage.py --actions=preparation --region=eu --datasets=network_pt`

**Comment by nihar1024** [comment]
@EPajares Are the R5 helper functions expected to be used for other tasks? In which case I can implement them in utils.

**Comment by EPajares** [comment]
Actually I think not really as this is quite specific.
