### ISSUE TITLE
Add info buttons for Routing Types

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#266]
Show info buttons if user moves the curser over the routing types.
With information about what happens when selecting this profile (e.g. Wheelchair: only barrier-free paths are considered in the routing).

**Comment by majkshkurti** [comment]
@UJehle Should we add tooltips ? 
If so, should we activate it when user hovers when routing dropdown is open ?

**Comment by UJehle** [comment]
@majkshkurti Yeah, that sounds good. 
I would display the following texts.
For "standard": Default routing.
For "elderly": Routing with reduced walking speed. 
For "wheelchair": Routing excluding paths and points-of-interest that are not barrier-free.
For "safe-night": Routing excluding unlit paths.
