### ISSUE TITLE
Refactor collection/preparation of GTFS

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2674]

**Comment by nihar1024** [comment]
Changes submitted via PR:
https://github.com/goat-community/data_preparation/pull/229

**Comment by nihar1024** [comment]
Potential further tasks/changes:

- Study extent of trip schedule exceptions defined in `calendar_dates` for custom datasets
- Study extent of trip schedules/headways defined in `frequencies` for custom datasets
- If these are used in a significant way, make the necessary changes to our preparation script & DB queries
- Potentially "generate trips" corresponding to headways defined in `frequencies` for _stop_times_optimized_
- Don't rely on a _parent_station_ field being defined for every stop (doing so causes our benchmarking function to miss stops)

**Comment by nihar1024** [comment]
Additional changes submitted via PR:
https://github.com/goat-community/data_preparation/pull/234
