### ISSUE TITLE
Graphics for the login/page

### ISSUE THREAD

**Issue by majkshkurti** [goat-community/goat#2697]
- Login and Singup page (right side background image, without the GOAT LOGO)
![image](https://github.com/goat-community/goat/assets/32641116/78713d2a-c0a1-44ff-ab81-f58a030da525)

- Organization Create/Invite page (same layout as login/signup)
_''currently has the same background image as login/sign up page. Can be something different."_

**Comment by AnaSasso** [comment]
thanks Majk, at this week's design review I'll bring a couple of options, but this is a munich map screenshot from goat

**Comment by AnaSasso** [comment]
https://plan4better-my.sharepoint.com/:i:/g/personal/elias_pajares_plan4better_de/Eb929MgCVWxCrM89RZD7wioBeXUgcs6kqW9qejxQEWmbqg?e=xlGbdM
