### ISSUE TITLE
Graphic for No Thumbnail

### ISSUE THREAD

**Issue by majkshkurti** [goat-community/goat#2698]
- [ ] Create new project graphic. (920x680)
Currently using this one: https://assets.plan4better.de/img/goat_new_project_artwork.png
![image](https://github.com/goat-community/goat/assets/32641116/b24ff103-c6f8-44af-926a-e573bbde843e)

- [ ] Create new dataset graphic. (920x680) 
Currently using this one: https://assets.plan4better.de/img/grid_thumbnail.png
![image](https://github.com/goat-community/goat/assets/32641116/ba21d9c4-57d1-49ec-b2b4-a2220e3b1341)

**Comment by AnaSasso** [comment]
https://plan4better-my.sharepoint.com/:f:/g/personal/elias_pajares_plan4better_de/EpUre_XvduFCnSSMiE9P2i0BefRBpM7CsYoMIlNx8MIiRg?e=W2Z00y
