### ISSUE TITLE
Graphics for Emails

### ISSUE THREAD

**Issue by majkshkurti** [goat-community/goat#2699]
Emails have the following layout: 
![image](https://github.com/goat-community/goat/assets/32641116/9053c736-2395-494b-8267-4ca6bfe695d8)

The artwork for each email have to be different depending on the subject. The emails that we send are the following

**Accounts**

- [x] 1.1 Invited to organization 
- [x] 1.2 Invited to group(Team)
- [x] 1.3 Subscription Started (Trial)
- [x] 1.4 Subscription is about to end. 
- [x] 1.5 Subscription has expired. 
- [x] 1.6 Account deactivated/deleted
- [ ] 1.7 Organization deactivated/deleted

**Authentication**
_Important_

- [x] 2.1 Verify Email
- [x] 2.2 Login Error Email (content example:  A failed login attempt was detected to your account.....)
- [x] 2.3 Password Reset Email
- [x] 2.4 Password Updated Email (Your password was changed on)

_Secondary_ (Can have a generic artwork)

- [x] 3.1 Event Emails (update account, update one-time password, update profile etc)

**Comment by AnaSasso** [comment]
[HQ Illustrations](https://plan4better-my.sharepoint.com/:f:/g/personal/ana_sasso_plan4better_de/EuL9Lp4Gr6lGl9HS4U3G05kBXRMEWBPuuv7w-17NcHzzTg?e=3X7XMr)
