### ISSUE TITLE
Show pop-up info box if user chooses Heatmap-Layer without choosing POIs

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#273]
Show an error (e.g. a pop-up info box) if a user chooses an Heatmap-Layer for which it's necessary to select POIs but the user has not selected POIs so far. (Like it's done for the multi-isochrones.)
It think that would make the functionality more understandable to the user.

@majkshkurti could you implement this?

**Comment by majkshkurti** [comment]
@UJehle I merged it with #285
