### ISSUE TITLE
Add BMVI + mFund Logo

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#275]

**Comment by EPajares** [comment]
We have to add their Logos to our Footer

**Comment by EPajares** [comment]
![2000px-TU_Muenchen_Logo svg](https://user-images.githubusercontent.com/42171996/70144054-6649a380-169d-11ea-9f27-1ec4afb23ad9.png)
![BMVI_Logo](https://user-images.githubusercontent.com/42171996/70144055-6649a380-169d-11ea-8578-b2ef58948415.jpg)
![mFund](https://user-images.githubusercontent.com/42171996/70144057-66e23a00-169d-11ea-992c-f812add46607.jpg)

**Comment by EPajares** [comment]
@ivanchromjak could you handle this issue? The idea is that these logos are on the footer. They should all have almost the same size. They should be arranged as the following:

left TUM 
center Bundesminsterium
right mfund

**Comment by ivanchromjak** [comment]
@EPajares I created a pull request https://github.com/goat-community/goat/pull/296

Footer logos added https://jmp.sh/iD4MdBa

I had to remove the footer background color as two of the logos are not transparent, also I had to side the logos individually as giving them the same height would make the left and right logos dominant and the middle unreadable.

**Comment by EPajares** [comment]
Looks nice thank you! I merged with the master version of the website.
