### ISSUE TITLE
Discuss possibilities for improved structure documentation

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#277]

**Comment by EPajares** [comment]
Elaborate on solutions to improve the structure of the documentation sections

**Comment by EPajares** [comment]
@ivanchromjak could you do a little research about possible improvements or show us some best-practice from other sites.

**Comment by ivanchromjak** [comment]
@EPajares the sidebar location is perfect as it is the first thing the user sees, what we could change is to have all categories open on page load as it makes all links immediately visible without the need to click (removes friction). We have currently a small number of links in the sidebar so this would work well, if and when the number of sidebar increases too much we can apply the accordion again and on page load open the most important category.

**Comment by EPajares** [comment]
Sorry for the late response. Sounds good! Can you kindly do it?

**Comment by ivanchromjak** [comment]
@EPajares done https://github.com/goat-community/goat/pull/305
