### ISSUE TITLE
Docs: Layer Types

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#2783]
```[tasklist]
### Tasks
- [x] Draft (Irem)
- [x] Check (Elias & Ulrike)
- [x] Adjustments (Irem)
- [ ] Final Check (Elias & Ulrike)
```

**Comment by iremkapucuoglu** [comment]
Will there be an option to load raster files like png, jpeg other than wms within imagery layer? @UJehle @EPajares

**Comment by UJehle** [comment]
Thanks @iremkapucuoglu. I just had a quick look at it. I think it would help the user if we show an example (screenshot of the file in GOAT) to better understand the differences. Not sure if this is already possible now. If not, then just add a placeholder for now that we don't forget about it.
