### ISSUE TITLE
Docs: Geoanalysis - Aggregate Points

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#2814]
```[tasklist]
### Tasks
- [x] Draft (Irem)
- [x] Check (Ulrike)
- [x] Adjustments (Irem)
- [ ] Final Check & Additions (Elias & Ulrike)
```

**Comment by iremkapucuoglu** [comment]
The example image needs an update. In the current image there are null values, avoid using null

**Comment by AnaSasso** [comment]
> The example image needs an update. In the current image there are null values, avoid using null

@nihar1024 I think this has already been addressed

**Comment by nihar1024** [comment]
True, it looks fine to me.
