### ISSUE TITLE
Mark psv:yes as not walkable

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#284]
There is existing the osm-tag psv that is frequently used for bus- or tramways. At least in Munich they are generally highway=service. They are generally not walkable and often not cycleable. We could check if it makes sense to classify them as foot='no'

**Comment by EPajares** [comment]
Do you think `(tags -> 'psv' ) is not null` would also do it? I would not delete them from the DB but we could label the associated network links from the ways table with foot='no' and cycling='no'. 

The table ways and planet_osm_line share the same osm_id.

**Comment by EPajares** [comment]
You could put this classification in line 344 of the sript /data_preparation/network_modification.sql

**Comment by rafleo2008** [comment]
> 
> 
> Do you think `(tags -> 'psv' ) is not null` would also do it? I would not delete them from the DB but we could label the associated network links from the ways table with foot='no' and cycling='no'.
> 
> The table ways and planet_osm_line share the same osm_id.

Somethimes work but is not enough to cover all the cases but the tag psv is not null groups all the values of psv = 'yes' and psv = 'bus'. In terms of the tag bus = 'yes',  I've found some cases in BOG and MUC where the tag psv does not cover all the dedicated lanes (and therefore, points the need to use extra tags). The examples are shown below.

![munich](https://user-images.githubusercontent.com/58067217/84532443-890ce280-ace6-11ea-88a5-197761662960.jpg)
![Bogota](https://user-images.githubusercontent.com/58067217/84532449-8b6f3c80-ace6-11ea-98ca-5478bd98d46e.jpg)

As this code has major impact in the Bogotá Network, I think I'll implement the next code in BOG.
`SELECT * FROM planet_osm_line WHERE highway = 'service' AND (tags->'psv' IS NOT NULL OR tags->'bus' = 'yes'); `

Finally,  as you mentioned, I'll classify the roads as  foot='no'.

**Comment by EPajares** [comment]
Thanks. I see. Make sense. We need to check in the long run if there are cases where `tags -> 'bus' = 'yes'` can be walkable but I don't think this is frequently the case. There might be also other attributes like `designated` for bus: https://wiki.openstreetmap.org/wiki/Key:bus

For now this fix should help though. The query could be more performant like this:

`UPDATE ways w SET foot = 'no' 
FROM (
      SELECT osm_id 
      FROM planet_osm_line 
      WHERE highway = 'service' 
      AND (tags->'psv' IS NOT NULL OR tags->'bus' = 'yes')
)  x
WHERE  w.osm_id = x.osm_id;`

**Comment by EPajares** [comment]
@rafleo2008 can we close this issue?

**Comment by rafleo2008** [comment]
This one will be included in the next push request
