### ISSUE TITLE
Docs: Layer Style - Attribute-based styling

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#2851]

**Comment by UJehle** [comment]
TODO: 
Update the images for quantile, standard deviation, equal interval and heads and tails. Use the same color palette for all of them. Ideally, use population or grid data (Choose the one that looks better). Use white basemap.

**Comment by iremkapucuoglu** [comment]
The image for custom breaks should be added when it is online

**Comment by AnaSasso** [comment]
@iremkapucuoglu what is the dependency here?

**Comment by nihar1024** [comment]
TODO: Page is complete, only Custom Breaks (data classification method) image is pending. Awaiting the resolution of https://github.com/goat-community/goat/issues/3209

**Comment by EPajares** [comment]
@NNoemi1 maybe you can also check this one
