### ISSUE TITLE
Translate Geoserver Legend Graphic

### ISSUE THREAD

**Issue by majkshkurti** [goat-community/goat#292]
It is possible to translate the geoserver legend graphic in the SLD Styling. 
This can be useful for the front-end so the language translation could be consistent.
See [SLD Language](https://docs.geoserver.org/stable/en/user/styling/sld/language.html#sld-language) and [GetLegendGraphic Options](https://docs.geoserver.org/stable/en/user/services/wms/get_legend_graphic/index.html#getlegendgraphic)

**Comment by UJehle** [comment]
#301 I inserted the translation definitions for all the "Street Level Quality" layers. But I just could insert the right translations for some languages, for the others I put default values. Is it somehow possible to connect the Layer Styles with the POEditor, to gradually improve the translations?

**Comment by EPajares** [comment]
Mhh I guess it does not work that easy with the POEditor unfortunately. As the Geoserver styles are in a XML-Schema. So I would propose for now we translate them just directly in the file.

**Comment by EPajares** [comment]
Can we close this issue?
