### ISSUE TITLE
Add Layers regarding Cycling Quality

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#295]
For the cycling routing, additional layers could be interesting. 
I am thinking about: 

- [ ]  incline
- [x]  smoothness
- [x]  bike ranks
- [x]  road category
- [x] maxspeed
- [x] surface
- [ ] official cycle network (from custom shapefile)
- [ ] cycleway width

**Comment by EPajares** [comment]
Speed limit would also be important. Let's do the simple things first. As slope/incline might be quite hard. I think we should have layers with:

**Comment by EPajares** [comment]
I will close this now as it is already mostly implemented. The cycleway width is not possible at the moment because we don't have the data.
