### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#2969]
Collection of missing translations that I came across: 
![grafik](https://github.com/goat-community/goat/assets/49870195/60984be2-8eec-4093-b678-09da3e40eadf)

All these Tooltips:
![grafik](https://github.com/goat-community/goat/assets/49870195/616490c3-58ed-4362-9116-119c5cdee489)
![grafik](https://github.com/goat-community/goat/assets/49870195/1b843fd0-cf88-4645-b677-6e717803eaa2)
![grafik](https://github.com/goat-community/goat/assets/49870195/536bdd48-570e-499c-aebd-0bff00a71753)

Toolbox titles:
![grafik](https://github.com/goat-community/goat/assets/49870195/81a05944-53d0-4fb1-afc6-e6322fc06cca)

Parts of the isochrone flow:
![grafik](https://github.com/goat-community/goat/assets/49870195/b9af471a-93ea-4e2d-a0dd-e6a4bfe234bb)

Layer Styling:
![grafik](https://github.com/goat-community/goat/assets/49870195/fbbda387-3719-43ee-adbc-c0141746e835)
![grafik](https://github.com/goat-community/goat/assets/49870195/a05414d4-31a5-44d9-be41-d8dfa88a94a1)

**Comment by UJehle** [comment]
Further Options in Layer Tree:
![grafik](https://github.com/goat-community/goat/assets/49870195/7612df3f-a5da-4a6c-948a-3af9983fb541)

**Comment by UJehle** [comment]
Job Status:
![grafik](https://github.com/goat-community/goat/assets/49870195/ff03eee5-8535-458f-b732-ac4673780679)

**Comment by UJehle** [comment]
Layer Styling:
![grafik](https://github.com/goat-community/goat/assets/49870195/9fb2531d-fafb-4099-868a-8af70ba2aead)
![grafik](https://github.com/goat-community/goat/assets/49870195/e8d3548f-d08f-4fe8-b62d-f142019d8245)

**Comment by UJehle** [comment]
Settings:
![grafik](https://github.com/goat-community/goat/assets/49870195/71fb01ad-8875-4ae9-a1d4-2f428a085dcf)

**Comment by UJehle** [comment]
Datasets:
![grafik](https://github.com/goat-community/goat/assets/49870195/73662ec7-6c71-4d07-86ec-22ac030f97f6)

**Comment by UJehle** [comment]
Legend:
![grafik](https://github.com/goat-community/goat/assets/49870195/e6e5e0b4-6e09-40ba-931e-47f4d3beefeb)

**Comment by UJehle** [comment]
Search bar:
![grafik](https://github.com/goat-community/goat/assets/49870195/1ca3df4e-bd59-4242-9149-4e24c87625e0)
+ tooltip behind the search bar icon

**Comment by UJehle** [comment]
Basemaps:
![grafik](https://github.com/goat-community/goat/assets/49870195/394608f5-564d-49c3-8448-db42a2695ae0)
& tooltip behind the basemap icon

**Comment by UJehle** [comment]
Project name:
![grafik](https://github.com/goat-community/goat/assets/49870195/641893cf-2f29-46e7-bb4d-919fbb925197)

**Comment by EPajares** [comment]
@majkshkurti most of the keys mentioned here are still missing.

**Comment by majkshkurti** [comment]
> @majkshkurti most of the keys mentioned here are still missing.

Currently fixing this.
