### ISSUE TITLE
Add Social media icons to the top and remove search bar

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#299]
I think it would be good to remove the search bar on the top right of the site. We could add a social media icon for LinkedIN and Twitter. @ivanchromjak can you add the icons and I can add the links later.

**Comment by ivanchromjak** [comment]
@EPajares what are the linkedin and twitter URLs?

**Comment by EPajares** [comment]
You can get them from the Readme. https://github.com/goat-community/goat/blob/master/README.md

**Comment by ivanchromjak** [comment]
@EPajares done https://github.com/goat-community/goat/pull/304
