### ISSUE TITLE
Fix functions management in DB

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#3007]

**Comment by nihar1024** [comment]
`init_functions.py` mostly looks good to me.

There are a few changes we could consider making:
- Drop function only if it exists locally (this could help prevent the accidental deletion of functions not created from within goat-core)
- Some functions are defined in goat-routing, these are not recreated by the script
- `find_unapplied_dependencies()` relies on a function's actual name being consistent with the function's filename. However, this is not always the case (e.g. `fix_transmeridian_h3()`, `get_h3_neighbors()`)

**Comment by nihar1024** [comment]
Relevant changes have been submitted here:

https://github.com/goat-community/goat-core/pull/41
https://github.com/goat-community/goat-routing/pull/7
