### ISSUE TITLE
Make Docker image for Geoserver ready to receive .env variable

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#315]
The image we use at the moment still is not receiving .env variables. We have to change this for the CI/CD pipeline.

**Comment by EPajares** [comment]
@majkshkurti we may can discuss this soon.

**Comment by tareksamni** [comment]
@EPajares @majkshkurti I found a better approach for this issue:
https://github.com/goat-community/goat/pull/323/commits/4b0869468e9b2d11b36cc4f3a1da4ce5f6e96e4e

It will allow the database configs to be injected in the pipeline into a ConfigMap that will be exposed inside the docker image (on k8s) as a file

**Comment by EPajares** [comment]
@tareksamni I think I can close this one. As you resolved it with your last pull request.
