### ISSUE TITLE
Docs: Once translations are complete, verify and update links

### ISSUE THREAD

**Issue by nihar1024** [goat-community/goat#3204]
Once textual docs content has been translated, we should update links and URLs to point to the Deutsch version of websites where possible.

For eg.:
https://plan4better.de/en/goat/ --> https://plan4better.de/goat/

This should only be done for pages under the `i18n/de/docusaurus-plugin-content-docs/current` folder.

**Comment by CyrineKamoun** [comment]
https://plan4better.de/images/docs/technical_documentation/isochrone/wiki.webp this link is from the previous website. 
Can we access it to understand what image we need?
