### ISSUE TITLE
Improve "toggle visibility"

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#324]
Currently, only the isochrone shapes are hiden when "toggle visibility" is enabled by the user. I think it would make sense to also hide the street network. 
If the user only wants to hide the isochrone shapes, he can still do that by simply using the visibility sliders. 
<img width="960" alt="Screenshot" src="https://user-images.githubusercontent.com/49870195/71444992-434b6600-2716-11ea-8f7a-8de0bf38435e.PNG">
Btw. I think it would also be useful to adjust the tooltip shown for "toggle visibility", depending on if this option is enabled or disabled, as I am always confused if the crossed out eye means that the isochrones is already invisible or if it will get invisible if i press this button. By adjusing the tooltip this could be improved.
My suggestion: 
- if the visibility is **enabled** : show tooltip "hide results"
- if the visibiliy is **deactivated** : show tooltip "show results"

@EPajares just a suggestion. We can discuss it in the new year.

**Comment by EPajares** [comment]
Yes the network should definitely toogle as well. Regarding the tooltip we need to see how much additional code this means.
