### ISSUE TITLE
GOAT Client: Don't show layer attribute list for Aggregate tools when statistic method is "count"

### ISSUE THREAD

**Issue by nihar1024** [goat-community/goat#3248]
![Image](https://github.com/user-attachments/assets/5b04fe73-e57a-41b0-8c08-f8390a7f1aaa)

This can be confusing / misleading for users.

**Comment by majkshkurti** [comment]
@nihar1024 I think the goat-core requires a field for the "count" as it counts the number of non-null values. 
https://github.com/goat-community/goat-core/blob/27d9b06cdc435028f9132bbb7d7b4d6f04690363/src/core/tool.py#L132
