### ISSUE TITLE
Add the used routing profile to the "results"

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#326]
In order to comprehend which results were done with which settings, the used routing profile should be included in the result box.
I think either a small icon or a text would be good:

![Bild2](https://user-images.githubusercontent.com/49870195/71482632-fa71db00-2803-11ea-947b-b1917ebc6287.png)

**Comment by EPajares** [comment]
This is definitely needed. We need to consider that we are going to add cyclng soon. So I would suggest that we use icons for the transport mode (walking-icon, cyling-icon) and in addition we write the routing profile.

**Comment by EPajares** [comment]
Thanks Majk. I think we can close this issue.
