### ISSUE TITLE
Consider removing ol-ext extension

### ISSUE THREAD

**Issue by majkshkurti** [goat-community/goat#332]
At the moment we use the extension only for displaying the mask filter of the study area. 
We can use a geoserver WMS layer instead of the vector data. This also will improve the performance.

**Comment by EPajares** [comment]
I added a cropped layer to the DB that is using the study area. The layer is already in the db, geoserver and config. Though I still had some issue with the geoserve style it does not get the right line stroke-width.

**Comment by EPajares** [comment]
As Ol-Ext was fixed thank to the great maintainers of the lib. We can go back to ol-ext. Using the cropped layer was not a perfect solution due to geoserver loading delays.
