### ISSUE TITLE
Docs: add External data section

### ISSUE THREAD

**Issue by NNoemi1** [goat-community/goat#3349]

**Comment by nihar1024** [comment]
TODO:
- Remove vector tiles section as that hasn't been implemented yet (but keep XYZ tiles under the raster section)
- Remove the "Imageries" title and have all the subsequent text at the Rasters title level
- Add example images of spatial, non-spatial (table), and raster layers being used in GOAT
- Update text at the bottom which says "Data Types" --> "Attribute Types"

**Comment by nihar1024** [comment]
@majkshkurti will be adding additional details on the XYZ tiles once all the above mentioned changes are complete.
