### ISSUE TITLE
Polygon-Outline Stacking Problem

### ISSUE THREAD

**Issue by SmithU64** [goat-community/goat#3376]
## Steps to Reproduce

1.
2.
3.
4.

**Comment by majkshkurti** [comment]
@SmithU64 Is this related to this issue: 
https://github.com/goat-community/goat/issues/3333

**Comment by SmithU64** [comment]
@majkshkurti : 
No it is a different/new issue.
I managed to reproduce it:
1. Input Layer: POI ÖPNV Sationen 
2. Buffer with 3 steps; Union: ON, Difference: OFF
3. Styling the Output Layer with Buffers: 
    1. set color palate to "equal interval"
    2. turn on stroke color
-> Resulting in Strokes appearing on top of polygons

**Comment by SmithU64** [comment]
![Screenshot 2024-10-28 at 15 45 37](https://github.com/user-attachments/assets/07e79c79-89a7-4135-b94b-16bd988973e8)

**Comment by SmithU64** [comment]
![Screenshot 2024-10-28 at 15 47 30](https://github.com/user-attachments/assets/35b104f0-26f9-4126-87b9-0331840a686c)

**Comment by majkshkurti** [comment]
Can you confirm that "Union" was on ? The layer features don't look unified.

**Comment by SmithU64** [comment]
I tried it again and you are right "Union" is in this scenario. Sorry for the misleading information.

**Comment by majkshkurti** [comment]
np, thank you for reporting it. 
This issue I am aware and unfortunately in this case we can't solve it due to the limitation of mapbox library which treats the fill and outlines as different layers with different z-indexes. The same goes for icons too. 

https://github.com/mapbox/mapbox-gl-js/issues/3018
