### ISSUE TITLE
Tooltip Text Mistake

### ISSUE THREAD

**Issue by SmithU64** [goat-community/goat#3377]
A Typo only: The word "tooltip" is showing up in a tooltip 

## Expected Behavior
Only the explanatory text should show 

## Steps to Reproduce
In Heatmap Closest Average. When hovering over "Number of Destinations"

## Context (Environment)

![Screenshot 2024-10-28 at 16 42 53](https://github.com/user-attachments/assets/4cf86393-e3d6-40a8-965f-3f4201c4725f)

**Comment by SmithU64** [comment]
Only the Typo: "Tooltip" is included in the tooltip when hovering over "Number of Destinations" 
I seem to filling out the form incorrectly. My comments are not showing.

**Comment by majkshkurti** [comment]
Thanks. Just fixed it. 


Regarding form: 
I think you are adding it as a mardown comment: 

<\!--- In Heatmap Closest Average. When hovering over "Number of Destinations" -->

should be 

In Heatmap Closest Average. When hovering over "Number of Destinations"

I will update it
