### ISSUE TITLE
Add Mapillary imagery as layer

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#349]
Apparently it is possible to add Mapillary imagery as additional layer to applications using openlayers.

https://www.mapillary.com/developer/tiles-documentation/#openlayers
https://bl.ocks.org/oscarlorentzon/1a21ea14f9249517356d6d52afe092b5

@majkshkurti could you give it a quick try? I am curious if it would work.

**Comment by majkshkurti** [comment]
@EPajares Yeah sure. I will check this and let you know.

**Comment by EPajares** [comment]
Ok great. Thanks!

**Comment by EPajares** [comment]
This feature got a lot of interest! Now is time to go for it.

**Comment by EPajares** [comment]
Great implementation in the dev branch @majkshkurti
