### ISSUE TITLE
Stop loading when calculation was not successful and give message

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#380]
When the user is not successful with the calculation of an isochrone the loading goes forever. It should simply stop with a message like 'Sorry but here no calculation is possible.'

@majkshkurti Could you investigate on this.

**Comment by majkshkurti** [comment]
@EPajares I will try to reproduce the same error and will investigate this further. 
I am also thinking to add some extra validation, to limit the user to calculate isochrones or draw features outside the study area.

**Comment by EPajares** [comment]
Thanks. This is done.
