### ISSUE TITLE
Back to website button is hard to find on the userinterface

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#381]
Maybe need an extra button that redirect to the website?

**Comment by majkshkurti** [comment]
We can add it over the map or in the right bottom corner ? Where do you think is more appropriate.

**Comment by EPajares** [comment]
Yes I think it would be good there. @UJehle what do you think?

**Comment by UJehle** [comment]
I think in the right bottom corner could be good. Underneath the info-button maybe ? Or we replace the info-button and lead directly to the GOAT Website instead of displaying the small box?
