### ISSUE TITLE
Error when starting VM: host path is missing: ./scripts

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#397]
After fetching upstream with the development branch, currently this issue is emerging when starting the VM:

<img width="401" alt="error" src="https://user-images.githubusercontent.com/49870195/74429828-f9504800-4e5b-11ea-8fca-f00df3fb5ee5.PNG">

Manually creating the folder "scripts" in "goat" solves this issue. However, this issue can perhaps be solved from scratch.

**Comment by EPajares** [comment]
The script folder has not really a purpose on this directory right? I think we should simply remove the line that is syncing the folder in the VAGRANTFILE: https://github.com/goat-community/goat/blob/master/Vagrantfile

The line was there for some legacy reasons but is not really needed.

**Comment by UJehle** [comment]
Okay. I removed this line in commit 9b9cf64580a3b44654410e99853ab55557bfab9f (comes with the next pull request).
