### ISSUE TITLE
Order Results according to relevance

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#403]
<img width="297" alt="Unbenannt" src="https://user-images.githubusercontent.com/49870195/74674687-32691f00-51b2-11ea-842e-6180f6077960.PNG">

Order the results according to their relevance (number of this amenities found in the area). Amenities with the same number should be ordered alpabetically. 
In this case:
Population
Restaurant
Cafe
Fast Food
Bar 
Kindergarten

**Comment by EPajares** [comment]
Thanks Majk!
