### ISSUE TITLE
Scenario building: Remove red cirlce as soon as features are displayed

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#429]
<img width="352" alt="circle" src="https://user-images.githubusercontent.com/49870195/75333416-66190880-5886-11ea-86ad-dabd18627dc0.PNG">
After the features are displayed with the red dots, the red circle is not needed anymore and can be removed. This would make the map more clear, as it currently can get crowded with the scneario calculation.

**Comment by EPajares** [comment]
@majkshkurti thanks a lot for this fix. Somehow now the response from the WFS is empty when the pois are fetched.
