### ISSUE TITLE
Make it easier to change the language

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#430]
We could improve the visibility of the language changing option by showing the flag of the current language instead of the general icon:
<img width="443" alt="language_new1" src="https://user-images.githubusercontent.com/49870195/75334630-7cc05f00-5888-11ea-8f1f-0d4c9c96f199.PNG">
And open a menu when the user hovers over the flag:
<img width="419" alt="language_new2" src="https://user-images.githubusercontent.com/49870195/75334849-d45eca80-5888-11ea-938b-213728906d50.PNG">

For now it may make sense to limit on the languages with complete translations, which are German and English.

**Comment by EPajares** [comment]
Yes let's limit it to those for now. At least the spanish we can update soon.
