### ISSUE TITLE
Scenario: delete only drawn way with ESC

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#433]
<img width="668" alt="scenario_esc" src="https://user-images.githubusercontent.com/49870195/75335363-afb72280-5889-11ea-9138-50de91f271e6.PNG">
Currently, if ESC is pressed the whole scenario building includig the selected network is deleted. I think I would be better if only the drawn way (blue line) will be deleted.

**Comment by EPajares** [comment]
This is fixed
