### ISSUE TITLE
Enable to show the road network also without isochrones

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#435]
It would be nice, if the road network can also be displayed without showing the isochrones (means: isochrones deactivated, road network activated).

**Comment by EPajares** [comment]
@UJehle is this one fixe?

**Comment by UJehle** [comment]
@EPajares not yet.
@majkshkurti could you do this? 
I think it would make sense like that:
- if the "hide results" is pressed, isochrones + network shall be hidded. 
- if the isochrones are deactivated via the silders, the road network should stay visible.

**Comment by majkshkurti** [comment]
@UJehle 
Yes, i can do it. 
The road network + isochrones is hidden when user clicks the hide result (eye icon). The "eye icon" is also switched off automatically if no isochrone feature is visible, which as a consequence turns off the road network too. 
Should i leave the "show/hide result" button unchanged when user interacts with sliders, or just change the logic for the network in this case ?

**Comment by UJehle** [comment]
@majkshkurti Awesome, thanks! 
Hm, I would suggest that the "eye icon" is only switched off automatically if neither isochrones nor network are visible anymore.
