### ISSUE TITLE
Re-classification function for POIs

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#461]

**Comment by UJehle** [comment]
if cuisine e.g. "turkish", then classification as "international supermarket"

**Comment by EPajares** [comment]
@rafleo2008 could you please have a look on this? We would need a generic approach to do such classifications.

**Comment by rafleo2008** [comment]
Yes, I am analyising this source with the tag explanations

https://wiki.openstreetmap.org/wiki/Key:cuisine 

After grouping by amenity where this tag cuisine is not null, i think this tag is correlated moslty with restaurants, coffee shops and ice cream stores, next table shows the number of elements per amenity where tag cuisine is not null

![imagen](https://user-images.githubusercontent.com/58067217/79558816-12b48100-80a5-11ea-96ff-d7fd9b88f5f9.png)

Do you have any suggestion to in which amenities do we have to focus on?

**Comment by EPajares** [comment]
It should only be applied for now if the tag shop=convenience_store in the OSM-rawdata.
In our pois-table this we are labelling everythings as amenity also shops. So in the pois-table it would be amenity=convencience_store

**Comment by EPajares** [comment]
Thanks Rafael great job! I will close this now.
