### ISSUE TITLE
Edit buildings interaction

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#464]
As for the POIs and ways we need an interaction to draw/delete/edit buildings.

**Comment by majkshkurti** [comment]
@EPajares Theoretically it should work the same as with the ways if we follow the same logic. I can test it out.

**Comment by EPajares** [comment]
Ok great.

**Comment by EPajares** [comment]
The basic interaction is already implemented. So I will close this issue and rather open a new one for further building interaction.
