### ISSUE TITLE
Add new WMS/WMST Layers

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#465]
There is existing a wide range of WMS/WMST layers from public agencies. Some of the we could embed. e.g. natural reserves

**Comment by UJehle** [comment]
@majkshkurti I already started with this issue. I will maybe contact you if I need some help.

**Comment by majkshkurti** [comment]
@UJehle Ok, great. 
In case there are WMTS layers, i have to add the logic to layer.js factory file to create the layer automatically as we currently don't have WMTS.

**Comment by UJehle** [comment]
@majkshkurti okay, thanks! Currently I only have WMS layers but if it comes to WMST I will contact you.

**Comment by EPajares** [comment]
@UJehle you added the layers. I think we can close it right?
