### ISSUE TITLE
Check if it is possible to click on Isochrone marker

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#466]

**Comment by majkshkurti** [comment]
Isochrone maker is part of the same isochrone layer. Clicking on the isochrone or marker just opens the windows now. But i can distinguish between isochrone feature or marker when the user clicks. 
Should we do something more specific if user clicks on the marker ?

**Comment by UJehle** [comment]
Provide additional options when rightklick on the icon/isochrone:
- [ ] delete calculation
