### ISSUE TITLE
Show isochrone information when hovering over it

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#468]
As it sometimes can get confusing when may isochrones are calculated, It would be nice to show the most important information when hovering over an isochrone (routing profile, speed and time). 
![Isochrone_information](https://user-images.githubusercontent.com/49870195/76103990-e7814100-5fd2-11ea-9aa9-9d0d54d42eaa.png)

@majkshkurti would this be possible?

**Comment by majkshkurti** [comment]
@UJehle 
Yeah it's possible. 
The only issue that can happen here is that when multiple isochrones overlaps with each other, it can get quite messy. 
But i can try it out.

**Comment by EPajares** [comment]
We could try to show this info on right-click?

**Comment by EPajares** [comment]
@majkshkurti  and @UJehle  I think we can close this right?

**Comment by majkshkurti** [comment]
Yes, i think so. We decided to handle this on click rather then on hover.
