### ISSUE TITLE
Finalizing pois_fusion script

### ISSUE THREAD

**Issue by rafleo2008** [goat-community/goat#501]
The script creates many temporal tables, improve the script to reduce the number of temporary tables and increase performance.

Check all the temporal tables are correctly deleted in the end.

**Comment by rafleo2008** [comment]
The script can be found here 

app\database\data_preparation\SQL\pois_fusion.sql

**Comment by EPajares** [comment]
I tested the script. I think we can close this issue and open new issues for further data refinement and fusion tasks.
