### ISSUE TITLE
Change colour picker for isochrones

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#503]
Provide a pallet of colours with differnt shades, like in word: 
![colour_picker](https://user-images.githubusercontent.com/49870195/78171007-14026e80-7454-11ea-83c0-27e4e7be2cc3.png)

**Comment by EPajares** [comment]
@UJehle could you define max. 10 color ranges? You could check the color ranges that are in QGIS.

**Comment by UJehle** [comment]
@EPajares sure. We need it with hashtag-code right?

**Comment by EPajares** [comment]
I think rgba-style would be a bit easier to handle.

**Comment by UJehle** [comment]
I would suppose the following colors:
![color palette3](https://user-images.githubusercontent.com/49870195/79697149-5bc12c80-8281-11ea-9cad-85df3f075fbd.png)


Color Codes: 
1.  R:254, G:202, B:232
2.  R:254, G:144, B:207
3.  R:239, G:002, B:140
4.  R:179, G:001, B:103
5.  R:125, G:001, B:072
6.  R:251, G:188, B:175
7.  R:247, G:122, B:099
8.  R:234, G:049, B:012
9.  R:186, G:039, B:010
10. R:116, G:024, B:006
11. R:255, G:200, B:142
12. R:255, G:171, B:079
13. R:238, G:125, B:000
14. R:192, G:101, B:000
15. R:126, G:066, B:000
16. R:254, G:229, B:168
17. R:253, G:216, B:123
18. R:252, G:193, B:044
19. R:231, G:166, B:003
20. R:193, G:139, B:003
21. R:232, G:240, B:182
22. R:202, G:220, B:094
23. R:182, G:206, B:044
24. R:143, G:161, B:035
25. R:104, G:117, B:025
26. R:220, G:241, B:211
27. R:173, G:223, B:153
28. R:097, G:190, B:060
29. R:071, G:140, B:044
30. R:054, G:105, B:033
31. R:201, G:237, B:236
32. R:144, G:216, B:214
33. R:066, G:190, B:187
34. R:052, G:152, B:150
35. R:039, G:111, B:109
36. R:197, G:218, B:237
37. R:126, G:172, B:214
38. R:066, G:133, B:194
39. R:042, G:105, B:162 
40. R:032, G:081, B:126
41. R:255, G:255, B:255
42. R:207, G:207, B:207
43. R:159, G:159, B:159
44. R:090, G:090, B:090
45. R:000, G:000, B:000
