### ISSUE TITLE
Kubernetes improve resources management for DB and Geoserver

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#514]
I feel especially Geoserver and the database consume too many resources. It happens that the deployments stop working because of this. We should limit the resources that can be consumed in the configurations files. 

Furthermore we should evaluate to top-up the used plan.

**Comment by EPajares** [comment]
@alfredopalhares

**Comment by alfredopalhares** [comment]
That can be done at the deployment level, let me check how things are running actually.
