### ISSUE TITLE
Check geoserver image

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#515]
We are currently using this docker image: https://hub.docker.com/r/oscarfonts/geoserver/dockerfile

We should double check if the Tomcat settings are appropriate for our deloyments. It could be that there is the need to increase the heap-memory here. Some further recommendations to improve performance are documented here:

https://docs.geoserver.org/latest/en/user/production/index.html

**Comment by EPajares** [comment]
@alfredopalhares

**Comment by alfredopalhares** [comment]
Do you want to build image based on that one, I see that we can increase the java heap size on a very simplistic way, yet it does not seem to check multiple flags.

**Comment by EPajares** [comment]
Yes I would say we should build on this image. Right it would be quite simple to pass the java heap size as additional variable. I guess we could do so in a fork. These changes might be relevant also for the maintainer of the image so we could check to do a PR on his repo after the changes.

**Comment by EPajares** [comment]
@alfredopalhares we would like to use this version of Geoserver: 2.16.2

**Comment by alfredopalhares** [comment]
@EPajares  can you test the [image here](https://hub.docker.com/repository/docker/goatcommunity/geoserver)

**Comment by EPajares** [comment]
Thanks Alfredo! The image is working and the container is starting. Though I am having an issue with the data that should be mounted to the container. We are currently mounting this folder: https://github.com/goat-community/goat/tree/development/app/geoserver/geoserver_data

**Comment by EPajares** [comment]
It seems to be a permission error. Basically when you start the service on localhost/geoserver and login with the credentials you should see our layers being loaded as on the following screenshot

![grafik](https://user-images.githubusercontent.com/42171996/79860316-ba49f000-83d2-11ea-89bb-b1a07cebe0dc.png)

**Comment by alfredopalhares** [comment]
I see, its the file that permission that should have the tomcat UID, I add some modifications, can you retest again please ?

**Comment by EPajares** [comment]
We fiex a type and it works now. I will do some further performance test tomorrow . But everything seems to be fine!

**Comment by alfredopalhares** [comment]
Awesome!

**Comment by EPajares** [comment]
I tested it! Everything is fine. I think we can close this issue.
