### ISSUE TITLE
Shapefile Export of isochrone is currently not working

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#516]
I think we are currently not having the layers in geoserver to provide shapefile download. We could discuss if we would need it all?

**Comment by EPajares** [comment]
@majkshkurti @UJehle

**Comment by EPajares** [comment]
@majkshkurti could you have a look? I think there is no call done to geoserver. There is the layer download_isochrones on geoserver that is receiving the objectid to return the isochrones.

**Comment by majkshkurti** [comment]
@EPajares Sure, i will fix this one.
