### ISSUE TITLE
Video heatmap auto-refresh

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#533]

**Comment by EPajares** [comment]
https://vimeo.com/411721219

I have recorded a new video and added English + German subtitles. @UJehle Feedback welcome :)

**Comment by UJehle** [comment]
@EPajares 
Nice, I like it a lot! The subtitles are really adding value to the videos. 
Just one little thing: 
At minute 1:55 it's written "Now let's check how the balance walkability and population has changed". Maybe it would be more understandable if we write "Now let's check how the balance of walking accessibility to bikesharing stations and population has changed".

**Comment by EPajares** [comment]
Thanks! I have changed it accordingly.
