### ISSUE TITLE
Add a "mapping mode"

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#537]
To make it easier to find missing data, we could implement a "mapping mode". If the user clicks on the OSM icon on the right bottom, a task menu opens. A good task for the beginning would be: mapping of missing opening hours.

By clicking on this task, all POIs without opening hours are displayed. Maybe same for all amenities where the "checkopen" funktion returns an error. 

Therefore we should enable the "edit in OSM button" again.
![task-opening-hours](https://user-images.githubusercontent.com/49870195/79232510-e2cc6a00-7e67-11ea-8920-9799099cb1bd.png)

**Comment by EPajares** [comment]
With the Overpass-Turbo API we could frequently check for changes in our study area and update the DB accordingly. I will start crafting a Python scripts that does run a request similiar to this one:
[diff:"2020-04-14T13:00:00Z"];
node
[amenity=ice_cream]
({{bbox}});
out meta;

We could then use this data to update the databases. We would need a schedule cron job in the DB container for running this frequently.

**Comment by EPajares** [comment]
There is luckily a 3rd party python lib for using the overpass api. I will use it and see how good it works.

**Comment by EPajares** [comment]
The script is finished and ready for testing. I will close this issue as it is very broad. And still many sub-tasks need to be done. New issues will be opened for that.
