### ISSUE TITLE
Refactor pois.sql

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#542]
After the re-classification function is finished, we have to refactor the pois.sql script. Large parts of the code could be simplified and replaced. We however should test the script in at least three areas. I would propose:

- Munich
- Fürstenfeldbruck
- Freising

This is linked to issue: #461

**Comment by EPajares** [comment]
@rafleo2008 please also handle this issue once finished with the re-classification function!

**Comment by rafleo2008** [comment]
Got It, I will work on this
