### ISSUE TITLE
Create layer custom landuse and landuse_osm

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#544]
We would need a WMS-layer for this. We should check for appropriate colors while considering common color for certain landuse types. 

It might be worth thinking about adding further landuse categories from ATKIS as currently we only use the build up area.

**Comment by EPajares** [comment]
Great! I am testing this now. And in principle everything fine. The landuse_osm layer though has severe performance issues when loading the layer for whole Munich. I guess it is because of the style. Geoserver just needs to long to render it with the conditions. I guess it will be more performant if we handle this in sql. We could do it sql-view and but a condition case CASE WHEN ... to define the right attribute.

**Comment by UJehle** [comment]
Yeah, the style is quite complexe. I will try to improve it.
