### ISSUE TITLE
Munich version: add additional layers

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#552]
Check which external WMS layers are available for Munich. 
Interesting could be e.g.:

- [x]  Bike counting stations ("Raddauerzählstellen") from City of Munich
- [x]  Street Tree Layer (https://land.copernicus.eu/local/urban-atlas/street-tree-layer-stl) or Baum-Cloud (https://baumcloud.org/#/)
- [x]  DGM or mapbox shading layer (maybe more interesting for other cities)

**Comment by EPajares** [comment]
It would be very interesting to add the data for the modal split in the Munich - Districts that we have from the MiD study.

**Comment by UJehle** [comment]
I created a first draft of a Mapbox hillshade layer: https://api.mapbox.com/styles/v1/ujehle/ckdkassqr0yz81ip85m70y3lp.html?fresh=true&title=copy&access_token=pk.eyJ1IjoidWplaGxlIiwiYSI6ImNrZGthZzVtNzBtdWMydG50ZGc1a3QzY3QifQ.yrsuVtwMM4JlhizlchvoEQ 
@majkshkurti do you know how to implement this kind of layer?

**Comment by UJehle** [comment]
Instead of a mapbox hillshape layer we could also use Opentopomap (https://opentopomap.org/#map=13/47.93038/11.66130) of OSM. Maybe this one is easier to implement. 

In addition, the opencyclemap (http://www.opencyclemap.org/) could be helpful.
