### ISSUE TITLE
Scenario isochrone smaller than standard?

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#566]
I builded a new bridge and the scenario isochrone is always smaller than the default one (tried it several times). 
Default calculation:
![default](https://user-images.githubusercontent.com/49870195/80596805-3d002a00-8a27-11ea-8484-35934a37b567.png)

Scenario:
![scenario](https://user-images.githubusercontent.com/49870195/80596846-4db0a000-8a27-11ea-86f9-e08de55cece0.png)

How can that be?

**Comment by EPajares** [comment]
Basically this is related to the fact that we have not yet customized the scenario building for wheelchair. I have done so in the latest changes that are now in the devlopment branch. It should work now. But @UJehle please test under development.open-accessibility.org

**Comment by UJehle** [comment]
@EPajares Awesome, looks good!
