### ISSUE TITLE
Printing: Walkability heatmap is not visualized correctly

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#567]
<img width="581" alt="print_walkability" src="https://user-images.githubusercontent.com/49870195/80601721-7720fa00-8a2e-11ea-8bcb-de43f7563ce3.PNG">

**Comment by EPajares** [comment]
![goat_print_2020-5-1_21-29-13](https://user-images.githubusercontent.com/42171996/80835335-d596d580-8bf2-11ea-9c57-2732f77e689c.png)

Could you check again. This is from the current deployed development version.

**Comment by majkshkurti** [comment]
@EPajares It happens when no pois is selected for the heatmap.
I can just turn off the layer or will not send it for print.
