### ISSUE TITLE
Printing: preview window is not in line with the actual printed section

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#568]
shown printing preview:
<img width="741" alt="printing_window" src="https://user-images.githubusercontent.com/49870195/80612914-e00f6e80-8a3c-11ea-9fcf-0cb482ec78ab.PNG">

actual printed map:
<img width="586" alt="printing_output" src="https://user-images.githubusercontent.com/49870195/80613084-177e1b00-8a3d-11ea-8694-002e5f4d8f02.PNG">

**Comment by majkshkurti** [comment]
@UJehle Are you getting this from the deployed version ?

**Comment by UJehle** [comment]
@majkshkurti for the development and ffb version
