### ISSUE TITLE
Add OSM-Mapping descriptions in mapping mode

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#623]

**Comment by EPajares** [comment]
It would be good to increase a bit the size of the pop-up window, when mapping mode is launched.

**Comment by UJehle** [comment]
@EPajares I tried out to add transparency for the building-style but this made the objects hardly visible

**Comment by EPajares** [comment]
I think we can keep it this way. Thanks for all your effors @UJehle and @majkshkurti
