### ISSUE TITLE
Multiple amenities in a single POI point

### ISSUE THREAD

**Issue by rafleo2008** [goat-community/goat#633]
There is a possibility of having more than one amenity in a specific geographic point (like sports complex entry points/shopping mall doors) that groups different amenities. But, It is necessary to avoid to duplicate points. Therefore, a solution is needed.

One first approach is to group different amenities in a new array type column, but there are some issues when the new array type amenity column is implemented. In the score calculations, for example, is possible to match the amenity with a category, but it is not possible to get a double score when we have double matches. (like in thematic_data_sum). And the function will calculate only one value, even though when there are more values in the arrays.

A second approach could be to create an "unnest function" only for accessibility calculations and create "temporal points" only for the calculation process, 
I am looking for a suitable approach.

**Comment by rafleo2008** [comment]
Update: 
Considering that we accept the duplicated points with one single amenity each(and same but duplicated geometry), one solution could be to "displace" the elements a little bit to manage to show both in the map, even with an overlap. 

I did some testings with primary and secondary schools. First, I counted how many points are overlapped comparing geometries, and then assign a number to them. After that, according to that number, define a displacement in one specific direction, adding or subtracting 10 meters (used in the example) to each coordinate. This is better explained with this figure:
![imagen](https://user-images.githubusercontent.com/58067217/91432054-7aec4e00-e861-11ea-8356-c81b8b1852b9.png)

here, the original point is modified according to the assigned number.

In the real-life example,there is the case of the Grund und Mittelschule an der  Toni-Pfülf Strasse. Here, the original points (blue) has been displaced to the positions 1 and 2.

![imagen](https://user-images.githubusercontent.com/58067217/91432388-f2ba7880-e861-11ea-8d59-9b8acf89d861.png)


Now I am dealing with the coordinates and the change of the geometry back in pois.

**Comment by EPajares** [comment]
This seems to be a good approach. I think we should make sure that the new geometries are still intersecting the building. Currently for the POIs derived from polygons we simply take the centroid. Usually this is fine but the issue comes with buildings that have holes. Maybe we could also make sure here to snap to the closest part of the polygon.

**Comment by rafleo2008** [comment]
According to our last meeting, the approach has been changed to handle angles that vary according to the number of repeated entities. This new approach has been implemented and tested and will be added in the next PR.

**Comment by UJehle** [comment]
Hey @rafleo2008 @EPajares ,
I just checked the PR. I think it looks good!
