### ISSUE TITLE
Name scenarios

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#703]
The user should have the opportunity to name scenarios (e.g. Scenario 1, Scenario 2, ... ), to switch dynamically between the scenarios and to combine them.

**Comment by EPajares** [comment]
- [ ] Create columns for scenario id in the relevant tables
- [ ] Develop work-flow for scenario labeling in the client
- [ ] Adjust scenario calculation in all relevant db-functions
- [ ] Implement client part
- [ ] Adjust variable in Geoserver + NodeJS

**Comment by EPajares** [comment]
Major refactoring paving the implementation of this was done. Especially the heatmap calculation is almost ready for this. However, there are still some adjustment that need to be done. And of course a lot of testing.

**Comment by EPajares** [comment]
This almost finished. But we need to do some cleaning and testing afterwards. Data import and export is still pending.

**Comment by EPajares** [comment]
Finished. But we still need to work on import/export for scenarios. But I will open a new issue for this.
