### ISSUE TITLE
missing fitness centers

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#709]
some fitness centers are missing in GOAT, e.g.:
https://www.openstreetmap.org/edit?editor=id&way=130534675#map=18/48.21971/11.56075
(Fitness Point in Hasenbergl)

I guess this is due to a typo in the goat_config.yaml file (line 167). In OSM, the tag is "fitness_centre" not "fitness_center".

@EPajares @rafleo2008

**Comment by EPajares** [comment]
I found the issue there are missing gyms that are mapped as polygons. We can easily add them as well.
