### ISSUE TITLE
Scenario: Improve visualization of deleted objects

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#720]
TO BE DISCUSSED. 
One option would be to show the deleted objects in light red (maybe half transparent) with a dashed line / filling.

**Comment by EPajares** [comment]
Not sure about that... Because it could get a bit messy if the user is drawing a new feature on top of it.

**Comment by UJehle** [comment]
Yeah, it's maybe not the perfect solution. 
The tricky challenge is that the base map always shows the base-scenario, including the deleted features, which confuses the user. Thus, some kind of overlay that indicates that the feature is gone could be helpful. But it's hard to find a usability compromise here.
