### ISSUE TITLE
Scenario: POIs are underneath the buildings

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#737]
When drawing buildings, they are covering the POIs. We should adjust the zIndex of the layers.
![buildings](https://user-images.githubusercontent.com/49870195/89762604-0c815f00-daf1-11ea-804f-8a9b4c766d17.JPG)

**Comment by EPajares** [comment]
The change of the zIndex is causing some trouble when fetching the POIs for scenario building. A real solutions needs to be found.
