### ISSUE TITLE
Experiment with new Mapillary API

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#775]
Mapillary has released a new API that basically provides there well know feature (road segmentation, object detection etc.) to third parties for free: https://blog.mapillary.com/update/2020/08/28/map-data-mapillary-api.html

I believe it is a very promising data source in the future.

**Comment by UJehle** [comment]
Santiago has tried the JOSM plugin of the Mapillary API and is currently summarizing his experiences in a blog post.

**Comment by EPajares** [comment]
We are working on this here: https://github.com/goat-community/mapillary-api
