### ISSUE TITLE
Add offcial reference for citing GOAT

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#786]
I think it would be beneficial to provide the users an official way how they can reference GOAT when being used in reports etc...

**Comment by EPajares** [comment]
Better reference data in the application and revive ABOUT section

**Comment by UJehle** [comment]
Could look like this:
![about](https://user-images.githubusercontent.com/49870195/100232225-5ec38000-2f28-11eb-9ffb-baf4f254347f.png)

To Do:

- [ ] agree on an icon to use for the "about" button (in "i" could be good but we already have one for the attributions)
- [ ] create the infobox 
- [ ] adjust the config-file to include the date and an extra attribute that defines which layers are shown in the about box
- [ ] add data (e.g. Census) which is not yet included in the config-file as extra object
- [ ] define how to cite GOAT (check other tools) @UJehle 

@majkshkurti @EPajares

**Comment by UJehle** [comment]
**TUM Zitierleitfaden:** 

Kann das Programm im Internet runtergeladen werden, nennen Sie statt Ort und Firma die URL, unter der das Programm verfügbar ist: [Name der Software] [(Versionsnummer)] [[Computer software]]. Retrieved from [URL]

_example:_
Camtasia Studio (Version 8.6.0) [Computer software]. Retrieved from https://www.techsmith.de/store/camtasia

**Comment by UJehle** [comment]
@majkshkurti is it possible to automatically set the date of the OSM data?

**Comment by majkshkurti** [comment]
@UJehle Yes but for that we should store some metadata in the database when the setup is done. Then I can fetch it in the client.

**Comment by EPajares** [comment]
Yes I can save it in the database and then we can create an endpoint for this.

**Comment by UJehle** [comment]
Great!

**Comment by EPajares** [comment]
I forgot that I have already added the date of the OSM data to the variable container. Once we have setup the new API we can easily create an endpoint.
