### ISSUE TITLE
Mapping Mode: Add link to JOSM and OSM

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#787]
It would be nice to also have a link to OSM and JOSM.
<img width="960" alt="edit_with_osm" src="https://user-images.githubusercontent.com/49870195/94010209-e9132a80-fda5-11ea-9a03-16b200eb1af1.PNG">

hint by Rainer:
in der Box, die sich öffnet, wenn man einen POI in der Ansicht "POIs - Öffungszeiten", gibt es "in OSM bearbeiten", was zum iD-Editor verlinkt; da wäre es toll, wenn es zusätzlich "in OSM anzeigen" und "in OSM bearbeiten (JOSM) gäbe. In OSM anzeigen deswegen, weil POIs eine Menge andere Attribute haben, die man ggf. auch ergänzen kann (wheelchair, website, cuisine, ...) und so kann man sich vorher orientieren, wie vollständig ein POI erfaßt ist. Und JOSM für die Nicht-iD-Affinen. Als Beispiel, wie Toni es in [PTNA](https://ptna.openstreetmap.de/results/DE/BY/DE-BY-MVV-Analysis.html#A2.5.4) gelöst hat. Beispiel [Gasthaus zur Post](http://127.0.0.1:8111/load_object?new_layer=false&objects=n369485141). new_layer=false sollte gut sein, so kann man mehrere Objekte selektieren und in derselben Ebene bearbeiten. Doku zu JOSM Remote Control im [Wiki](https://josm.openstreetmap.de/wiki/Help/RemoteControlCommands) und [JOSM remote control commands](https://josm.openstreetmap.de/wiki/Help/RemoteControlCommands).

**Comment by UJehle** [comment]
In addition, it could be useful to download all the Mapping Challenges shown in the bounding box and open them in JOSM.

**Comment by EPajares** [comment]
Yeah indeed this would be a nice feature. I think especially exporting all challenges for JSOM could help to improve efficiency when mapping. Though we will need some serve-side code for creating the OSM-file that can be loaded to JOSM.
