### ISSUE TITLE
Mapillary images: avoid jumping to a random imagery sequence

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#794]
When enabling the Mapillary images, the display window moves to a random (always the same) imagery sequence. It would be more user-friendly to show an imagery sequence in the currently displayed window.

**Comment by EPajares** [comment]
@majkshkurti do you think the Mapillary API can return on image from the current BBOX?

**Comment by EPajares** [comment]
Great! Thanks Majk for the instant fix. It is much better now.
