### ISSUE TITLE
Nursery in Puch only appears when selecting the wheelchair mode

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#833]
![puch](https://user-images.githubusercontent.com/49870195/96607996-34631f00-12f9-11eb-8e60-b2c91fab4bb5.png)

**Comment by UJehle** [comment]
Same for the Kindergarten "Die Feldmäuse" in FFB.

**Comment by EPajares** [comment]
I cannot really reproduce this. Is there really a nursery in Puch?

I found some smaller issue in the data for this nursery: https://www.stiftung-kinderhilfe.de/einrichtungen/3-bis-7-jaehrige-kinder/integratives-kinderhaus-regenbogenland-in-fuerstenfeldbruck.html

**Comment by UJehle** [comment]
I just tried it again in the live FFB version, the issue seems to be fixed.
