### ISSUE TITLE
Disable old accident layers

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#850]
Since we now have the 2 aggregated accident layers, we could disable the old wms layers.
<img width="271" alt="unfälle" src="https://user-images.githubusercontent.com/49870195/97174422-5eea2780-1792-11eb-96a0-4ab0b5c3dde2.PNG">

**Comment by EPajares** [comment]
But aren't they different? Because some the previous ones are lines and the new ones points?

**Comment by UJehle** [comment]
Yeah, it's a different visualization but the same data. The lines are a WMS view from the Statistikamt, which is only available for the different years and not in aggregated form. That's why I downloaded all the data from 2016-2019 and merged them. As we don't have the lines that they are using for the visualization of the segments, we can only show them as points. But we could improve the style and try to have a heatmap, which is more similar to the WMS view. 
I mean, we could also leave the old layers there but the user may be confused why there are several layers with the same name.

**Comment by EPajares** [comment]
I agree the user could be confused... I am not sure though. I like the line visualization more then a heatmap. So maybe we could think about keeping them but rename the layer name. So we can tell a difference.

**Comment by UJehle** [comment]
Ya, that's a good solution. 
Maybe: 
- "Accident points (2016-2019)" (for the point layer)
- "Accident frequency (year)" (for the line layer)
