### ISSUE TITLE
Adjust user interface to screen size

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#861]
Would it be possible to adjust the user interface to the screen size?
With small screens, the left and right menu are quite big and the remaining map in the middle quite small.

![grafik](https://user-images.githubusercontent.com/49870195/98397904-60540380-2060-11eb-8b2f-7e696b652a63.png)

**Comment by EPajares** [comment]
As discussed with @majkshkurti this is quite hard as we could adjust it to the screen sizes but some of the HTML-Features would then not fit e.g. the tables of the calculations. This can be only solved by develop it as a responsive application which is currently definitely out of scope.

**Comment by UJehle** [comment]
Okay. Then this was maybe just an overambitious wish.
