### ISSUE TITLE
Tbd: Glossar on Website

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#862]
On one of our Workshops, we got the feedback that a glossar with all used wordings/definitions may be helpful.
Could be added to the help-section of the website. 

In my opinion, this could indeed be helpful, especially for persons that are new to GOAT (and may also help to make the website more "visible" on the web, e.g. if some people are searching for a definition they could be lead to our website).

**Comment by UJehle** [comment]
@iremkapucuoglu is this the glossary issue you are working on at the moment or is it a duplicate?

**Comment by iremkapucuoglu** [comment]
I think this issue is the same with one that I am working on issue #2045
