### ISSUE TITLE
Rename "walkability-population-index"

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#869]
"Walkability-Population-Index" sounds bulky and constant (statement from on of our workshop participant). 

Some ideas on how we could name the layer: 
- "Population-Accessibility-Comparision" (deutsch: "Bevölkerungs-Erreichbarkeits-Vergleich")
- "Accessibility-Density-Comparision" (deutsch: "Erreichbarkeits-Dichte-Vergleich")
- "Supply-Demand-Comparision" (deutsch: "Angebot-Nachfrage-Vergleich") --> only valid as soon as we have the workplaces included

Maybe it is even better understandable if we not try to build a new word:
- "Comparison of population density and accessibility"

**Comment by EPajares** [comment]
The issue in general is with the term "walkability" also for our other heatmap. Some things that we could consider is the current discussion around the 15-minutes-city. Basically our current walkability heatmap is more or less such an indicator. We could also call it "Local accessibility". Accordingly it would the "Comparison local accessibility and population density"?

**Comment by UJehle** [comment]
"Local accessibility" for the walkability heatmap is good! As long as this heatmap is only available for the mode walking, we could also call it "walking accessibility". 

I like "Comparison local accessibility and population density". Explains quite good what the maps shows.

When discussing about renaming the heatmaps.. what do you think of the name "connectivity" instead of "area isochrone"?

**Comment by EPajares** [comment]
Yeah I think as it could be that we have the heatmap soon for cycling and maybe wheelchair it could make sense calling it something more generic. Scientifically "Gravity-based accessibility" would make sense but besides researchers nobody going to understand it. It could also just be "Accessibility heatmap".
