### ISSUE TITLE
Accessibility to water areas (and grass areas without path intersection)

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#871]
To calculate the accessibility to water areas is quite a challenge, as there is no intersection between the area and paths which could be defined as entrance points (the same is also true for some grass areas). Thus, we have to find a new way to define the entrance points. 

Idea: 
- create a buffer around the water area (we have to test which buffer size is the best)
- intersect the buffer with the surrounding paths 
- as generating "access points" does not make sense for this use case I would suggest to create "access links". Means, as soon as the routing reaches one of those links, the water area is considered accessible.
![Bild18](https://user-images.githubusercontent.com/49870195/99074081-69d8f080-25b7-11eb-9693-118997012da8.png)

For grass areas, we could use the same methodology but maybe a smaller buffer size.

**Comment by UJehle** [comment]
@rafleo2008 When you are finished with #547 you could try to continue with this issue.

**Comment by EPajares** [comment]
I am not very sure about this one. I think we should not solve this in the data preparation but rather in the accessibility calculation. It is computationally cheap to just intersect the isochrone with the buffer of the lake or park. We though also have to consider that we do need the calculation also for the heatmap. For this we need a point intersection of the buffer and the reached network. This is feasible though.
