### ISSUE TITLE
Adjust available POI categories for the Mapping Mode

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#873]
We once limited the POI categories available for the Mapping Mode, somehow in the current online version this is not included anymore. E.g. it does not make sense to map opening hours for recycling stations or tram stops. 
Is it possible to fix this before the mapping party next wednesday?
![grafik](https://user-images.githubusercontent.com/49870195/99076889-2634b580-25bc-11eb-8944-722cdb8e1e17.png)

**Comment by EPajares** [comment]
@majkshkurti I forgot if it is already possible to exclude certain POIs from being listed here in the mapping mode?

**Comment by majkshkurti** [comment]
@EPajares @UJehle 
Yes, it is possible. 
We had it working for the routing time filters as well but now it seems that there is a problem. Something should have changed. 
I will investigate and try to fix this today.
