### ISSUE TITLE
Check Walkability heatmap (biksharing, Pasing)

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#874]
Here seems to be an error.
![grafik](https://user-images.githubusercontent.com/49870195/99156165-0e922580-26bf-11eb-9681-fcc43de6c39e.png)

**Comment by EPajares** [comment]
I will check that out.

**Comment by EPajares** [comment]
This is fixed in the commit. There was an issue with NULL values in the classification. It should work with the lastest code.
