### ISSUE TITLE
Population Heatmap - Comparison standard scenario

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#875]
Is the comparison view of the population heatmap already working? 
I am just wondering why there is no population plus in the area marked with blue.
![grafik](https://user-images.githubusercontent.com/49870195/99156668-05a35300-26c3-11eb-922b-ddae4220a0b0.png)

**Comment by EPajares** [comment]
I will check that out.

**Comment by EPajares** [comment]
![grafik](https://user-images.githubusercontent.com/42171996/99186054-eef60e00-274d-11eb-8897-724b06b0e7ef.png)

**Comment by EPajares** [comment]
Locally I could not reproduce it.
