### ISSUE TITLE
Data issue network at Tram station Riedenburgerstraße

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#877]
![grafik](https://user-images.githubusercontent.com/42171996/99181628-eee71580-272f-11eb-9c3a-fe57b28ae460.png)

**Comment by EPajares** [comment]
It is mapped use_sidepath but there are no separate sidepaths drawn. Shall we just remove the attribute?

**Comment by UJehle** [comment]
Puh, the sidewalks there are quite a mess. I just tried to fix it.

**Comment by EPajares** [comment]
Ok great! Thank you :)
