### ISSUE TITLE
Documentation Multi-Isochrones

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#888]
We should have a technical documentation on the Multi-Isochrones to make them better understandable.
- how the starting points are derived
- ...

**Comment by UJehle** [comment]
Hi @dilaann, I just found this issue that I created some time ago. We forgot about it for quite a while. But if you have time in the upcoming weeks, could you make a draft on this one? It can be quite short. Just a short explanation of what multi-isochrones are (the same like isochrones, but starting from the POIs). Maybe include a graphic that visualizes this (showing the POIs as starting points and the multi-isochrones around them). If you need some technical input, you could ask @EPajares and @majkshkurti.

**Comment by dilaann** [comment]
Hello, [here](https://github.com/goat-community/goat/issues/1717) I defined the difference between single and multi-isochrone with a brief sentence and created a PR. Would it be enough for this issue or should we add more detail?
Thanks.

**Comment by UJehle** [comment]
Hi @dilaann, thanks for the PR! 
It's already helpful to have a short explanation of this in the tutorials. 
My initial idea was actually to have a "docs" section (https://plan4better.de/docs/alphashape/). It doesn't has to be as long as the one for the isochrone, but could shortly explain how the multi-isochrone calculation technically works.

**Comment by UJehle** [comment]
Rough content: 
- Selected POIs are used as starting points
- Isochrones are calculated from all the POIs and merged to be one big polygon (if they are intersecting each other) 
- The catchment areas are intersected with the population data 
- The results show the percentage of residents within certain districts that have access to the chosen POIs

We can link the "isochrone docs" page, so there is no need to repeat the content that is already in there but basically explain how the isochrone functionality is used to compute multi-isochrones. 
I would also recommend adding some screenshots and graphics (they are also good for SEO! :))

**Comment by iremkapucuoglu** [comment]
I add the task list here

- [ ] Create draft (İrem)
- [ ] Check (Ulrike)
- [ ] Finalize the content (İrem)
- [ ] Final check (Ulrike)
- [ ] Bring it on website (İrem or Ulrike :))

**Comment by UJehle** [comment]
Thanks @iremkapucuoglu ! This looks good. The changes will be online with the next website update.
