### ISSUE TITLE
Provide the option to add own POI categories

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#913]
It would be nice for the user to add own POIs for a new category, which is not yet included in GOAT. 
E.g. access to cargo bike sharing stations. 

Could be done by adding a new POI category "Others" which can be used by the user to include own POIS via the scenario. 
But I think this is not the best option, as this may also confuse some users. 
Maybe we wait with this feature until we have the user login.

**Comment by UJehle** [comment]
This request was also raised by the city of Freiburg.

**Comment by UJehle** [comment]
I think the best would be if we (with the user login) provide the option to add a new POI category, give it a name, upload data as shapefile and upload an icon.

**Comment by EPajares** [comment]
This is implemented in the new version
