### ISSUE TITLE
Optimize routing network

### ISSUE THREAD

**Issue by EPajares** [goat-community/goat#93]
Currently the routing network is not optimized neither for performance nor for accuracy. There are two main issues. If the links are very long the number of vertices is also very low, accordingly the accuracy can be affected. 

Second especially at areas with a dense network it happens that the network is split into too many small pieces which affects performance significantly. Links that have identical attributes and are smaller than 10 meters accordingly can be merged. 

- [x] Split long links (first trial max. 500m)
- [ ] Merge unnecessary splited ways (max. 10 meters)
- [ ] Experiment with removing links for car only

**Comment by EPajares** [comment]
![unnecessarily_split](https://user-images.githubusercontent.com/42171996/59827263-80ced100-9338-11e9-951a-b28bd41d1aee.png)

**Comment by EmnaBH** [comment]
Completed task:  splitting long links (max. 300 m) that don't exclude:

-  class_id_walking 

-  categorie_foot

**Comment by EPajares** [comment]
Great! I can review and discuss the following steps next week with you.

**Comment by EPajares** [comment]
I did some experiments with removing death_ends from the routing network. It could significantly boost the performance but further testing and refactoring has to be done.
