### ISSUE TITLE
Create a REST Api  for CRUD operations on layers. 

### ISSUE THREAD

**Issue by majkshkurti** [goat-community/goat#944]
The feature edit should be handled in a python custom endpoint that is able to update the tables in a similar way the geoserver WFS-T is working.

**Comment by EPajares** [comment]
#CRUD operations for reading, insert, update and delete from modifiable table

#Sample body read
{"mode":"read","table_name":"pois","scenario_id":"1"} 
#Sample body insert
{"insert":"read","table_name":"pois","scenario_id":"1","name":"Test","geom":"ST_POINT(11.4543,48.1232)"} 
#Sample body update
{"mode":"update","table_name":"pois","scenario_id":"1","gid":"1","name":"Test"} 
#Sample body delete
{"mode":"delete","table_name":"pois","gid": "1","scenario_id":"1"} 


#Relevant tables: 

pois_modified
buildings_modified
ways_modified
population_modified

#Maybe check Majks code here: https://github.com/majkshkurti/deeptime/blob/master/app/api/controllers/gis/layerController.js

**Comment by EPajares** [comment]
Example Update SQL

`UPDATE pois_modified geom = ST_GEOMFROMTEXT('POINT(11.4543 48.1232)')
WHERE gid = 1 
AND scenario_id = 1`
