### ISSUE TITLE
WALKIE: adjust style according to data availability

### ISSUE THREAD

**Issue by UJehle** [goat-community/goat#996]
if we e.g. only have data for 10 out of 20 walkability indicators for one link, we should somehow represent this uncertainty in the style.
Idea: make the path (10/20)=50% transparent

**Comment by UJehle** [comment]
@majkshkurti would be great if you could create a similar style that we had in the Hackathon with the Vectortiles. Soon we will also have an additional column, that indicates how good the data quality is. Depending on the value of the data quality column we can then set the transparency.

**Comment by majkshkurti** [comment]
Line transparency for lines it's changing the color and doesn't look good in the screen.
